gitcoinco/grants-stack

packages/contracts/contracts/GrantRoundFactory.sol
packages/contracts/contracts/program/ProgramFactory.sol
packages/contracts/docs/CHAINS.md
packages/contracts/scripts/config/program.config.ts
packages/contracts/scripts/config/round.config.ts
packages/contracts/scripts/round/createGrantRound.ts

- ensure event is indexable on creation
- add prefix `_` to internal variable
- when round is created, expect deployer to pass program address (solely used for firing an event) 
programFactoryContract : 0x1542143A64DcFa25Ddeb3CAf79F538B4a04F3FDd
programImplementationContract:  0x54457339Ca7Cc674f035ed2456d68631672733b7
Program created:  0xbd4b0db965d02308fd7b7f31eb25ec010cdbee3c5aa72f82a9e88f8176f6b6f0
grantRoundFactoryContract :  0x2f97819a05051cC0983988B9E49331E679741309
grantRoundImplementationContract: 0xc2B040cdd5fba17779ca2d81c4214d590Db885A9
GrantRound created:  0x0cdabe49c870238732bf35ee86686ca8c471bee95e1bcf287d6ea2a1f26f6d67

chore: tweaks based on feedback to factory contracts

---

packages/contracts/contracts/GrantRoundFactory.sol
packages/contracts/contracts/GrantRoundImplementation.sol
packages/contracts/docs/CHAINS.md
packages/contracts/scripts/config/round.config.ts

Currently the admin role of the grant was set to the factory address 
This PR ensures 
- the caller of the contract is indeed set as the admin 
- GrantContract uses AccessControlEnumerable 
Tested on testnet & documentation has been updated with latest contract
https://goerli.etherscan.io/address/0xb42db2ac7f8c1506f2642d398e4762e18667ca9a#events

bug: ensure admin_role of grant round is set right

---

packages/round-manager/src/features/api/services/program.ts
packages/round-manager/src/features/api/services/round.ts
packages/round-manager/src/features/api/types.ts
packages/round-manager/src/features/program/ViewProgramPage.tsx
packages/round-manager/src/features/round/RoundDetailForm.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx

This PR uses the subgraph instead of contract interactions to get the list of rounds for a given account/programId
closes #150

feat: use subgraph in round list service

---

CODEOWNERS

Add QEDK as code owner for contracts

chg: Add QEDK as code owner for contracts

---

packages/graph/.gitignore
packages/graph/README.md
packages/graph/config/goerli.json
packages/graph/config/optimism-kovan.json
packages/graph/package.json
packages/graph/subgraph.template.yaml
packages/graph/yarn.lock

- update .gitignore to include subgraph.yaml
- replace subgraph.yaml with subgraph.template.yaml
- add mustache to generate yaml from template
- update readme doc
- add config for networks
closes #158 
| Network        | GITHUB_USER/SUBGRAPH_NAME                 | Playground                                                                             | Query                                                                             |
|----------------|-------------------------------------------|----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|
| goerli         | thelostone-mc/program-factory-v0          | https://thegraph.com/hosted-service/subgraph/thelostone-mc/prog …

feat: allow subgraph to be deploy on multiple networks

---

packages/round-manager/.env.sample
packages/round-manager/src/features/api/__tests__/utils.test.ts
packages/round-manager/src/features/api/contracts.ts
packages/round-manager/src/features/api/services/program.ts
packages/round-manager/src/features/api/services/round.ts
packages/round-manager/src/features/api/utils.ts

- replace hardcoded factory contract with support for multiple network
- add networks -> 
- optimism ( contract address to be set after deploy )
- optimism kovan
- goerli (default)
This PR is in draft state as it's broken and the API query is not tested/ working.  
This should be gotten in after #181 and rebasing 
Closes https://github.com/gitcoinco/grants-round/issues/157

feat: load factory contract based on web3 network

---

packages/graph/docs/Round.md
packages/graph/schema.graphql
packages/graph/src/round/implementation.ts

The graph sets a project application to a round by prefixing the round id to the given project id.
The frontend already sends it with the round id prefixed
This means we can avoid the prefix operation on the graph 
**Expected ID from graph:** 
`0x000000000000000000000000500df079bebe24a9f6ffa2c70fb58000a4722784-0xd96222ec011cded90be74969d0cffdf4247fae1b`
**What graph was doing:** 
`0x000000000000000000000000500df079bebe24a9f6ffa2c70fb58000a4722784-0xd96222ec011cded90be74969d0cffdf4247fae1b-0xd96222ec011cded90be74969d0cffdf4247fae1b`
Additionally, the subgraph schema has been updated to include the project ID as a part of the schema to enable easy quering  
IPFS link: 
https://gitcoin.mypinata.cloud/ipfs/bafkreibmenkpeyaezovxutlqlfsybn7cfaa43zd2zauuywadzsnvvlapb4
Query: 
```
{ …
```

chore: update project id lookup in graph

---

packages/round-manager/src/features/round/ApplicationsReceived.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx

There is a weird bug where after you approve one application, you aren't able to approve a subsequent application.
**Steps to reproduce:**
1. Go to a round with applications ([example](https://rmgitcoin.on.fleek.co/#/round/0xb91fec0b68f39cbfdd75e4f08042c60724e1bd3b))
2. Click "Select" button to begin bulk approval/rejection process
3. Click "Approve" on the first application
4. Click "Approve" on the second application
**Expected behavior:**
Both applications should display as "approved"
**Actual behavior:**
Second application does not display as "approved"
related to #251
Added a small regression test for the approve case

fix: fix a bug where user was unable to approve/reject some applications

---

packages/round-manager/src/features/api/services/grantApplication.ts
packages/round-manager/src/features/common/ConfirmationModal.tsx
packages/round-manager/src/features/round/ApplicationsReceived.tsx
packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx

- stick bulk approval continue button to bottom
- added test to verify bulk approval confirmation modal content
- confirmation modal uses isOpen/setIsOpen props instead of managing internal state
- inline ipfsHash in updateProjectsMetaPtr in updateGrantApplication api
closes #252

fix: stick bulk approval continue button to bottom

---

packages/round-manager/README.md

| Env     | Git Branch | URL                               |
|---------|------------|-----------------------------------|
| STAGING | main       | https://rmgitcoin.on.fleek.co/    |
| LIVE    | release    | https://round-manager.gitcoin.co/ |
fixes https://github.com/gitcoinco/grants-round/issues/241
Links are documented above

chore: add link to staging + live env

---

packages/round-manager/src/app/wagmi.ts
packages/round-manager/src/features/round/ApplicationsReceived.tsx

Bulk select was no longer possible as every area of the application card is linked to the detail page. This PR makes only the card content area clickable
refers #280

fix: make bulk select icons clickable

---

README.md
packages/round-manager/.env.sample
packages/round-manager/README.md
packages/round-manager/docs/MONITORING.md
packages/round-manager/package.json
packages/round-manager/src/datadog.tsx
packages/round-manager/src/features/common/NotFoundPage.tsx
packages/round-manager/src/features/program/CreateProgramPage.tsx
packages/round-manager/src/features/program/ListProgramPage.tsx
packages/round-manager/src/features/program/ViewProgramPage.tsx
packages/round-manager/src/features/round/CreateRoundPage.tsx
packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/index.tsx
packages/round-manager/yarn.lock

- add @datadog/browser-logs, @datadog/browser-rum
- add documentation on how monitoring should be used
- create default logging for routes
- init datadog
Additionally
- staging env on fleek has been populated with env variables meant for staging
- production env on fleek has been populated with env variables meant for production
fixes https://github.com/gitcoinco/grants-round/issues/242

feat: add datadog monitoring

---

packages/round-manager/src/constants.ts
packages/round-manager/src/features/api/services/ipfs.ts
packages/round-manager/src/features/common/ErrorModal.tsx
packages/round-manager/src/features/common/ProgressModal.tsx
packages/round-manager/src/features/common/__tests__/ProgressModal.test.tsx
packages/round-manager/src/features/program/CreateProgramPage.tsx
packages/round-manager/src/features/program/__tests__/CreateProgramPage.test.tsx
packages/round-manager/src/features/program/__tests__/ErrorModal.test.tsx
packages/round-manager/src/features/round/RoundApplicationForm.tsx
packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx

- show an error icon in the progress modal if a step fails
- replace progress modal with an error modal after ~3 seconds
fixes #275
- ProgressModal.test.tsx
- CreateProgramPage.test.tsx
- RoundApplicationForm.test.tsx
Example screenshots:

feat: add error states to processing modal

---

packages/round-manager/src/features/api/services/grantApplication.ts

This covers a scenario where the project metaPtr hasn't been set yet.
Aka all projects are in pending state
https://discord.com/channels/562828676480237578/1013943021387137035/1013943025275240490
locally tested

bug: handle scenario where operator hasn't reviewed any projects in the round

---

packages/round-manager/src/features/api/__tests__/program.test.ts
packages/round-manager/src/features/api/services/grantApplication.ts
packages/round-manager/src/features/round/ApplicationsApproved.tsx
packages/round-manager/src/features/round/ApplicationsReceived.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx
packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx
packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx

- based on discussion with Eduardo, bulk select button is moved into individual tabs, instead of on top
- move bulk select button into received applications tab
- add bulk select button into approved applications tab
other:
- also fixes #316 bug where applications were incorrectly appearing in approved/rejected tabs
- updates RoundApplicationForm.test.tsx to silence `console.error` logs during test runs
- also fixes #319 error 3 - lit-sdk error during test run
fixes #303
- ApplicationsApproved.test.tsx
- ApplicationsReceived.test.tsx
- ViewRoundPage.test.tsx
- RoundApplicationForm.test.tsx

303  bulk reject approved applications

---

packages/round-manager/src/features/api/__tests__/program.test.ts
packages/round-manager/src/features/round/ApplicationsApproved.tsx
packages/round-manager/src/features/round/ApplicationsReceived.tsx
packages/round-manager/src/features/round/ApplicationsRejected.tsx
packages/round-manager/src/features/round/BulkApplicationCommon.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx

refactor: move button and icon to MarkForApproval component 
tests: just send in bulk select state as if it was already clicked 
refactor: extract cancel and select button JSX to well named components 
refactor: extract no apps message JSX to well named component 
refactor: extract continue and number of apps selected message JSX to well named components 
refactor: extract count of rejected and count of approved JSX to well named components
refactor: extract number of approve / reject JSX into generic component called NumberOfStatus 
refactor: moved back state for bulk select status to be internal to applications received again 
refactor: extract jsx to new well named components ApprovedApplicationsCount and RejectedApplicationsCount 
refactor: move text for additional gas fees to shared …

refactor: added confirming text to approved tab

---

packages/grant-explorer/package.json
packages/grant-explorer/src/context/RoundContext.tsx
packages/grant-explorer/src/context/__tests__/RoundContext.test.tsx
packages/grant-explorer/src/features/api/__tests__/utils.test.tsx
packages/grant-explorer/src/features/api/round.ts
packages/grant-explorer/src/features/api/types.ts
packages/grant-explorer/src/features/api/utils.ts
packages/grant-explorer/src/features/common/Spinner.tsx
packages/grant-explorer/src/features/common/__tests__/Spinner.test.tsx
packages/grant-explorer/src/features/round/ViewRoundPage.tsx
packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
packages/grant-explorer/src/history.ts
packages/grant-explorer/src/index.tsx
packages/grant-explorer/src/test-utils.tsx
packages/grant-explorer/yarn.lock

- add RoundContext and api/round to be fetch data from graph
- add ViewRoundPage with NotFound + nav + footer
- populate ViewRoundPage with RoundContext
- add faker package
- move api/__tests__/utils.test.ts -> api/utils.test.tsx
fixes: https://github.com/gitcoinco/grants-round/issues/348
https://bafybeicqnyconodzgott5lcokpw6is3e4oahd4vp5fpjxrcnt3lji4qqmm.on.fleek.co/#/round/5/0xa89c6f804579864e29fdbb9653f62d761d1a42fe

feat: add ViewRoundPage

---

packages/round-manager/src/features/common/CopyToClipboardButton.tsx
packages/round-manager/tailwind.config.js

fix: keep copy to clipboard button at the same width through the animation
fix #396

fix: keep copy to clipboard button at the same width through the animation

---

packages/round-manager/src/features/api/__tests__/utils.test.ts
packages/round-manager/src/features/api/utils.ts

application questions now have a non-stub input type associated with them. 
example ipfs hash: ipfs://bafkreig3e7wrfk7qptupqldckndlyq5kgwvgwmwn2knxkdrwsecuwtwjy4/
the possible types are now "text", "number", "email", and are hardcoded for the
fixes #376 
tests fixed to reflect casing change in type field

feat(applicationMetadata): add input types

---

packages/round-manager/src/context/application/ApplicationContext.tsx
packages/round-manager/src/context/program/ReadProgramContext.tsx
packages/round-manager/src/features/api/types.ts
packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
packages/round-manager/src/test-utils.tsx

- verify credentials against project metadata instead of application answers
- verification should be case-insensitive
- always refetch application data to get project owners for verification
- use round context provider in application page instead of RTK Query
fix #427

fix: read project socials from project metadata

---

packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
packages/round-manager/src/test-utils.tsx

use new application friendly labels when displaying answers on application detail page
#430 updated the application schema to use human-friendly labels for the questions. However, the application detail page was hard-coded to the old labels. This change updates the application detail page to read application answers using the new labels.
NOTE -- this is currently not backward-compatible -- applications submitted with the "old" labels will not show correct answers on the application page anymore
fix bug introduced in PR #452 (original story: #430)

fix(rm): use new application friendly labels when displaying answers

---

.husky/pre-push
packages/round-manager/.eslintrc.js
packages/round-manager/package.json

ignore the eslint unused variable pattern if the variable name is exactly `_`
Fixes #455

chore(githooks): make eslint fail on warnings to unify ci and local behaviour

---

packages/round-manager/src/context/application/BulkUpdateGrantApplicationContext.tsx
packages/round-manager/src/context/application/__tests__/BulkUpdateGrantApplicationContext.test.tsx
packages/round-manager/src/context/program/CreateProgramContext.tsx
packages/round-manager/src/context/program/__tests__/CreateProgramContext.test.tsx
packages/round-manager/src/context/round/CreateRoundContext.tsx
packages/round-manager/src/context/round/__tests__/CreateRoundContext.test.tsx
packages/round-manager/src/features/api/application.ts
packages/round-manager/src/features/program/CreateProgramPage.tsx
packages/round-manager/src/features/round/ApplicationsApproved.tsx
packages/round-manager/src/features/round/ApplicationsReceived.tsx
packages/round-manager/src/features/round/ApplicationsRejected.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx
packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx
packages/round-manager/src/index.tsx
packages/round-manager/src/test-utils.tsx

- create BulkUpdateGrantApplicationContext 
- use new useBulkUpdateGrantApplications in ApplicationsReceived, ApplicationsApproved, Applications Rejected
- clear error statuses when create or update operations are retried
- show progress modal on bulk approve/reject 
fix #400

feat: show progress modal on bulk approve/reject 

---

packages/round-manager/src/features/common/ErrorModal.tsx
packages/round-manager/src/features/common/ProgressModal.tsx
packages/round-manager/src/features/common/__tests__/ProgressModal.test.tsx
packages/round-manager/src/features/program/__tests__/ErrorModal.test.tsx
packages/round-manager/src/features/round/RoundApplicationForm.tsx

the dialog component from headlessui currently doesn't support simultaneous dialogs.
even though the progress modal should close at the same time the error modal opens,
they will exist simultaneously due to the transition animation time.
the recommended fix is to either nest the dialogs,
or delay the opening of the second dialog until the end of the first dialog's animation.
fixes #449

fix: nest error modal inside progress modal to prevent scroll locking

---

packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx
packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
packages/round-manager/src/index.tsx

feat: add progress modal on application details page
- grouped ViewApplicationPage.test.tsx tests into a "verification badges" describe block
- added tests for confirmation modal logic on ViewApplicationPage
- redirect to round page after process completes
- fix margin top on Approve / Reject buttons
fix #401

feat: add progress modal on application details page

---

packages/graph/docs/Round.md

update `package/graph` documentation
- add "applications by project id" query
- reword previous query descriptions to be clearer

docs(graph): add applications by project id query. reword previous query description

---

packages/grant-explorer/package.json
packages/grant-explorer/src/context/BallotContext.tsx
packages/grant-explorer/src/context/RoundContext.tsx
packages/grant-explorer/src/context/__tests__/BallotContext.test.tsx
packages/grant-explorer/src/features/api/LocalStorage.ts
packages/grant-explorer/src/features/api/__tests__/localstorage.test.ts
packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
packages/grant-explorer/src/index.tsx
packages/grant-explorer/src/setupTests.ts
packages/grant-explorer/src/test-utils.tsx
packages/grant-explorer/yarn.lock

feat: add project to ballot when Back this project is clicked
- wrap RoundProvider around all routes instead of individually
- add ballot selection button to project detail page
fixes #353
**Testing:**
[GE preview link]/#/round/5/0xe7e8c1021da7b811b2303f70ec1a0b5adec8eaf2

#353 - Grant Explorer -  add to ballot

---

packages/contracts/contracts/round/RoundImplementation.sol
packages/contracts/contracts/votingStrategy/IVotingStrategy.sol
packages/contracts/contracts/votingStrategy/QuadraticFundingStrategy/QuadraticFundingVotingStrategyImplementation.sol
packages/contracts/docs/contracts/round/RoundImplementation.md
packages/contracts/docs/contracts/votingStrategy/IVotingStrategy.md
packages/contracts/docs/contracts/votingStrategy/QuadraticFundingStrategy/QuadraticFundingVotingStrategyImplementation.md
packages/contracts/test/_votingStrategy/QuadraticFundingVotingStrategyImplementation.test.ts
packages/contracts/test/payoutStrategy/MerklePayoutStrategy.test.ts

The goal here is to update the QFVotingStrategyImplementation contract to support native tokens transfer and not just ERC20.
All we would have to do here in the vote function :
fixes #496

feat: update QFVotingStrategy to allow native token transfer

---

packages/grant-explorer/src/features/api/round.ts
packages/grant-explorer/src/features/api/types.ts
packages/grant-explorer/src/features/round/ViewRoundPage.tsx
packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
packages/grant-explorer/src/test-utils.tsx

As a round operator, I want to configure what the application page will say on Grant Explorer
So that I can tell potential grantees exactly how to get involved in my round.
Todo: 
fixes #474

Add round details to application view page

---

packages/round-manager/src/features/api/utils.ts
packages/round-manager/src/features/round/RoundApplicationForm.tsx
packages/round-manager/src/features/round/RoundDetailForm.tsx
packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx

feat: add QF section + payout token #504

---

packages/round-manager/src/features/api/contracts.ts

The ProjectRegistry contract addresses in `packages/round-manager/src/features/api/contracts.ts` were accidentally overwritten during the contract update changes from #566 
The ProjectRegistry is managed by Grant Hub team, and the addresses have not changed -- the PR returns them to the previous values
For reference, Project Registry deployments are here: https://github.com/gitcoinco/grant-hub/blob/development/client/src/contracts/deployments.ts
fixes #576

fix: revert project registry contract addresses to correct values

---

CODEOWNERS

As per Oct 27 Retro action item: add Melissa + Nate to default PR reviewer list, so they will automatically be tagged as reviewers for all PRs
Also removing myself and Dave since today is our last day with RM/GE team 😭

chore: add nate and melissa to CODEOWNERS. remove shavina and dave

---

packages/round-manager/src/features/round/RoundApplicationForm.tsx

Adjusts the Edit application question title button to the new design from Figma
fixes #582
Tests not affected

feat(rm): add new save edit button design

---

packages/round-manager/src/features/program/CreateProgramPage.tsx
packages/round-manager/src/features/round/ApplicationsApproved.tsx
packages/round-manager/src/features/round/ApplicationsReceived.tsx
packages/round-manager/src/features/round/ApplicationsRejected.tsx
packages/round-manager/src/features/round/BulkApplicationCommon.tsx
packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx
packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx

when there is an error during the approve/reject flow, the error modal should appear with "Try Again" or "Done" options. this is the same error modal that appears during round creation and program creation flows
fixes #593

add error modal for bulk approve/reject application

---

packages/grant-explorer/src/features/ViewBallotPage.tsx
packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx

- updates UI to implement add to shortlist
WHEN I click to add a project to my ballot
THEN the project is added to my shortlist
WHEN I have projects on my shortlist
THEN I see the projects in the Shortlist section of the page
WHEN I do not have projects on my shortlist
THEN I see the empty shortlist copy and "Browse Projects" button
WHEN I click on the "Browse Projects" button
THEN I am brought to the round explorer page
closes #485

feat: add to shortlist

---

packages/contracts/docs/CHAINS.md
packages/contracts/scripts/config/payoutStrategy.config.ts
packages/contracts/scripts/config/program.config.ts
packages/contracts/scripts/config/round.config.ts
packages/contracts/scripts/config/votingStrategy.config.ts
packages/grant-explorer/src/app/wagmi.ts
packages/graph/config/optimism.json
packages/round-manager/src/app/wagmi.ts
packages/round-manager/src/features/api/contracts.ts

- deploy contracts
- update round manger + grant explorer to support optimism mainnet
- deploy subgraph for optimism mainnet
fixes #662
- #/program/0x228907b3b4c4877885320654b98465daf62c3766
- #/round/0xe0883e6f3113fc4c2d9539b9ee1659e59531e312
- https://thegraph.com/hosted-service/subgraph/gitcoinco/grants-round-optimism-mainnet

feat: enable optimism mainnet support

---

.husky/pre-push

**Note: only relevant for Engineering.**
Yarn printed a warning regarding the passing of -- to the underlying scripts. Removed the -- and removed the yarn prefix to fix this.
Tested locally on latest macOS Ventura ARM Mac

feat(githooks): fix yarn warning re: --

---

packages/round-manager/src/features/api/application.ts

Grants Hub changed the id format from "projectId" to "chainId:projectRegistryAddress:projectId". This PR adds support for this new format. closes #733 
https://discord.com/channels/562828676480237578/1048235936691007519/1048320321419214899

fix(re): fix for new id format

---

packages/api/src/__tests__/utils.test.ts
packages/api/src/types.ts
packages/api/src/utils.ts
packages/api/src/votingStrategies/linearQuadraticFunding.ts

fixes #749 
fixes #769 
This implements a new method that calculates the start and end times of a token. 
It modifies the RoundMetadata to include the start and end times for the round.

feat: added start and average token price function and tests

---

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx

Fix layout for mobile to avoid overlapping and horizontal scrolling.
Before:
After:
N/A
No tests as the changes are just styling fixes.

view project details mobile fix

---

packages/api/src/handlers/summaryHandler.ts
packages/api/src/routes.ts
packages/api/src/types.ts
packages/api/src/votingStrategies/linearQuadraticFunding.ts

This is a refactoring of the endpoints in the API. 
Instead of having a bunch of separate handlers for specific endpoints and usage, this introduces a single endpoint for project and round summaries.
This does not remove any existing endpoints, they should be deprecated as tests and implementations are refactored with the new endpoint. 
The endpoint is `/summary/:chainId/:roundId` and making a GET request with to this endpoint will yield a summary of the round: 
```
GET http://localhost:8000/summary/250/0xebdb4156203c8b35b7a7c6f320786b98e5ac67c3
```
```
{
"success": true,
"message": "fetched round stats successfully",
"data": {
"uniqueContributorCount": 60,
"contributionsCount": 100,
"totalContributionsInUSD": 0
}
}
```
Furthermore, you can also use this endpoint to get project summaries, …

add: Project/Round summary endpoints

---

packages/grant-explorer/package.json
packages/grant-explorer/src/index.tsx
packages/grant-explorer/src/tagmanager.ts
packages/grant-explorer/yarn.lock
packages/round-manager/package.json
packages/round-manager/src/index.tsx
packages/round-manager/src/tagmanager.ts
packages/round-manager/yarn.lock

The react-gtm-module doesn't appear to log the URL fragments, so switch over to react-ga4 to see if it solves the issue.  This module appears to be more focussed on support for Google Analytics 4.
Difficult to test this as it's using an external service.

Tagmanager url fragment fix

---

packages/round-manager/src/features/api/application.ts

due to graphs limit of 100 results, not all projects are shown in round manager. to fix this, the limit is set to 1000

fix: query first 1000

---

packages/api/src/votingStrategies/linearQuadraticFunding.ts

It looks like in the current implementation the usdValue is not set for the very first contribution made by the contributor.
This causes that value to be ignored and results in negative matching for projects with 2 contributions 
Additionally my hunch is that when a project has 1 contribution , it would be ignored and the percentage would be 0

bug: ensure first contributions usd value is populated

---

packages/api/src/utils.ts

- Adds temporary util function which swaps BUSD price for DAI price on fantom as coingecko does not support this 
- This works only for matching endpoint (The summary endpoints still have this issue)
- A follow up issue is to be created to ensure we have a cleaner solution which can be used across all 3 endpoints to handle scenarios where coingecko doesn't have the rate of the token on a given chain ID
fixes #1043

1043 coingecko price

---

packages/grant-explorer/src/features/common/Navbar.tsx
packages/grant-explorer/src/features/common/NotFoundPage.tsx
packages/grant-explorer/src/features/common/PassportBanner.tsx
packages/grant-explorer/src/features/common/RoundEndedBanner.tsx
packages/grant-explorer/src/features/round/PassportConnect.tsx
packages/grant-explorer/src/features/round/ThankYou.tsx
packages/grant-explorer/src/features/round/ViewBallotPage.tsx
packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
packages/grant-explorer/src/features/round/ViewRoundPage.tsx

As a user
I want to click on the Grants Explorer icon in the nav bar
So that I can go back to the main landing page
fixes #1013

feat: sticky nav bar

---

packages/api/.env.sample
packages/api/package.json
packages/api/src/sybilProtection/__tests__/passport.test.ts
packages/api/src/sybilProtection/passport.ts
packages/api/src/test-utils.ts
packages/api/src/types.ts
packages/api/src/votingStrategies/linearQuadraticFunding.ts

**Description**
Looks like passport bulk API is quite slow.
Fetching all passport score for a given community requires a GET call which limits results to 1000.
and each call takes about 3 seconds and currently there are 8000 stamps (and this will increase over time)
We will need to figure out a more scalable solution
fixes https://github.com/gitcoinco/grants-round/issues/990

feat: wire in passport

---

packages/grant-explorer/src/features/round/ViewRoundPage.tsx

As a donor
I want to be able to check my Passport score after the Alpha rounds end
So that I know if my score is eligible for matching
fixes #1062

feat: temporarily allow Passport banner post-round

---

packages/builder/src/actions/projects.ts

During the first alpha round, we created applications with the wrong chain id (using the round chain instead of the project chain). This was a fix to display the applications with
the wrong application id. 
Removing this fix now that the app id's are correct.

fix: app load fix

---

packages/common/src/index.ts
packages/grant-explorer/src/features/common/PassportBanner.tsx
packages/grant-explorer/src/features/round/PassportConnect.tsx
packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx

Fixes #1113 
This makes the error message a bit more clear to the user (and us) when the passport API returns an error.
I also added Datadog logging to our passport connection logic to make it easier to troubleshoot in case we don't have a way to repro (like in this case).

fix: tweaked error message for passport failures, added Datadog logging

---

packages/grant-explorer/src/features/common/CustomerSupport.tsx

This should fix the error we are seeing in the prod deployment:
```
2:58:13 PM 02/10/2023: Failed to compile.
2:58:13 PM 02/10/2023: TS2322: Type 'ForwardRefExoticComponent<SVGProps<SVGSVGElement> & { title?: string | undefined; titleId?: string | undefined; }>' is not assignable to type '(props: SVGProps<SVGSVGElement>) => Element'.
2:58:13 PM 02/10/2023: Type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not assignable to type 'Element'.
2:58:13 PM 02/10/2023: Type 'null' is not assignable to type 'ReactElement<any, any>'.
2:58:13 PM 02/10/2023: 17 | export const menuItems: Menu[] = [
2:58:13 PM 02/10/2023: 18 | {
2:58:13 PM 02/10/2023: > 19 | Icon: BookOpenIcon,
2:58:13 PM 02/10/2023: | ^^^^
2:58:13 PM 02/10/2023: 20 | title: "Grants Explorer Guide",
2:58:13 PM …
```

fix: production build fail

---

.github/workflows/api.yml
.github/workflows/builder.yml
.github/workflows/contract.yml
.github/workflows/grant-explorer.yml
.github/workflows/graph-project-registry.yml
.github/workflows/graph-round.yml
.github/workflows/round-manager.yml

We're currently executing duplicate actions on each push for a PR, with 7 workflows inside the repository it gets really noisy.
This PR reduces the checks from 18 to 11.
It implements the following behavior for all our workflows:
- All pushes to `main` and `release` will run checks, regardless if they're part of a PR or not, this includes merges
- Commits pushed to branches that have a PR will run checks once
- Commits pushed to branches that don't have a PR will not run checks

Fix duplicate Github Action runs

---

packages/round-manager/.env.sample
packages/round-manager/src/app/wagmi.ts

note: I added the Infura env var and left the Alechmy one as a dummy var, until we sort it out, to our fleek round manager deployments. 
Be sure to check the new .env.example. 
It will still fallback to the public key if not on mainnet because we have not setup infura/alchemy for each project and chain (which incurs additional costs). 
But at least on mainnet - it should use our production infura key. 
fixes #1173

fix: add alchemy/infura key usage and priority to wagmi

---

packages/contracts/.openzeppelin/unknown-31337.json
packages/contracts/contracts/payoutStrategy/IPayoutStrategy.sol
packages/contracts/docs/contracts/payoutStrategy/IPayoutStrategy.md
packages/contracts/docs/contracts/payoutStrategy/MerklePayoutStrategy/MerklePayoutStrategyImplementation.md
packages/contracts/docs/upgrades/IPayoutStrategy/v0.2.0.md
packages/contracts/test/payoutStrategy/IPayoutInterface.test.ts

Removing [remove reclaimLockEndTime](https://github.com/gitcoinco/grants-round/commit/7b545db4bf1dbd4d5c05a94cb0edc03ae6fec05f) as it adds no value in this point
Currently this value is set on init based on the round end time BUT the round end time can change over the course of the round and that makes data inconsistent. It’s smarter to always fetch the latest round and then add the time lock
Also since this check is used only in withdraw. Moving this into the function is cheaper than having a modifier which won’t be used by anyone else

chore: remove reclaimLockEndTime

---

packages/grant-explorer/src/features/api/utils.ts
packages/round-manager/src/features/api/round.ts
packages/round-manager/src/features/api/utils.ts
packages/round-manager/src/features/round/FundContract.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/features/round/ViewRoundResults.tsx
packages/round-manager/src/features/round/__tests__/FundContract.test.tsx
packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx
packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx

As a program manager
I want to see the funding pool details of my round
So that I can reference them during operations
Acceptance Criteria
fixes #1146

Add contract details to Fund Contract tab

---

packages/builder/src/components/grants/inputs.tsx

This adds a tooltip to the project application description for markdown support and also to the question answers that are paragraph type.
Closes #1209

wip: add tooltip to project form and paragraph answers

---

packages/builder/src/components/application/Form.tsx

See Discord thread: https://discord.com/channels/562828676480237578/1095761375751569512
Fixes the non-required fields to not be undefined and an empty string instead when the user does not answer the question.

make sure undefined is an empty string for answer text

---

packages/builder/src/components/base/ImageInput.tsx
packages/builder/src/components/base/ProjectForm.tsx
packages/builder/src/components/base/images/ImageCrop.tsx
packages/builder/src/components/base/images/buildCanvas.ts

- Simplify the image cropping code
- Apply a resize to avoid uploading huge images
- Use JPEG instead of PNG for a x5 image size reduction
This PR + changing our IPFS gateway to our CDN (https://ipfs-grants-stack.gitcoin.co) should reduce our costs to almost nothing.
In the future we can also optimize and convert images to other formats (like webp) on the fly based on the user agent, we can do this with Cloudfront.
More discussion here:
https://github.com/gitcoinco/grants-stack/issues/1395
https://github.com/gitcoinco/grants-stack/discussions/1129

Fix Builder Image Sizes

---

packages/builder/src/components/grants/Landing.tsx
packages/builder/src/components/providers/Github.tsx
packages/builder/src/components/providers/Twitter.tsx
packages/builder/src/components/providers/identity/__tests__/credentials.test.ts
packages/builder/src/components/providers/identity/credentials.ts
packages/builder/src/hooks/useValidateCredential.tsx
packages/builder/src/index.tsx

This PR simplifies and adds better error handling amongst other refactorings.
- The BroadcastChannel callback happens inside React, this is not ideal because React could re-render the component or even not render at all, there could be a redirect etc. Since this is not related to the UI at all it now happens in the index script before anything else, this will ensure things are being called.
- Separate unexpected errors from Verification errors and surface them to the user instead of silencing, also callback with errors from OAuth which at the moment they're silenced as well.
- Unify all the logic to create credentials from OAuth instead of having relying on `useEffect`, this will ensure errors happening with this procedure will always be caught instead of just doing nothing
- Give …

Twitter and Github Verification Fixes

---

packages/grant-explorer/src/features/round/ViewRoundPage.tsx

The pre-round page on the Explorer isn't showing its [proper layout](https://explorer.gitcoin.co/#/round/1/0x421510312c40486965767be5ea603aa8a5707983). We want to clean up the design to match this [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=483-10998&t=wMy7pAZ3lbml5Ctb-4)
#1439

Explorer pre round page cleanup

---

packages/round-manager/src/context/application/BulkUpdateGrantApplicationContext.tsx

resolves https://github.com/gitcoinco/grants-stack/issues/1557
Issues:
- Row index is calculated wrong  from application index
- Mutating applications received in `_bulkUpdateGrantApplication`
- Using application index as a column index
- Cancelled status is wrong
- Rows and applications don't need to be sorted
This PR also refactors some small things and renames the variables a bit to make things more readable an easy to follow. I didn't want to change too much to avoid introducing other issues.

Fix Set Application Statuses

---

packages/round-manager/.env.sample
packages/round-manager/src/features/program/ViewProgramPage.tsx
packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
packages/round-manager/src/hooks.ts

This PR adds a debug mode to the Manager app, which allows you to see rounds you normally don't have access to (for example to test a production round), access pages that might be disabled (for example the round results page) for testing and debugging, this is how it works:
`REACT_APP_ALLOW_URL_DEBUG_MODE=true`
When this environment variable is `true` it allows enabling debug mode via a URL query param, for example:
http://localhost:3000/#/round/0x6e8dC2e623204D61b0E59E668702654aE336c9f7?debug=true
Will enable debug mode for that page.
This option is useful for testing in staging or even production, where we only want to enable debug mode when convenient but not all the time.
`REACT_APP_DEBUG_MODE=true`
This environment variable enables debug mode all the time, this can be useful in …

Add debug mode

---

packages/builder/package.json
packages/builder/src/actions/projects.ts
packages/grant-explorer/package.json
packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
pnpm-lock.yaml

depends on https://github.com/gitcoinco/allo-indexer-client/pull/14
This fixes the project stats for Builder and Explorer.
To clarify things, when we get applications from the indexer you get actual applications, not projects, so you can have multiple applications for a single project. The application ID is the index for new rounds and it's the projectId for old rounds (because we don't have an index), so we need to explicitly use `.projectId` if we want to filter by project.
We need to test this for new rounds as well not just old.

Fix Project stats in Builder and Explorer

---

packages/builder/src/services/lit.ts
packages/round-manager/src/features/api/lit.ts

While working on [#1484](https://github.com/gitcoinco/grants-stack/issues/1484) I noticed that the Lit class has a race condition, if you call decrypt or encrypt multiple times it will load the client multiple times as well, this prevent it form happening.

Fix Lit Protocol Connection Race Condition

---

packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx

modifies the modal so that there is a new step.
Upload distribution to IPFS -> Set hash in Contract -> Set as Ready for Payout -> Final step (don't what what it's for but it's in the designs and all the other modals)
the code isn't ideal, but the whole context and handling of finalizing to contract needs to be redone anyway, so this is temporary.
fixes #1764

feat: separate ipfs and contract upload steps during finalization

---

packages/round-manager/src/features/round/ViewFundGrantees.tsx
packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx

I noticed we're using the match percentage in the Fund grantees page: https://github.com/gitcoinco/grants-stack/blob/0e74007cff1b29d130c160dfe402ece47c758a48/packages/round-manager/src/features/round/ViewFundGrantees.tsx#L386
I would rather calculate it using the round Match amount but this should suffice for now.
This also fixes the USD conversion.

Fund Grantees Fixes

---

packages/round-manager/src/features/api/types.ts
packages/round-manager/src/features/round/RoundDetailForm.tsx
packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
packages/round-manager/src/test-utils.tsx

As a Program Manager
I want to make my round public or private
So that I can choose if I want my round to be visible on the Explorer homepage
fixes #1651

Manager: add ability to set a round or edit a round to be public or private

---

packages/grant-explorer/src/features/common/NavbarCart.tsx

closes #1545 
* Re-exported original cart svg to avoid having always a space on top even without items in the cart
* Updated badge position with negative numbers to keep the cart icon always centered
* Moved badge background outside the svg, with just css
* Set higher badge width when count is > 99
Before:
---------------
Now with 0, 1, 10, 100 items:

updated cart icon and styles to fix alignment

---

packages/grant-explorer/src/features/api/rounds.ts
packages/grant-explorer/src/features/discovery/LandingPage.tsx

Cleans up the explorer landing page:
- Add [Greenpill Q2 2023 round](https://explorer.gitcoin.co/#/round/10/0x4195cd3cd76cc13faeb94fdad66911b4e0996f38) (confirmed real round)
- Hide [Meg's test round](https://explorer.gitcoin.co/#/round/10/0xde272b1a1efaefab2fd168c02b8cf0e3b10680ef)
Closes #1869 
Tested locally

[1869] chore: clean up explorer landing page

---

packages/grant-explorer/src/features/round/ThankYou.tsx

closes #1940 
with this PR we encode the URI components of the twitter share URL to solve the bug described in #1940 
After merging this directly to release I will cherry-pick the commit and create a new PR for main

encode params in the twitter share URL in the thank you page

---

packages/round-manager/src/features/round/RoundDetailForm.tsx

Changes round creation behaviour as per [Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?type=design&node-id=2058%3A44553&t=72M3DAIH6udXhBQJ-1) and [Loom walkthrough](https://www.loom.com/share/0088cad637a14e86bbbda735a32da47b).
@willsputra I added a tooltip as well, let me know if you want me to remove it.
Fixes #1840

[1840] Manager: allow applications and round period to overlap

---

packages/builder/src/components/grants/About.tsx
packages/builder/src/components/grants/Details.tsx
packages/builder/tailwind.config.js

fixes #1891 By restructuring the `showTabs` boolean logic. If true, the about section will be shown inside of the navigable tab panel, otherwise just show the about section (e.g. when previewing).

fix: builder project preview

---

packages/grant-explorer/src/features/round/ThankYou.tsx

What the title says.
Closes #1947 
Note: one of the reported whitespaces is actually in the round name. Asking if we should try to fix that too, but my guess is that we should not.

[1947] fix: remove spacing and add newline in twitter message

---

packages/grant-explorer/src/assets/DonationHistoryBanner.tsx
packages/grant-explorer/src/features/api/round.ts
packages/grant-explorer/src/features/api/utils.ts
packages/grant-explorer/src/features/common/StatCard.tsx
packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
packages/grant-explorer/src/features/contributors/__tests__/ViewContributionHistory.test.tsx
packages/grant-explorer/tailwind.config.js

As a DONOR
I want to distinguish my donations to Active Rounds vs. Past Rounds
So that I can easily find my donations
As a donor
I want to see my Donation History page on mobile
So that I can view my donations on my phone
As a DONOR
I want to be able to navigate to and from my profile
so that I can easily check my donation history
fixes #1898 
fixes #1928 
fixes #1900

Explorer: Implement Past and Active round split on Donation History page

---

packages/builder/package.json
packages/grant-explorer/package.json
packages/grant-explorer/public/index.html
packages/round-manager/package.json
packages/round-manager/public/index.html

This PR adds a metatag in the index.html page with the git sha of the latest commit in the build.
This allows us to check the version deployed in each environment for each front-end app.
`Builder` already had it, we simplified it removing the env variable needed for cloudflare pages.

add a metatag in the index.html page with the git sha of the latest commit in the build

---

packages/builder/.eslintrc.js
packages/builder/src/actions/roundApplication.ts
packages/builder/src/components/application/AboutProject.tsx
packages/builder/src/components/application/DetailSummary.tsx
packages/builder/src/components/application/Form.tsx
packages/builder/src/components/application/FullPreview.tsx
packages/builder/src/components/application/ProjectTitle.tsx
packages/builder/src/utils/RoundApplicationBuilder.ts
packages/builder/src/utils/projects.ts

- splits out the huge Apply.tsx in builder (1200-line files are not ok 😬)
- disables the eslint rule to prefer default exports on files with single export (prefer named exports to prevent mis-naming imports)
- removes eslint-ignores of the aforementioned rule
- fixes the error for applications not open

chore: split up Apply component and disable default export eslint rule

---

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/features/round/ViewRoundSettings.tsx
packages/round-manager/src/features/round/ViewRoundStats.tsx

fixes #2261 
Fixes FTM matching funds being displayed as ETH in various places in explorer and manager, by checking for chainId as well as the token name.

fix: eth -> ftm token 

---

.github/workflows/builder.yml
package.json
packages/grant-explorer/src/features/api/__tests__/utils.test.tsx
packages/grant-explorer/src/features/api/utils.ts
packages/round-manager/src/features/api/__tests__/utils.test.ts
packages/round-manager/src/features/api/utils.ts
packages/round-manager/src/features/round/ViewApplicationPage.tsx

- fixes #2332 
- fixes bug with pinata URL being double-prefixed with https on vercel
superseded by https://github.com/gitcoinco/grants-stack/pull/2339

fix: rename arbitrum one to arbitrum for lit js  sdk

---

packages/grant-explorer/src/features/categories/CategoriesGrid.tsx
packages/grant-explorer/src/features/categories/CategoryCard.tsx
packages/grant-explorer/src/features/categories/hooks/useCategories.ts
packages/grant-explorer/src/features/common/styles.ts
packages/grant-explorer/src/features/discovery/CardBanner.tsx
packages/grant-explorer/src/features/discovery/LandingPage.tsx
packages/grant-explorer/src/features/discovery/RoundCard.tsx
packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx

- Fixes #2490
- Fixes #2491 
There are some complexities in building a carousel for the categories. We could use something like this but it adds a dependency and doesn't really feel that great to use.
- https://react-multi-carousel.vercel.app
In this PR I've used a simple approach of just overflow-scroll and widening the container on xl screens. The scrollbar can be hidden with CSS.

Explorer: [2490] Add categories

---

packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx
packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
packages/grant-explorer/src/hooks/matchingEstimate.ts

feat: don't display matching estimates for polygon

---

packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx
packages/grant-explorer/src/hooks/matchingEstimate.ts

feat: re-enable matching estimates for polygon

---

packages/grant-explorer/src/features/api/rounds.ts

Fixes: #2724 
Remove one of the ACS rounds from explorer homepage
This PR:

Remove one of the ACS rounds from explorer homepage

---

packages/grant-explorer/src/features/discovery/LandingHero.tsx

Fixes: #2741 
update numbers on the main explorer page
This PR:

feat: update numbers on main page

---

packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx

Fixes: #2702
adds a useEffect that clears expired rounds (their projects) from cart on checkout page. this method incurs no additional network requests.
This PR:

feat: clear projects from expired rounds from cart

---

packages/builder/src/actions/projects.ts

Fixes: #2746
this constrains the project created and updates `getLogs` call on Polygon PoS to since the ProjectRegistry contract was created. This gives us ample time to move the fetching to the data layer (indexer) before we hit the 5mil block range limit for `getLogs` again.
This PR:

fix: only index from projectregistry contract creation block on polygon pos

---

packages/grant-explorer/src/features/common/Navbar.tsx
packages/grant-explorer/src/features/common/PassportWidget.tsx
packages/grant-explorer/src/index.css

Fixes: #2609 
- Fixes the fonts and background blur and colour of the passport dialog
- aligns the navbar bg color and blur to figma
This PR:

fix: fonts and styles in passport banner and navbarˆ

---

packages/builder/src/actions/rounds.ts

Fixes: #2783 
Fix round application loading error on builder on polygon
This PR:

fix round loading error on builder

---

packages/builder/src/components/base/ImageInput.tsx

Fixes: #2584 
fixes the image upload dialog in builder not accepting jpegs
This PR:

fix: allow jpeg files in image upload dialog in builderˆ

---

packages/round-manager/src/features/round/ViewRoundSettings.tsx

Fixes: #2580 
this fixes the bugs described in the original ticket by Meg.
A follow-up to this ticket is a refactor of the Round Settings page, since it's currently a mess.
This PR:

fix: rolling applications bug on edit page

---

packages/common/src/allo/transaction-sender.ts

Implement ethers transaction sender

---

.github/workflows/common.yml
package.json
packages/common/package.json
packages/common/src/chains.ts
packages/common/tsconfig.json
pnpm-lock.yaml

Fixes: #issue
This makes common isolated from the consumers, as it needs to build the JS code and types and they are included.
This PR:

Fix common, make it an actual package

---

packages/data-layer/src/backends/legacy.ts

closes: #2891
closes: #2882 
Temporary fix to remove test/spam rounds in the explorer. 
Once we switch to the indexer API we can filter directly in the query removing test rounds. 
For now with the subgraph we can't because the metadata needs to be fetched separately, and the roundType (private/public) is in the metadata.

data-layer: filter out spam rounds based on a temporary csv blacklist

---

packages/builder/tailwind.config.js
packages/common/src/components/Footer.tsx
packages/common/src/config.ts
packages/grant-explorer/src/features/common/DefaultLayout.tsx

This PR allows to switch the Allo version configuration at runtime in the front-end.
It adds a switch button to the footer that save an ovverride variable in local storage and reloads the page. 
The default allo version is set as an environment variable and parsed to `config.allo.version`.
Only when `REACT_APP_ENV` is `development` (local and staging-preview environments), `config.allo.version` is overridden with a value set in `localStorage` (`configOverrides["allo-version"]`).
Clicking on the switch buttons toggles the version in local storage and reload the page allowing us to test with the other version.

add allo version switch button to the footer

---

packages/builder/src/utils/AlloWrapper.tsx

Fixes: #2906 
new behaviour in builder: if the current chain id is not supported, we default to mainnet and we automatically show the wrong chain modal from rainbowkit.
This PR:

fix: default to mainnet if chain id is not supported

---

cache/solidity-files-cache.json
packages/builder/.gitignore
packages/builder/package.json
packages/builder/src/__tests__/components/application/Form.test.tsx
packages/builder/src/actions/grantsMetadata.ts
packages/builder/src/actions/projects.ts
packages/builder/src/actions/roundApplication.ts
packages/builder/src/actions/rounds.ts
packages/builder/src/components/application/Form.tsx
packages/builder/src/components/application/FullPreview.tsx
packages/builder/src/components/grants/ApplicationCard.tsx
packages/builder/src/components/grants/rounds/RoundListItem.tsx
packages/builder/src/components/rounds/Apply.tsx
packages/builder/src/components/rounds/Show.tsx
packages/builder/src/components/rounds/ViewApplication.tsx
packages/builder/src/reducers/projects.ts
packages/builder/src/reducers/rounds.ts
packages/builder/src/types/index.ts
packages/builder/src/utils/components.ts
packages/common/src/allo/backends/allo-v2.ts
packages/common/src/allo/roundIdentifier.ts
packages/common/src/index.ts
packages/data-layer/src/data.types.ts
packages/data-layer/src/queries.ts
pnpm-lock.yaml

Flows affected and tested
NOTE: 
- CROSS CHAIN SYNCING PROJECT WILL BE HANDLED ON https://github.com/gitcoinco/grants-stack/issues/2928
- Applications will be shown only when https://github.com/gitcoinco/grants-stack/issues/2856 which will be the next ticket
Fixes: #2788

v2: builder applyToRound

---

packages/common/src/index.ts
packages/data-layer/src/data.types.ts
packages/data-layer/src/queries.ts
packages/grant-explorer/src/features/api/utils.ts
packages/grant-explorer/src/features/discovery/FilterDropdown.tsx
packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx
packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts
packages/grant-explorer/src/features/discovery/utils/__tests__/getExplorerPageTitle.test.tsx
packages/grant-explorer/src/features/discovery/utils/getExplorerPageTitle.ts
packages/grant-explorer/src/features/projects/hooks/useApplication.ts
packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx

This PR fixes the round typevalue that was hardcoded to merkle and remove the checkout box from the sidebar of the application page in case it's a direct grants round.
Direct Grant application example (replace the domain with the one from the preview link):
https://explorer.gitcoin.co/#/round/42161/0x6142eedc06d80f3b362ce43b4ac52fad679dc850/0x6142eedc06d80f3b362ce43b4ac52fad679dc850-22
QF Round application (replace the domain with the one from the preview link):
https://explorer.gitcoin.co/#/round/10/0xf89aad3fad6c3e79ffa3ccc835620fcc7e55f919/0xf89aad3fad6c3e79ffa3ccc835620fcc7e55f919-10

remove hardcoded strategy name from application.round

---

packages/data-layer/src/data-layer.ts
packages/data-layer/src/data.types.ts
packages/data-layer/src/queries.ts
packages/round-manager/src/context/program/ReadProgramContext.tsx
packages/round-manager/src/features/api/__tests__/program.test.ts
packages/round-manager/src/features/api/program.ts
packages/round-manager/src/features/program/CreateProgramPage.tsx
packages/round-manager/src/features/round/__tests__/CreateRoundPage.test.tsx

subtask of https://github.com/gitcoinco/grants-stack/issues/2870
this completes the task to load programs from the indexer and simplifies some things:
- Create program advises user to create a project on Builder (temporary solution until we define the flow)
- Implement loading a single program from the indexer
- Fix and simplify the program types in the data layer
- Create a program in Allo V2 doesn't work, you have to use Builder in Allo V2 mode
- Create a program still works for Allo V1
- In the manager homepage, programs should be loaded for Allo V1 and V2
- You should be able to click and view the rounds of a single program
Video of round creation: https://www.loom.com/share/ebaec99b1ed0485dae5ef5ec1bc9bca4
This PR:

Load Programs from Indexer

---

packages/round-manager/src/features/common/Utils.ts
packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx
packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/features/round/__tests__/ApplicationDirectPayout.test.tsx
packages/round-manager/src/features/round/__tests__/ApplicationsToReview.test.tsx
packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
packages/round-manager/src/test-utils.tsx

Fixes: #issue
this is temporary, I will sort this out in my PR to fetch round from indexer
This PR:

fix direct round view

---

packages/builder/src/actions/rounds.ts

indexer dates are now returned with timezone information, adding Z at the end will make it an invalid ISO date

fix date parsing in builder

---

packages/grant-explorer/src/features/round/ViewRoundPage.tsx

Remove invalid html console warnings converting a `p` tag to `div` to allow `div` child elements

fix(explorer): convert p to div to allow div child elements

---

packages/common/tsconfig.json
packages/data-layer/tsconfig.json

this fixes LSP go to definition when going from one of the dapps to common / data-layer, at the moment when you go to defintion it goes to the `dist` files instead of the source files (like `common/dist/allo.d.ts` instead of `common/src/allo.ts`, which is annoying because you cannot change the source, you have to find the source file manually

fix goto definition

---

packages/common/src/allo/backends/allo-v1.ts
packages/common/src/allo/backends/allo-v2.ts

Fixes: #3099
Test round in case you want to test it manually: https://grants-stack-manager-staging.vercel.app/#/round/0x11f747e641613b86d1db25d53ea6f963ae53bc58
An error happens when applications are moved from `In Review` to other statuses and at least `1` application is left in `In Review`.
This PR fixes it treating `IN_REVIEW` as a `PENDING` status, since `IN_REVIEW` is not a core status in the round contract

fix(Manager): treat IN_REVIEW status as pending for the round contract

---

packages/common/src/allo/allo.ts
packages/common/src/allo/backends/allo-v1.ts
packages/common/src/allo/backends/allo-v2.ts
packages/round-manager/src/context/round/ReclaimFundsContext.tsx
packages/round-manager/src/context/round/__tests__/ReclaimFundsContext.test.tsx
packages/round-manager/src/features/api/payoutStrategy/payoutStrategy.ts
packages/round-manager/src/features/round/ReclaimFunds.tsx
packages/round-manager/src/features/round/__tests__/ReclaimFunds.test.tsx

Fixes: #3138
How to test it:
* switch to Sepolia in your wallet
* open round in Manager `0xb00abdd04cb58b2a8e15d4e382548ee81f5632c4`
* go to the Reclaim Funds tab, it should show `Amount in payout contract: 0 ETH`
* send 0.01 ETH to the Payout Strategy (`0xCa1Cd1cD347a6a2673Ec80Ba0c77e058008e1caA`) with a normal tx from the wallet (without having to use Manager)
* refresh the "Reclaim Funds" tab, it should show `Amount in payout contract: 0.01 ETH`
* Enter your wallet address, click the "Reclaim funds" button and confirm the tx
* Your should receive 0.01 back

implement "reclaim fund" on the allo wrapper

---

packages/builder/src/utils/AlloWrapper.tsx
packages/common/src/index.ts
packages/grant-explorer/src/features/api/AlloWrapper.tsx
packages/round-manager/src/features/api/AlloWrapper.tsx

currently loading explorer & manager with PGN renders a blank page
this also fixes the hack of loading mainnet, which could bring other problems downstream
how to test:
- open explorer with allo v2
- choose pgn
- it shouldn't crash
we might have to look at doing something more elaborate in the future, like showing "unsupported network" but at least without crashing you can still change the network to something else

fix unsupported chains in allov2

---

packages/round-manager/src/features/round/FundContract.tsx

usdglo is not supported by redstone
this fixes the fund contract page so that it doesn't show USD instead of crashing

fix unsupported redstone tokens

---

packages/builder/src/components/application/Form.tsx

This enables reapply only for allo-v2 so that it doesn't break existing flow on v1.
Note: This needs the indexer to be update to be able to track UpdatedRegistration event which is not indexed currently
Here is a sample round:
https://grants-stack-manager-staging.vercel.app/#/round/98
And the project with which I've reapplied
http://localhost:3000/#/chains/11155111/registry/0x/projects/0x663a65b17790c882b4606a423641381db8cbb692f35869344bc35b172c36f364
Fixes: https://github.com/gitcoinco/grants-stack/issues/3254
He

chore:enable reapply

---

packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
packages/grant-explorer/src/features/contributors/__tests__/ViewContributionHistory.test.tsx

Fixes: #3307 
Remove the matching stat card until we fetch that data for the individual cart.
This PR:

3307/ remove matching stat card

---

packages/round-manager/src/features/round/ViewRoundPage.tsx

The "View on Explorer" link on round manager was using the project id instead of the round id. 
This PR fixes the issue
Fixes: #issue
This PR:

Fix "View on Explorer" link

---

packages/grant-explorer/src/features/round/KarmaGrant/GrantItem.tsx
packages/grant-explorer/src/features/round/KarmaGrant/MilestoneItem.tsx
packages/grant-explorer/src/features/round/ViewProjectDetails.tsx

Fixes: gap small updates on wording
Small changes on the [Karma-GAP](https://gap.karmahq.xyz) grant integration
- Changed the position of the no-milestone message to outside the collapsible
- Changed tab title "Grant" => "Milestone updates"
- Fixed: minor bug in which empty milestone updates are displayed
This PR:

[KARMA-GAP] Small changes on the Grant and Milestones component

---

packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx

chore: prevent unchecking all chains in checkout

---

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx

Fixes: 
Addresses project stats sidepanel not displaying neatly on mobile/small screens.
Styling fixes that makes the box auto-scale from row to column depending on screen size.
This PR:

Make projectstats panel collapse on mobile

---

packages/data-layer/src/data-layer.ts
packages/data-layer/src/data.types.ts
packages/data-layer/src/openapi-search-client/models/ApplicationSummary.ts
packages/data-layer/src/queries.ts
packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
packages/grant-explorer/src/features/discovery/LandingTabs.tsx
packages/grant-explorer/src/features/projects/hooks/useApplication.ts

instead of the latest anchor address
Currently, we rely on the anchor address from the project itself. The issue here is that if a project changes it's name, the anchor address changes, which means the new recipient Id is not accounted for on the pool strategy.
This change ensures we use the anchor used at the time of the applying and not the latest anchor address

chore: use anchor address of project at the time of applying

---

packages/builder/src/__tests__/reducers/projects.test.ts
packages/data-layer/src/data-layer.test.ts
packages/data-layer/src/data.types.ts
packages/data-layer/src/queries.ts
packages/grant-explorer/src/checkoutStore.ts
packages/grant-explorer/src/features/discovery/utils/__tests__/getFilterLabel.test.tsx
packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx

Some user have Carts with broken items from previous bugs.
This PR introduces an additional call to the indexer to query and update the application data.
Note: We may want to revert this change in future.
Fixes: #issue
This PR:

Update recipient data on checkout 

---

packages/grant-explorer/src/features/discovery/LandingTabs.tsx

https://discord.com/channels/562828676480237578/1233348739721199687/1233412176199421993.
Project explore tab loads projects only for allo-v2. 
Hence it makes sense for this tab to be removed

disable explore project on v1

---

packages/data-layer/src/data-layer.ts

Using this one as an example:
https://explorer.gitcoin.co/#/contributors/0xd034Fd34eaEe5eC2c413C51936109E12873f4DA5
Fixes: Donations loading an empty screen
Adds a check for any applications that are `null`.
This PR:

fix: donations/when application is null

---

packages/builder/src/actions/roundApplication.ts
packages/builder/src/utils/RoundApplicationBuilder.ts
packages/common/src/allo/backends/allo-v2.ts
packages/common/src/index.ts
packages/round-manager/src/app/wagmi.ts
packages/round-manager/src/features/common/AddQuestionModal.tsx
packages/round-manager/src/features/common/BaseSwitch.tsx
packages/round-manager/src/features/round/RoundApplicationForm.tsx

This PR adds a util function where we can specify where LIT is not supported. If you attempt to create a round on unsupported LIT chain, then encryption options is disabled and email is defaulted to non-encrypted
**Round:**
http://localhost:3000/#/round/132
**Builder**
http://localhost:3001/#/chains/11155111/rounds/132/apply
http://localhost:3001/#/chains/11155111/registry/0x/projects/0x663a65b17790c882b4606a423641381db8cbb692f35869344bc35b172c36f364
**View Email Without Encrypted Data**
http://localhost:3000/#/round/132/application/0?debug=true

rm: lit is optional

---

packages/grant-explorer/src/features/collections/community/index.ts

last one for gg20. need to do this within 3 days for communit policy laid out in https://gov.gitcoin.co/t/gg20-featured-collections-policy/18718/2

update community collections list

---

packages/grant-explorer/src/features/discovery/LandingTabs.tsx
packages/grant-explorer/src/index.tsx

Remove projects tab outside of GG rounds
This PR:

Remove projects tab outside of GG rounds

---

packages/grant-explorer/src/features/api/utils.ts
packages/round-manager/src/features/api/payoutTokens.ts

Removes the zk Sepolia TEST token to prevent it from being used.
This PR:

 Remove zk sepolia test token

---

packages/data-layer/src/data.types.ts
packages/grant-explorer/src/features/api/rounds.ts
packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
packages/grant-explorer/src/features/discovery/utils/__tests__/createRoundsStatusFilter.test.tsx
packages/grant-explorer/src/features/discovery/utils/createRoundsStatusFilter.ts

Note this can be tested only on V1 to make sure Uniswap DG round is displayed
https://discord.com/channels/562828676480237578/1239738214474842163/1239850037178273842
- Ensure DG grants shows up on the explorer
- Adds a new filter to ensure private rounds are displayed on the explorer

fix: explorer not showing DG

---

packages/round-manager/src/features/round/ViewRoundSettings.tsx

Currently, in production when you edit a round -> we try to find the decimals of the token and default it to 18 if it is undefined. It was being set to undefined and we were comparing checksum token address with lower token address which would always return fail  (eg:  aa == AA)
When creating a round with USDC which has 6 decimals  -> the compare would fail and it would default to 18 decimals
Fix Tested on round http://localhost:3000/#/round/0x6f008d6701daf4ab585202e95c273d4225a0bf15
This was a round created with 1 USDC as match amount and then updated to 10 USDC
fixes https://github.com/gitcoinco/grants-stack/issues/3421

fix: ensure token address is lowercased

---

packages/round-manager/src/features/round/ViewFundGrantees.tsx
packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx

Revert this once https://github.com/gitcoinco/grants-stack/pull/3440 is merged

disabled payout

---

packages/common/package.json
packages/common/src/allo/backends/allo-v2.ts
packages/common/src/types.ts
packages/round-manager/src/features/api/payoutStrategy/payoutStrategy.ts
packages/round-manager/src/features/api/types.ts
packages/round-manager/src/features/api/utils.ts
packages/round-manager/src/features/round/ViewFundGrantees.tsx
packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx
pnpm-lock.yaml

Fixes: #issue
fix: payout issue in v2
This PR:

fix: payout issue in v2

---

packages/round-manager/src/features/api/round.ts
packages/round-manager/src/features/api/types.ts
packages/round-manager/src/features/round/ViewManageTeam.tsx
packages/round-manager/src/features/round/ViewRoundPage.tsx
packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx

Fixes: #2727 
Fixes: #2733 
1. Add a "Manage Team" section to Round Details page on Manager
2. View team members as an operator
This PR:

add a Manage Team section to Round Details page

---

packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
packages/round-manager/src/features/round/RoundApplicationForm.tsx
packages/round-manager/src/features/round/__tests__/ApplicationDirectPayout.test.tsx
packages/round-manager/src/features/round/usePayouts.tsx

Changes on Direct Grants:
This PR allows to remove the payout token from the Direct Grants Round creation form,
also it resolves the bug of setting a wrong/not existing token.
As a replacement for the pre-defined token a token list dropdown was added to the payout form.
The dropdown allows to chose a token form our payout token list and to payout with a custom token.
To Test:
- creating a direct grants round (without payout token)
- payout a grantee with a token from the dropdown
- payout a grantee with a custom token (i can send you some test token)
Screenshots:
Note: RND is a Random token i used for testing which is not in the payout token list
Custom token allows to paste in an address and loads the needed token information like symbol and decimals
a wrong token address shows an error

DG: Add payout token list

---

packages/builder/.env.example

Fixes: bug "REACT_APP_CHAINS_OVERRIDE=all" is not valid, and commenting out this line will actually have the desired effect. Also, make allo-v2 the default.
Improve default/example env values to more closely reflect "ideal" default values.
This PR:

improve builder default envs

---

packages/common/src/chains.ts

Set the public rpc for sepolia so that we don't require infura/alchemy accounts for local development

set public sepolia rpc

---

packages/common/src/allo/backends/allo-v2.ts
packages/round-manager/src/features/api/round.ts

Removing the Round operator filter.
If we encounter the spam rounds again, we need to think about a different way to handle them (maybe black listing)
See: https://discord.com/channels/562828676480237578/1234146304108531852

removing round operator filter

---

packages/round-manager/src/features/round/ViewFundGrantees.tsx

fix allProjects to be an array instead of an object

---

packages/common/src/chains.ts

use alchemy and infura provider

---

packages/grant-explorer/src/features/round/ViewRoundPage.tsx

Fixes: #issue
In ViewRoundPage:
ProjectCards were not displaying the description if the ProjectCard footer was being displayed. 
This PR:

fix(explorer): description missing on project card with footer

---

packages/grant-explorer/src/features/api/utils.ts
packages/grant-explorer/src/features/common/styles.tsx
packages/grant-explorer/src/features/round/ApplicationsCountdownBanner.tsx
packages/grant-explorer/src/features/round/RoundStartCountdownBadge.tsx
packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
packages/grant-explorer/src/features/round/ViewRoundPage.tsx
packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
packages/grant-explorer/tailwind.config.js

Fixes: #issue
We remove the old pre-round page, and reuse the after round start page:
- src/features/api/utils.ts:
-  implemented getTimeLeft function reusing the logic of getDaysLeft, to return an object { days, hours, minutes, seconds } with the time left values based on a timestamp passed as argument
- getDaysLeft now uses getTimeLeft
- implemented parseTimeLeftString that receives as argument the same structure that getTimeLeft returns, and converts is to string with the format `X days, X hours, X minures`
- src/features/common/styles.tsx & tailwind.config.js:
- extended TW theme with a rainbow gradiend background to use it in a badge 
- src/features/round/ViewProjectDetails.tsx:
- cart button now is hidden in pre-round period
- src/features/round/ApplicationsCountdownBanner.tsx & …

feat(explorer): show project list in preround page

---

packages/grant-explorer/src/features/common/Auth.tsx
packages/round-manager/src/features/common/Auth.tsx
packages/round-manager/src/features/program/__tests__/CreateProgramPage.test.tsx
packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx
packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
packages/round-manager/src/features/round/FundContract.tsx
packages/round-manager/src/features/round/RoundApplicationForm.tsx
packages/round-manager/src/features/round/__tests__/ApplicationDirectPayout.test.tsx
packages/round-manager/src/features/round/__tests__/CreateRoundPage.test.tsx
packages/round-manager/src/features/round/__tests__/QuadraticFundingForm.test.tsx
packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx
packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx

Fixes: https://github.com/gitcoinco/grants-stack/issues/3530
https://discord.com/channels/562828676480237578/1253821571781365821/1253823804635877470

fix: use right signer

---

packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx

Keep the finalize round button always enabled instead of checking if the pool is completely funded. 
This is needed in case the round operator wants to distribute less funds only to some grantees.

keep the finalize round button always enabled

---

packages/grant-explorer/src/features/common/Navbar.tsx
packages/grant-explorer/src/features/discovery/LandingPage.tsx
packages/grant-explorer/src/features/round/ViewCartPage/Header.tsx
packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx

Disables the Featured rounds drop down from the navbar. We can enable it again during our GG21 round.
Removes collections. They are currently serving no purpose. The team is working on how the future of collections look.
Remove share button on `ViewCartPage`

update navbar/disable featured ddl

---

packages/builder/src/components/grants/Show.tsx

This PR adds a `View Public Profile` button in builder to quickly find the profiles page on explorer

Add Public Profile Button

---

packages/builder/src/components/rounds/Show.tsx

Fixes: #3561 
logic seemed to be reversed on setting round times based on the round being direct grant or not. flipped it, and now non-direct grants rounds are showing correct round times.
This PR:

fix builder round dates

---

packages/builder/src/components/grants/stats/StatCard.tsx
packages/builder/src/components/grants/stats/Stats.tsx
packages/builder/src/utils/wagmi.ts
packages/common/src/allo/backends/allo-v2.ts
packages/data-layer/src/data-layer.ts
packages/data-layer/src/data.types.ts
packages/data-layer/src/queries.ts

fixes BLU-115
see stats of https://builder-staging-git-builder-direct-donations-grants-stack.vercel.app/#/chains/11155111/registry/0x/projects/0x0ad4d07d45ef3c6807b71f09342201baee881e13b67906d7067df59588dd4879

Show direct donations on builder

---

packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx

in the indexer in the file migrate.ts, the search_projects function is using to_tsquery that does not accept espaces, a solution is to wrap the phrase in single quotes.

fix(PAR-208): search projects by multiple words

---

packages/common/src/allo/allo.ts
packages/common/src/allo/backends/allo-v1.ts
packages/common/src/allo/backends/allo-v2.ts
packages/round-manager/src/context/program/UpdateRolesContext.tsx
packages/round-manager/src/features/common/useApplicationsByRoundId.tsx
packages/round-manager/src/features/program/TabGroup.tsx
packages/round-manager/src/features/program/ViewManageProgram.tsx
packages/round-manager/src/features/program/ViewProgramPage.tsx
packages/round-manager/src/features/round/ViewApplicationPage.tsx
packages/round-manager/src/index.tsx

chore: add manageProfileMembers

---

packages/grant-explorer/src/features/projects/ViewProject.tsx

Fixes: PAR-217
Fixes wrong project added to cart bug & updates sidebar ui in project page to be more descriptive.
This PR:

fix: wrong project added to cart bug

---

packages/common/src/allo/backends/allo-v2.ts

Fixes: PAR-249
fix donating with erc20 issue during direct donations
This PR:

fix: donating with erc20 issue during direct donations

---

packages/common/package.json
packages/common/src/allo/backends/allo-v2.ts
packages/common/src/index.ts
packages/grant-explorer/src/features/projects/ViewProject.tsx
packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
pnpm-lock.yaml

Fixes: #issue
fetch direct donation contracts from chain data package
This PR:

feat: fetch direct donation contracts from chain data package

---

packages/grant-explorer/src/features/api/oso.ts
packages/grant-explorer/src/features/round/OSO/ImpactStats.tsx

Fixes: #3458 
updates explorer project page's codebase impact stats to use OSO's latest models (was broken previously)
This PR:

Fix OpenSource Observer queries

---

packages/builder/src/components/base/images/ImageCrop.tsx

Fixes: #3291 
Fixes the bug where only a portion of an image can be selected for a project's logo. See image below.
This PR:

[FIX] Bug 3291 - Can now select full area for project logo

---

packages/round-manager/src/features/round/FundContract.tsx

Remove fund restriction

---

packages/grant-explorer/src/features/api/oso.ts
packages/grant-explorer/src/features/round/OSO/ImpactStats.tsx

Fixes: https://github.com/gitcoinco/grants-stack/issues/3669
https://linear.app/gitcoin/issue/PAR-438/update-oso-endpoint-and-queries
With current OSO models it is not straightforward to retrieve code velocity data. Updated that field to instead reflect OSO's `activeDeveloperCount6Months` field for a sense of active developers.
This PR:

update OSO endpoint and queries

---

packages/data-layer/src/data-layer.ts
packages/data-layer/src/index.ts
packages/data-layer/src/services/AttestationService/AttestationService.ts
packages/data-layer/src/services/AttestationService/index.ts
packages/data-layer/src/services/AttestationService/types.ts
packages/data-layer/src/services/__tests__/AttestationService.test.ts
packages/data-layer/src/services/__tests__/mocks.ts
packages/grant-explorer/src/features/attestations/MintYourImpactComponents.tsx
packages/grant-explorer/src/features/common/components/ImageWithLoading.tsx
packages/grant-explorer/src/features/common/components/Modal.tsx
packages/grant-explorer/src/features/contributors/components/Buttons/MintDonationButton.tsx
packages/grant-explorer/src/features/contributors/components/Buttons/MintDonationImpactAction.tsx
packages/grant-explorer/src/features/contributors/components/Buttons/MintingActionButton.tsx
packages/grant-explorer/src/features/contributors/components/ContributionHistoryContainer.tsx
packages/grant-explorer/src/features/contributors/components/RoundDonations/DonationsTransactions.tsx
packages/grant-explorer/src/features/contributors/components/RoundDonations/RoundDonations.tsx
packages/grant-explorer/src/features/contributors/components/RoundDonations/TransactionHeader.tsx
packages/grant-explorer/src/features/contributors/hooks/useContributionsByDonor.tsx
packages/grant-explorer/src/features/contributors/hooks/useMintingAttestations.tsx
packages/grant-explorer/src/hooks/attestations/useGetAttestationData.ts

chore: check transaction minting in history page

---

packages/grant-explorer/src/attestationStore.ts
packages/grant-explorer/src/checkoutStore.ts
packages/grant-explorer/src/context/RoundContext.tsx
packages/grant-explorer/src/features/api/types.ts
packages/grant-explorer/src/features/attestations/MintYourImpactComponents.tsx
packages/grant-explorer/src/features/attestations/utils/getRoundsToFetchNames.ts
packages/grant-explorer/src/features/contributors/utils/getContributionFrameProps.ts
packages/grant-explorer/src/features/round/ThankYou.tsx

- Separates checkout store with attestation store
- Fixes Thank you page 
- Renders the actual attestation impact image
- uses the attestation-store which uses persit
- After the attestation mint it removes attestation store state

Gg22 thank you page improvs

---

packages/grant-explorer/src/features/attestations/MintYourImpactComponents.tsx
packages/grant-explorer/src/features/contributors/components/Buttons/MintDonationImpactAction.tsx
packages/grant-explorer/src/features/round/ThankYou.tsx
packages/grant-explorer/src/index.css

improved attestation frame made it more dynamic-minimal

---

packages/grant-explorer/src/features/contributors/components/RoundDonations/TransactionHeader.tsx
packages/grant-explorer/src/features/round/ThankYou.tsx

- hide attest behind debug flag.
- this should be reverted for releasing attestation feature to public

hide attestation

---

packages/grant-explorer/src/features/attestations/components/ActionButton.tsx
packages/grant-explorer/src/features/common/GenericModal.tsx
packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx

- Adds the Squid widget to the BridgeFunds button when the user doesn't have enough funds to mint their attestation.
fixes PAR-556

adds the squid widget in the mint attestation workflow

---

packages/grant-explorer/src/features/discovery/LandingPage.tsx

chore: removing community collections

---

packages/common/package.json
packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx
pnpm-lock.yaml

fixes PAR-566
We have made the following updates:
1. **Checkout**: 
- If price fetching fails for any reason, users will still be able to proceed with the checkout process.
_2. **CUSD Token Update**:
- The Redstone token ID for CUSD has been updated in the **chain data package**.
3. **USDGLO Replacement**:
- Since USDGLO is not available on Redstone and accurate pricing is not critical in this context, we have replaced the Redstone token ID for USDGLO with CUSD. This ensures a similar approximation in price._
**Action Item**:
- Discuss the handling of tokens that are not available on Redstone. Begin by identifying where Redstone is currently used and then determine the importance of accurate prices for these services.

fix price fetching bug

---

packages/builder/babel.config.js
packages/builder/craco.config.js
packages/builder/package.json
packages/builder/src/__tests__/components/grants/Show.test.tsx
packages/builder/src/components/grants/rounds/__tests__/Rounds.test.tsx
pnpm-lock.yaml

Fix builder test

---

packages/grant-explorer/src/features/round/ViewRoundPage.tsx

Fixes: #3607 
This PR addresses the Cosmetic UI issue to ensure all figures displayed contain 2 decimal places for consistency on the frontend. 
This PR:

fix: apply consistent 2 decimal places in UI.

---

packages/grant-explorer/src/attestationStore.ts
packages/grant-explorer/src/checkoutStore.ts
packages/grant-explorer/src/features/round/ThankYou.tsx

fixes attestation store

---

packages/grant-explorer/src/features/api/gap.ts
packages/grant-explorer/src/features/round/KarmaGrant/CompletionBadge.tsx
packages/grant-explorer/src/features/round/KarmaGrant/GrantItem.tsx

Fixes: Check if grant was completed before checking for milestone completion
Fixes on the [Karma-GAP](https://gap.karmahq.xyz/) grant integration
- Added completed type to a grant object
- Check if grant was completed along with checking for milestone completion in the grant completion badge
This PR:

[KARMA-GAP] Small fixes on the grants completion badge

---

packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx

Fixes: #3604 
Render checkout message to different network only when more than one contribution is made for different networks.
This PR:

fix:reduntant message if only one network

---

packages/grant-explorer/src/features/collections/CollectionCard.tsx
packages/grant-explorer/src/features/collections/CollectionDetails.tsx
packages/grant-explorer/src/features/discovery/CardBanner.tsx

fixes PAR-605
Add Description to Collection Details
figma: https://www.figma.com/design/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?node-id=692-46254&node-type=frame&m=dev
fix collection card sizes:
figma: https://www.figma.com/design/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?node-id=628-25647&node-type=frame&t=Z54cVQbLt8qyaifq-0

fix collection size

---

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx

Fixes: #3717 
The previous implementation was stuck in a loading state when a grant was unapproved leading to confusion. Now, it will properly display a message to the user if the grant is in an unapproved state.
This PR:

[Bugfix]  Better handling of unapproved grants in Grants Explorer

---

docs/TOKENS.md
packages/round-manager/README.md

Pull Request: Grammar and Style Improvements
Changes:
1. File: packages/round-manager/README.md
- Old: "w.r.t to" -> New: "w.r.t"
Reason: Removed redundant "to" as "w.r.t" already means "with respect to"
2. File: packages/round-manager/README.md  
- Old: "decentralized stored" -> New: "decentrally stored"
Reason: Corrected grammatical form from adjective to adverb for proper modification of verb
These changes improve documentation clarity and maintain professional standards without altering meaning.

Grammar and Style Improvements

---

packages/common/src/allo/backends/allo-v2.ts

update checker api call to not await

---

packages/data-layer/src/data-layer.ts
packages/data-layer/src/queries.ts
packages/grant-explorer/src/features/api/rounds.ts
packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
packages/grant-explorer/src/features/discovery/RoundCard.tsx
packages/grant-explorer/src/features/discovery/RoundProjects.tsx
packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts

…tions
Fixes: https://linear.app/gitcoin/issue/PAR-863/[explorer]-improve-round-engagement-reporting
This PR:

Showing Pending Applications on Round Card

---

packages/data-layer/src/data-layer.ts
packages/data-layer/src/queries.ts
packages/grant-explorer/src/features/api/rounds.ts
packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts

showing application count on home screen

---

packages/builder/src/components/base/InputLabel.tsx

Fixes: https://linear.app/gitcoin/issue/PAR-905/hidden-application-answers-still-public
This PR:

Acknowledge "Hidden" application fields are still public

---

packages/builder/src/components/providers/identity/__tests__/credentials.test.ts
packages/builder/src/components/providers/identity/credentials.ts

fix: twitter verification

---

.env.example
packages/common/src/index.ts
packages/grant-explorer/README.md

Fixes: [issue](https://linear.app/gitcoin/issue/PAR-911/passport-score-cors-error)
This PR:

Passport scorer API update

---

packages/data-layer/src/data-layer.ts
packages/data-layer/src/data.types.ts
packages/data-layer/src/queries.ts
packages/grant-explorer/src/features/collections/CollectionCard.tsx
packages/grant-explorer/src/features/discovery/RoundCard.tsx
packages/grant-explorer/src/features/projects/__tests__/ViewProject.test.tsx
packages/grant-explorer/src/features/round/ViewRoundPage/ProjectCard.tsx
packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx

- getApprovedApplication
- getApplicationsForExplorer
- getDonationsByDonorAddress

fix: canonical metadata
