packages/round-manager/src/actions/web3.ts, packages/round-manager/src/app/hooks.ts, packages/round-manager/src/app/store.ts, packages/round-manager/src/components/dashboard/Dashboard.tsx, packages/round-manager/src/index.tsx
- Rely on the redux dispatcher and 
- Move thunks and state to it's own file 
Locally Tested
=> chore: isolate hooks/, store/ logic

.gitignore, packages/round-manager/package.json, packages/round-manager/postcss.config.js, packages/round-manager/src/components/dashboard/Dashboard.tsx, packages/round-manager/src/index.css, packages/round-manager/tailwind.config.js, packages/round-manager/yarn.lock
this pr integrates [tailwindcss](https://tailwindcss.com/)
closes https://github.com/gitcoinco/grants-round/issues/10
=> integrate tailwind

.gitignore, packages/contracts/.vscode/launch.json, packages/contracts/docs/Dev.md
Adds in debugger script via vscode for hardhat commands
source: https://code.visualstudio.com/docs/editor/debugging
fixes https://github.com/gitcoinco/grants-round/issues/22
Locally Tested
=> chore: add debug scripts for .vscode

packages/contracts/.gitignore, packages/contracts/contracts/dummy/README.md, packages/contracts/contracts/dummy/upgradeCheck/README.md, packages/contracts/contracts/dummy/upgradeCheck/dummyProgramFactory.sol, packages/contracts/contracts/dummy/upgradeCheck/dummyProgramImplementation.sol, packages/contracts/contracts/program/ProgramFactory.sol, packages/contracts/contracts/program/ProgramImplementation.sol, packages/contracts/hardhat.config.ts, packages/contracts/package.json, packages/contracts/scripts/program/deployProgramFactory.ts, packages/contracts/scripts/program/deployProgramImplementation.ts, packages/contracts/scripts/program/upgradeProgramFactory.ts, packages/contracts/scripts/round/deployGrantRoundFactory.ts, packages/contracts/scripts/round/deployGrantRoundImplementation.ts, packages/contracts/scripts/votingMechanism/deployBulkVotingMechanism.ts, packages/contracts/yarn.lock
- uses proxy pattern on Program to make an upgradeable contract
- introduces dummy upgradable contract with documentation on how to go about this 
This PR shows how we can rely on Proxy for program factory.
Once we focus on test coverage -> we can consider implementing the proxy pattern for Grant Factory as well 
Further details on what the proxy does can be found in the readme file.
For now **this does not change the behaviour on how program are created / deployed**
=> feat: switch Program Factory to use proxy 

packages/contracts/.vscode/launch.json, packages/contracts/contracts/dummy/upgradeCheck/README.md, packages/contracts/docs/DEPLOY_STEPS.md, packages/contracts/package.json, packages/contracts/scripts/program/linkProgramImplementation.ts, packages/contracts/scripts/round/linkGrantRoundImplementation.ts
renaming script to make it more meaningful
=> chore: rename update -> link

packages/round-manager/src/features/api/contracts.ts, packages/round-manager/src/features/api/index.ts, packages/round-manager/src/features/api/services/program.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/ProtectedRoute.tsx, packages/round-manager/src/features/common/styles.ts, packages/round-manager/src/features/program/CreateProgram.tsx, packages/round-manager/src/features/program/ListPrograms.tsx, packages/round-manager/src/features/program/ViewProgram.tsx, packages/round-manager/src/history.ts
This PR introduces the following
- fetch all on-chain and off-chain data for the programs in which the connected account is an operator
- view detail pages of programs
closes #6 
* list programs
* view program
=> feat(program): view and list pages

packages/round-manager/craco.config.js, packages/round-manager/package.json, packages/round-manager/src/features/api/services/program.ts, packages/round-manager/src/features/api/services/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/round/ReviewApplicationsPage.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/index.tsx
This PR introduces
* View grant rounds on the detail page of a program
* Round detail page
* Skeleton round applications review page
close #7 
* List rounds
* Round detail page
* Skeletal round applications review page
=> feat: view and list grant rounds

packages/round-manager/src/index.css, packages/round-manager/tailwind.config.js
This PR implements the color palette from gitcoin design system
closes #70
=> chore: implement gitcoin color palette

packages/contracts/contracts/RoundFactory.sol, packages/contracts/contracts/RoundImplementation.sol, packages/contracts/docs/ROUND_APPLICATION.md, packages/contracts/scripts/round/createRound.ts
- add public MetaPtr variable
- update documentation on Review System
- update script to include new added field
- define unique event on each time / metaPtr updated
- add new public storage variable projectsMetaPtr
- add updateProjectsMetaPtr to allow update projectsMetaPtr by
round operator
https://github.com/gitcoinco/grants-round/issues/66
Tested on etherscan.
Unit test will come up in a follow up PR
=> chore: enable storing applicationMetaPtr

packages/round-manager/src/features/common/FormWizard.tsx, packages/round-manager/src/features/common/ProtectedRoute.tsx, packages/round-manager/src/features/common/styles.ts, packages/round-manager/src/features/program/ListProgramPage.tsx
This PR introduces a form wizard component that can be use thus
```
const Component1 = () => <p>Component 1</p>
const Component2 = () => <p>Component 2</p>
const Component3 = () => <p>Component 3</p>
<FormWizard steps={[Component1, Component2, Component3]} />
```
closes #74 
tested locally
=> feat: form wizard component

packages/round-manager/package.json, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/FormStepper.tsx, packages/round-manager/src/features/common/FormWizard.tsx, packages/round-manager/src/features/common/styles.ts, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/round/CreateRoundPage.tsx, packages/round-manager/src/features/round/RoundApplicationsConfigForm.tsx, packages/round-manager/src/features/round/RoundDetailsForm.tsx, packages/round-manager/src/index.css, packages/round-manager/tailwind.config.js, packages/round-manager/yarn.lock
This PR introduces the following:
* UI styling for round creation page
* Form wizard
* Round details step
closes #61
=> feat(mvp): round creation 1

packages/contracts/.vscode/launch.json, packages/contracts/docs/CHAINS.md, packages/contracts/package.json, packages/contracts/scripts/config/round.config.ts, packages/contracts/scripts/round/createRound.ts, packages/contracts/scripts/round/updateProjectMetaPtr.ts
- adds helper script to update project metaPtr
Locally Tested.
=> chore: add script to update project metaPtr

packages/contracts/.vscode/launch.json, packages/contracts/contracts/RoundImplementation.sol, packages/contracts/docs/CHAINS.md, packages/contracts/docs/ROUND_APPLICATION.md, packages/contracts/package.json, packages/contracts/scripts/config/round.config.ts, packages/contracts/scripts/round/applyToRound.ts, packages/contracts/scripts/round/updateProjectMetaPtr.ts, packages/graph/abis/RoundFactory.json, packages/graph/abis/RoundImplementation.json, packages/graph/docs/Round.md, packages/graph/schema.graphql, packages/graph/src/round/implementation.ts, packages/graph/src/utils.ts, packages/graph/subgraph.yaml
- add applyToRound function
- add NewProjectApplication event
- add script to applyToRound
- update package.json to add new script command
- update chain.md with new contract
- feat: indexing NewProjectApplication Event
Tested on testnet + updated in CHAINS.md
=> feat: review system contract changes

packages/contracts/docs/CHAINS.md, packages/contracts/scripts/config/round.config.ts, packages/graph/docs/Round.md, packages/round-manager/src/features/api/contracts.ts
General cleanup + updating documentation + redeploying subgraph
=> chore: deploy subgraph

README.md, packages/contracts/README.md, packages/contracts/docs/DEPLOY_STEPS.md, packages/contracts/docs/Dev.md, packages/contracts/docs/MetaPtrProtocol.md, packages/contracts/docs/ROUND_APPLICATION.md, packages/graph/README.md, packages/graph/docs/Program.md, packages/graph/docs/Round.md, packages/graph/networks.json, packages/round-explorer/README.md, packages/round-explorer/docs/Dev.md, packages/round-manager/README.md, packages/round-manager/docs/Dev.md
- Update documentation for gitbook integration
- Moves directory structure to root of every package
- Add README for thegraph
- Update core readme which links to packages 
- remove networks.json (redundant file)
https://app.gitbook.com/o/Aqbtj6s4OkLaygileCka/s/6WA8Y0HFz1HDvz5JgLH8/
=> chore: update READ.md

packages/contracts/hardhat.config.ts, packages/contracts/yarn.lock
- tweak hardhat config to use new format to export abi in fullName format
- PR was raised https://github.com/ItsNickBarry/hardhat-abi-exporter/pulls?q=is%3Apr+is%3Aclosed
closes #128 
Locally
=> chore: upgrade hardhat-abi-exporter

packages/contracts/contracts/program/ProgramFactory.sol, packages/contracts/contracts/program/ProgramImplementation.sol, packages/contracts/docs/CHAINS.md, packages/contracts/scripts/config/program.config.ts, packages/contracts/scripts/program/createProgram.ts, packages/contracts/scripts/round/createRound.ts, packages/graph/docs/Program.md, packages/graph/docs/Round.md, packages/graph/subgraph.yaml, packages/round-manager/src/features/api/contracts.ts
- [task: update ProgramImplementation to use encodedParameters](https://github.com/gitcoinco/grants-round/commit/520ce92b2c257c27d462f132865f39c8f48ca1a9)
- [chore: update adminRoles to array in ProgramImplementation](https://github.com/gitcoinco/grants-round/commit/2af7301fcc600de0961519f564eca53559dfd4ae) 
- update contract + deploy scripts
- update README.md
- minor improvement to program creation script
closes #123 
closes #122 
Created Program with https://goerli.etherscan.io/address/0xA758560ED04c45FE77D1bE3aFC1f8B0eb4Cc597c#readContract
=> feat: program contract updates 

packages/contracts/contracts/round/RoundFactory.sol, packages/contracts/contracts/round/RoundImplementation.sol, packages/contracts/docs/CHAINS.md, packages/contracts/scripts/config/round.config.ts, packages/contracts/scripts/program/createProgram.ts, packages/contracts/scripts/round/createRound.ts, packages/contracts/scripts/utils.ts, packages/contracts/test/round/RoundFactory.test.ts, packages/contracts/test/round/RoundImplementation.test.ts, packages/graph/docs/Round.md, packages/round-manager/src/features/api/contracts.ts
Should be merged after #137 
- [update RoundImplementation to use encodedParameters](https://github.com/gitcoinco/grants-round/commit/4481217bdd66ba08d0f69a80167b338663642eae)
- [chore: update adminRoles to array in RoundImplementation](https://github.com/gitcoinco/grants-round/commit/46e213feb0937f432e59147abe738c5a270b11ad) 
- update contract + deploy scripts
- update README.md
- add tests
closes #121 
closes #124 
Tested on-chain in test network
=> task: contract changes to Round contracts

packages/round-manager/.env.sample, packages/round-manager/.gitignore, packages/round-manager/package.json, packages/round-manager/src/__tests__/Dashboard.test.tsx, packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/services/ipfs.ts, packages/round-manager/src/features/api/services/program.ts, packages/round-manager/src/features/api/services/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/global.ts, packages/round-manager/yarn.lock
This PR integrates pinata.cloud for pinning and fetch from ipfs network
#133
=> ipfs pinning service

packages/contracts/contracts/dummy/README.md, packages/contracts/contracts/dummy/upgradeCheck/dummyProgramFactory.sol, packages/contracts/contracts/dummy/upgradeCheck/dummyProgramImplementation.sol, packages/contracts/contracts/dummy/upgradeCheck/dummyRoundFactory.sol, packages/contracts/contracts/dummy/upgradeCheck/dummyRoundImplementation.sol, packages/contracts/contracts/program/ProgramFactory.sol, packages/contracts/package.json, packages/contracts/scripts/program/createProgram.ts, packages/contracts/scripts/program/upgradeProgramFactory.ts, packages/contracts/scripts/round/deployRoundFactory.ts, packages/contracts/scripts/round/upgradeRoundFactory.ts, packages/contracts/scripts/utils.ts, packages/contracts/test/program/ProgramFactory.test.ts, packages/contracts/test/round/RoundFactory.test.ts, packages/round-manager/src/features/api/abi/programFactory.ts, packages/round-manager/src/features/api/abi/programImplementation.ts, packages/round-manager/src/features/api/abi/roundFactory.ts, packages/round-manager/src/features/api/abi/roundImplementation.ts
- make factory contracts upgradable
- add script for upgrade
- add tests
- Deploying Upgradable RoundFactory to 0x1FB48c98d6c04995c173faEE60Aac73a0cc19948
- Deploying RoundImplementation to 0xF0638054756E9f342C2e3c9d73A6ccbFc2A83442
- ✅ RoundImplementation Contract linked to Round Contract 0xa73ccce60ae5e24ed24b56bc967cb838affeb385dbbdd81df9e7ab95feb9291e
- Txn hash: 0x9a8d34d7e13a010d58cb26db172ca202991f9e23f78b1fc2668cda812675bf23
✅ Round created:  0x92972ef8E4c7E2700bf1EBFbb7418431CA92DDd9
**Upgrading**  
- RoundFactory is now upgraded. Check 0x1FB48c98d6c04995c173faEE60Aac73a0cc19948
- Deploying Dummy RoundImplementation to 0x6b0b7703160f437711A99a8c211DD93677c3c038
- ✅ RoundImplementation Contract linked to Round Contract 0x24ea48f423efbcf168e1be560d87227442d6aa85cd93ca576f80eb6679149 …
=> feat: factory contracts upgradable 

packages/round-manager/src/features/api/services/program.ts, packages/round-manager/src/features/api/services/round.ts
This PR updates the round and program services to interact with the latest versions of the respective contracts which require initialization parameters to be encoded
#142
=> feat(manager): round/program services to use encoded parameters

packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/RoundApplicationForm.tsx
- chore: update form to MVP round
#143
=> chore: update form to MVP round

packages/graph/abis/ProgramFactory.json, packages/graph/abis/ProgramImplementation.json, packages/graph/abis/RoundFactory.json, packages/graph/abis/RoundImplementation.json, packages/graph/subgraph.yaml
- update graph deploy to latest contract
```
Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
Skip migration: Bump mapping apiVersion from 0.0.4 to 0.0.5
Skip migration: Bump mapping apiVersion from 0.0.5 to 0.0.6
Skip migration: Bump manifest specVersion from 0.0.1 to 0.0.2
Skip migration: Bump manifest specVersion from 0.0.2 to 0.0.4
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
Load contract ABI from abis/ProgramFactory.json
Load contract ABI from abis/RoundFactory.json
✔ Load contract ABIs
Generate types for contract ABI: ProgramFactory (abis/ProgramFactory.json)
Write types to generated/Program/ProgramFactory.ts
Generate types for contract ABI: …
```
=> chore: update graph deploy

packages/round-manager/src/features/program/ViewProgramPage.tsx
This PR includes the list of rounds for a given program in the program's detail page
closes #131
=> feat: include round list in program detail page

packages/contracts/docs/ROUND_APPLICATION.md, packages/round-manager/src/features/api/utils.ts
=> feat: add question id to the application schema

packages/round-manager/src/features/round/RoundApplicationForm.tsx
=> chore: remove roadmap & challenges from app form

packages/graph/schema.graphql, packages/graph/src/program/factory.ts, packages/graph/src/round/factory.ts, packages/graph/src/utils.ts, packages/graph/subgraph.yaml
Index public storage variables upon contract creation in Round and Program
Refers #164 
Can be tested by running documented queries on 
https://thegraph.com/hosted-service/subgraph/thelostone-mc/program-factory-v0?selected=playground
=> feat: index program contract public variables

packages/round-manager/.env.sample, packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/services/program.ts, packages/round-manager/src/features/api/utils.ts
This PR uses the subgraph instead of contract interactions to get the list of programs for a given account
closes #149
=> feat: use subgraph in program list service

packages/round-manager/src/features/api/index.ts, packages/round-manager/src/features/api/services/grantApplication.ts, packages/round-manager/src/features/api/services/program.ts, packages/round-manager/src/features/api/services/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/ApplicationsReceived.tsx
- Write grant application API service
- Display pending applications in round detail page
closes #113
=> View received grant applications

packages/contracts/contracts/round/RoundImplementation.sol, packages/contracts/test/round/RoundImplementation.test.ts
* Updates the function signature and related tests.
Fixes #179 
* Addressed
=> feat: update applyToRound function signature

packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx
This simply enhances the changes based on https://github.com/gitcoinco/grants-round/issues/113
to ensure subgraphs are used in approved and rejected pages as well
Refs: https://github.com/gitcoinco/grants-round/issues/113
=> chore: wire in graph query for applications approved / rejected

packages/contracts/contracts/program/ProgramImplementation.sol, packages/contracts/test/program/ProgramImplementation.test.ts, packages/contracts/test/round/RoundImplementation.test.ts, packages/graph/abis/ProgramImplementation.json, packages/round-manager/src/features/api/abi/programImplementation.ts
**NOTE: This would require re-deploying factory contracts and should go along with https://github.com/gitcoinco/grants-round/discussions/171**
- rename MetadataUpdated -> MetaPtrUpdated event
- add tests for ProgramImplementation
- update abi in graph, round-manager packages
closes #96
=> chore: add coverage for ProgramImplementation

packages/contracts/scripts/config/round.config.ts, packages/contracts/scripts/round/applyToRound.ts
This PR updates the applyToRound function with the latest structure for grant applications
https://ipfs.fleek.co/ipfs/bafybeiceggy6uzfxsn3z6b2rraptp3g2kx2nrwailkjnx522yah43g5tyu
https://ipfs.fleek.co/ipfs/bafybeih2pise44gkkzj7fdws3knwotppnh4x2gifnbxjtttuv7okw4mjzu
https://ipfs.fleek.co/ipfs/bafybeiekytxwrrfzxvuq3ge5glfzlhkuxjgvx2qb4swodhqd3c3mtc5jay
=> chore: update applyToRound applications

.github/workflows/contract.yml, package.json, packages/contracts/slither.config.json
This PR adds the slither static analyzer as part of our CI/CD pipeline.
Fixes #180 
Does not apply here.
Find the initial report here: https://github.com/gitcoinco/grants-round/discussions/203
=> feat: Add slither to GitHub CI workflow

CODEOWNERS
Add Shavina and Luke to CODEOWNERS file
=> chore: add Shavina and Luke to CODEOWNERS file

packages/graph/src/round/implementation.ts
=> chore: save round details after update

packages/round-manager/src/features/program/CreateProgramPage.tsx
This fixes the bug in program creation form where operator wallets overwrite each other
closes #176
=> fix: dynamic operator wallets in create program form

packages/round-manager/src/features/api/contracts.ts
Use the Round Factory abi instead of Program Factory abi when constructing the Round Factory contract
[fixes #216]
Would like help figuring out how to add a test for this :)
=> fix: use correct abi for round factory contract

packages/round-manager/src/history.ts
This PR enables page reload to work on fleek by using hash routing
closes #218 
https://vimeo.com/734517985/3a25a62ef9
=> feat: hash based routing

.github/workflows/contract.yml, packages/contracts/contracts/dummy/upgradeCheck/dummyProgramFactory.sol, packages/contracts/contracts/dummy/upgradeCheck/dummyProgramImplementation.sol, packages/contracts/contracts/dummy/upgradeCheck/dummyRoundFactory.sol, packages/contracts/contracts/dummy/upgradeCheck/dummyRoundImplementation.sol, packages/contracts/contracts/program/ProgramFactory.sol, packages/contracts/contracts/program/ProgramImplementation.sol, packages/contracts/contracts/round/RoundFactory.sol, packages/contracts/contracts/round/RoundImplementation.sol, packages/contracts/contracts/votingStrategy/BulkVotingStrategy.sol, packages/contracts/test/round/RoundFactory.test.ts
Addresses all issues detected by slither static analyzer, also some minor fixes here and there.
Fixes #211 
Does not affect program logic.
=> feat: fix all slither issues

packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/Footer.tsx, packages/round-manager/src/features/common/FormStepper.tsx, packages/round-manager/src/features/common/styles.ts, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/round/CreateRoundPage.tsx, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx
=> feat: create round page hi-fi

packages/contracts/hardhat.config.ts, packages/contracts/scripts/program/createProgram.ts, packages/contracts/scripts/program/deployProgramFactory.ts, packages/contracts/scripts/program/deployProgramImplementation.ts, packages/contracts/scripts/program/linkProgramImplementation.ts, packages/contracts/scripts/program/upgradeProgramFactory.ts, packages/contracts/scripts/round/applyToRound.ts, packages/contracts/scripts/round/createRound.ts, packages/contracts/scripts/round/deployRoundFactory.ts, packages/contracts/scripts/round/deployRoundImplementation.ts, packages/contracts/scripts/round/linkRoundImplementation.ts, packages/contracts/scripts/round/updateProjectMetaPtr.ts, packages/contracts/scripts/round/upgradeRoundFactory.ts, packages/contracts/scripts/utils.ts, packages/contracts/scripts/votingStrategy/castBulkVotingStrategy.ts, packages/contracts/scripts/votingStrategy/deployBulkVotingStrategy.ts
Suppresses warnings on tests and only asserts variable existence during script runs.
Fixes #185
=> fix: suppress warnings in tests and assert in scripts

packages/contracts/contracts/votingStrategy/BulkVotingStrategy.sol, packages/contracts/contracts/votingStrategy/IVotingStrategy.sol
Fixes the DoS vulnerability in `BulkVotingStrategy` by removing `safeTransferFrom()` in favour of `transferFrom()`
Fixes #256 
* Passes existing tests
=> fix: remove safeTransferFrom() in favour of transferFrom()

packages/round-manager/src/features/common/Footer.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx
- add footer to missing pages
- updating styling to make footer stay at bottom of the page
closes #217
=> chore: tweak footer

packages/graph/src/utils.ts
=> Use ByteArray.fromUTF8 instead of fromHexString

packages/round-manager/package.json, packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/contracts.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/program/ViewProgramPage.test.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/test-utils.tsx, packages/round-manager/yarn.lock
- style program details page
- add to Faker library to generate test data
- also fix graphql_fetch usages in test due to new signature
resolves #196
- adds `packages/round-manager/src/features/program/ViewProgramPage.test.tsx`
=> 196 Update program details page

packages/round-manager/src/features/round/ViewApplicationPage.tsx
fixes broken application logo and banner images
closes #248
=> fix: load application images with ipfs hash

packages/round-manager/src/features/common/styles.ts, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx
=> feat: update application card design

packages/graph/README.md, packages/graph/docs/Round.md
Improves documentation on the graph package
Does not have an associated ticket and this was feedback given by @nfrgosselin  to make the doc better
=> chore: improve documentation

packages/contracts/docs/ROUND_APPLICATION.md, packages/round-manager/src/features/api/utils.ts
Resolves #221 
Round contract: 
0x001b73d0c92f50e2a5385b1328d615d2addac438
Application Metadata:
https://gitcoin.mypinata.cloud/ipfs/bafkreifkt4sond4c5amadjffnoy6cebxbmflcid5trmxazf5os3zlpwi2a
=> Adds encrypted flag to round metadata, only email is set to true for now

packages/round-manager/src/features/common/FormWizard.tsx, packages/round-manager/src/features/common/__tests__/FormStepper.test.tsx, packages/round-manager/src/features/common/__tests__/FormWizard.test.tsx
Adds tests to FormWizard and FormStepper
resolves #261
Adds `packages/round-manager/src/features/common/__tests__/FormStepper.test.tsx` and `packages/round-manager/src/features/common/__tests__/FormWizard.test.tsx`
=> [#261] form wizard tests

CODEOWNERS
Add dave to be a code owner so he can review PRs.
=> Add dave as codeowner

packages/round-manager/src/features/api/services/grantApplication.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/ConfirmationModal.tsx, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/setupTests.ts
=> feat: confirm bulk approval

packages/round-manager/src/features/common/Footer.tsx, packages/round-manager/src/features/round/CreateRoundPage.tsx
Fixes navbar on create round page
https://github.com/gitcoinco/grants-round/issues/217
=> chore: fix broken nav

packages/round-manager/src/features/program/ListProgramPage.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx
Make the following elements clickable 
fixes https://github.com/gitcoinco/grants-round/issues/277
=> chore: make card clickable

packages/round-manager/src/features/round/RoundApplicationForm.tsx
Updates the design in the application configuration step of round creation
closes #274
=> feat: update application config page design

packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/RoundApplicationForm.tsx
=> fix: application schema generation

packages/round-manager/src/features/api/lit.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/ViewApplicationPage.tsx
- adds try catch error handling to LIT
- introduces answerBlocks to state
- add ability to run through application answers and decrypt answers if the user has round operator role
closes #222 
URL to test decrypt : [HERE](http://localhost:3000/#/round/0xb91fec0b68f39cbfdd75e4f08042c60724e1bd3b/application/0x3600000000000000000000000000000000000000000000000000000000000000-0xb91fec0b68f39cbfdd75e4f08042c60724e1bd3b)
note: reached out to LIT team to ask if
-  we can pass in a config to override the alert box and show our own custom message
https://discord.com/channels/896185694857343026/916383445784096839/1011148394938519613
- how to get jest to work with lit (this issue is something even grants hub is facing)
https://discord.com/channels/896185694857343026/916383445784096839/10111629563498455 …
=> feat: integrate LIT decrypt

packages/round-manager/src/app/context/ProgramContext.tsx, packages/round-manager/src/context/ProgramContext.tsx, packages/round-manager/src/context/__tests__/ProgramContext.test.tsx, packages/round-manager/src/features/api/__tests__/program.test.ts, packages/round-manager/src/features/api/program.ts, packages/round-manager/src/features/program/ListProgramPage.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/program/__tests__/ListProgramPage.test.tsx, packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx, packages/round-manager/src/features/round/CreateRoundPage.tsx, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/CreateRoundPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/index.tsx, packages/round-manager/src/test-utils.tsx
Use Context API for program state slice.
This PR has been 
- mobbed with the team to explore + implement react-context
- retire rtk-query for Program List page
- add tests
Other API will be migrated 
closes #298
=> 298  react context

packages/contracts/scripts/round/createRound.ts, packages/round-manager/src/features/common/ProgressModal.tsx
- fix There are no focusable elements inside the FocusTrap. Picked up from https://github.com/tailwindlabs/headlessui/issues/407#issuecomment-822753975
refs: https://github.com/gitcoinco/grants-round/issues/319
Locally Tested
=> chore: fix There are no focusable elements inside the FocusTrap

packages/round-manager/src/features/round/RoundApplicationForm.tsx
fixes #274
Move social fields move social fields to project information section
=> feat: move social fields to project information section

packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx
This PR implements the bulk approval feature in the rejected applications tab
closes #304
=> feat: bulk approve rejected applications

packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx
This PR properly aligns the bulk select button
closes #333
=> fix: misaligned bulk select button

packages/round-manager/src/features/common/ConfirmationModal.tsx, packages/round-manager/src/features/common/ProgressModal.tsx, packages/round-manager/src/features/common/__tests__/ConfirmationModal.test.tsx, packages/round-manager/src/features/common/__tests__/ProgressModal.test.tsx, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx
review `ProgressModal` and `ConfirmationModal` using TDD and original ACs (as much as possible)
fix #263 
- `packages/round-manager/src/features/common/__tests__/ConfirmationModal.test.tsx`
- `packages/round-manager/src/features/common/__tests__/ProgressModal.test.tsx`
=> task: tdd modal components

packages/round-manager/src/features/program/ListProgramPage.tsx
Updated the icon color and bottom background color of programs card
#292 
Visual testing
=> chore: update My Programs aesthetics

packages/round-explorer/README.md, packages/round-explorer/docs/DEV.md
- setup fleek deployment for round explorer for
- staging (branch : main)
- production (branch : release)
- added basic datadog integration for both branches
- enable auto deploy env for PR raised against main
- update documentation 
fixes https://github.com/gitcoinco/grants-round/issues/354
staging: https://regitcoin.on.fleek.co/
production: https://round-explorer.gitcoin.co/
=> feat: setup CI/CD pipeline

packages/round-manager/package.json
pull request has fulfilled all requirements outlined in the target package.
-->
=> another test CI/CD

packages/round-manager/.eslintrc.js, packages/round-manager/src/features/common/ProgressModal.tsx, packages/round-manager/src/features/program/__tests__/ListProgramPage.test.tsx, packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx
- add no-non-null-assertion: "off" to eslint test file overrides
- fix useWallet stub in ListProgramPage.test.tsx to silence console.log errors
- fix & remove some eslint-disable overrides
no associated issue
=> build: add no-non-null-assertion: "off" to eslint test file overrides

packages/round-manager/src/features/common/CopyToClipboardButton.tsx, packages/round-manager/src/features/common/__tests__/CopyToClipboardButton.test.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx
- create new feature CopyToClipboardButton
- add/update tests
- integrate feature into ViewRoundPage
fixes #373
Locally Tested by visting round page
=> feat: add CopyToClipboard to RoundPage

packages/round-manager/src/features/api/services/grantApplication.ts
fixed async executor function
#374 
no new code was introduced
=> chore(lint): rewrite function to fix no async promise executor error

packages/round-manager/src/features/round/ViewRoundPage.tsx
update URL of copy to clipboard on round page
fixes #378
tested locally
=> fix: update URL of copy to clipboard on round page

packages/round-manager/src/context/ApplicationContext.tsx, packages/round-manager/src/context/__tests__/ApplicationContext.test.tsx, packages/round-manager/src/features/api/__tests__/application.test.ts, packages/round-manager/src/features/api/__tests__/program.test.ts, packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/abi/index.ts, packages/round-manager/src/features/api/abi/projectRegistry.ts, packages/round-manager/src/features/api/application.ts, packages/round-manager/src/features/api/contracts.ts, packages/round-manager/src/features/api/services/grantApplication.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/index.tsx, packages/round-manager/src/test-utils.tsx
Verify owner address against VC.  Project Owner information is fetched from the projectRegistry contract. 
Refactored to use new ApplicationContext (removed RTK) for the ViewApplicationPage.
fixes #290
refactored ViewApplicationPage tests to use ApplicationContext
=> 290  verify project owner address against vc

packages/round-manager/src/features/common/CopyToClipboardButton.tsx, packages/round-manager/src/features/common/__tests__/CopyToClipboardButton.test.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/tailwind.config.js
Adds color transition on click for copy to clipboard animation
fixes #396
Locally Tested
=> chore: add animation to CopyToClipboard

packages/round-manager/src/context/ApplicationContext.tsx, packages/round-manager/src/context/__tests__/ApplicationContext.test.tsx, packages/round-manager/src/features/api/__tests__/application.test.ts, packages/round-manager/src/features/api/application.ts, packages/round-manager/src/features/api/services/grantApplication.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/index.tsx, packages/round-manager/src/test-utils.tsx
- refactor ApplicationApproved | ApplicationRejected | ApplicationRecieved to use context api
- refactor ViewRoundPage to use context api
- update ApplicationContext to handle new application format
fixes #394
**Round:** 
http://localhost:3000/#/round/0x59cab4dfe63ff49ab6c9f64246fbc628acf23d49
**Application**: 
http://localhost:3000/#/round/0x59cab4dfe63ff49ab6c9f64246fbc628acf23d49/application/0x813c7647128123ae52148f8
5dc2e675e7df6335dc755c420a7797ee5754810ef-0x59cab4dfe63ff49ab6c9f64246fbc628acf23d49
If you don't have a round / application -> please create one to test this flow out
=> chore: update application context to use new application format

packages/round-manager/src/features/round/RoundApplicationForm.tsx
fixes https://github.com/gitcoinco/grant-hub/issues/398
Locally Tested
=> chore: mark required fields as optional to keep deisgn consistent

packages/round-manager/src/context/application/ApplicationContext.tsx, packages/round-manager/src/context/application/__tests__/ApplicationContext.test.tsx, packages/round-manager/src/context/program/CreateProgramContext.tsx, packages/round-manager/src/context/program/ReadProgramContext.tsx, packages/round-manager/src/context/program/__tests__/CreateProgramContext.test.tsx, packages/round-manager/src/context/program/__tests__/ReadProgramContext.test.tsx, packages/round-manager/src/features/api/__tests__/subgraph.test.ts, packages/round-manager/src/features/api/application.ts, packages/round-manager/src/features/api/ipfs.ts, packages/round-manager/src/features/api/program.ts, packages/round-manager/src/features/api/services/program.ts, packages/round-manager/src/features/api/subgraph.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/ProgressModal.tsx, packages/round-manager/src/features/common/__tests__/ProgressModal.test.tsx, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/program/ListProgramPage.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/program/__tests__/CreateProgramPage.test.tsx, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx, packages/round-manager/src/features/round/CreateRoundPage.tsx, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx, packages/round-manager/src/index.tsx, packages/round-manager/src/test-utils.tsx
using new react context hook useCreateProgram
split ProgramContext into ReadProgramContext and CreateProgramContext
fix #398
=> feat: add indexing step to create program process

packages/round-manager/src/context/RoundContext.tsx, packages/round-manager/src/context/program/ReadProgramContext.tsx, packages/round-manager/src/features/api/__tests__/program.test.ts, packages/round-manager/src/features/api/program.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/program/__tests__/ListProgramPage.test.tsx, packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/CreateRoundPage.test.tsx, packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/index.tsx, packages/round-manager/src/test-utils.test.tsx, packages/round-manager/src/test-utils.tsx
Review and test following components:
closes #105
=> feat: tdd round pages + refactor to context api

packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/RoundApplicationForm.tsx
chore: remove social questions from application schema
fix #387
this PR is based off of #417, updated to latest `main` branch
I couldn't think of a good way to test this, since this is basically a change in configuration for the pre-determined application questions
=> chore: remove social questions from application schema

.github/workflows/contract.yml, .github/workflows/grant-explorer.yml, .github/workflows/round-manager.yml
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
fixes: #432
=> chore: use unique workflow names 

CODEOWNERS
Just removing myself from the CODEOWNERS file
=> chore: remove self from CODEOWNERS file

.husky/commit-msg, commitlint.config.js, package.json, yarn.lock
add husky hook for commit linting and conventional commit style
fixes #402
=> chore(git): setup commit linting

packages/round-manager/src/context/round/CreateRoundContext.tsx, packages/round-manager/src/context/round/RoundContext.tsx, packages/round-manager/src/context/round/__tests__/CreateRoundContext.test.tsx, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/subgraph.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx, packages/round-manager/src/features/round/CreateRoundPage.tsx, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx, packages/round-manager/src/index.tsx, packages/round-manager/src/test-utils.tsx
- refactor to use CreateRoundContext instead of RTK query
- create enum for storage protocol id
- update useWallet mock to prevent console error logs during test runs
fix #399
=> feat: add indexing step to create round progress modal

.husky/pre-commit, lerna.json, package.json, packages/contracts/package.json, packages/graph/tests/.latest.json
- use lerna for running top-level scripts
- update husky to use lerna
- update lerna version to v5
- use nx in lerna for faster task running
fixes #441 
no change in tests
=> feat(monorepo): use lerna for running tasks in parallel

packages/grant-explorer/src/features/common/Navbar.tsx
fixes https://github.com/gitcoinco/grants-round/issues/349
=> chore: update navbar gap

packages/round-manager/src/context/application/ApplicationContext.tsx, packages/round-manager/src/context/program/CreateProgramContext.tsx, packages/round-manager/src/context/program/ReadProgramContext.tsx, packages/round-manager/src/context/round/CreateRoundContext.tsx, packages/round-manager/src/context/round/RoundContext.tsx, packages/round-manager/src/features/api/lit.ts, packages/round-manager/src/features/api/program.ts, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx
Improve datadog logging 
fixes: https://github.com/gitcoinco/grants-round/issues/258
=> chore: improve datadog logging

packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
remove program id/name from Grant Explorer round page
https://github.com/gitcoinco/grants-round/issues/351#issuecomment-1268428960
=> feat(ge): remove program id/name from round page

packages/round-manager/src/context/program/ReadProgramContext.tsx, packages/round-manager/src/context/program/__tests__/ReadProgramContext.test.tsx, packages/round-manager/src/context/round/RoundContext.tsx, packages/round-manager/src/context/round/__tests__/RoundContext.test.tsx, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/program/ListProgramPage.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/program/__tests__/ListProgramPage.test.tsx, packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx
also:
- ViewProgramPage and ViewRoundPage now use ProgressStatus to check state rather than isLoading boolean
- removed incorrect dependencies in RoundContext useEffect
fixes #448
=> fix: view round and view program no longer shows 404 error on first page load

packages/contracts/contracts/votingStrategy/IVotingStrategy.sol, packages/contracts/contracts/votingStrategy/QuadraticFundingStrategy/QuadraticFundingVotingStrategyImplementation.sol, packages/contracts/docs/contracts/votingStrategy/IVotingStrategy.md, packages/contracts/docs/contracts/votingStrategy/QuadraticFundingStrategy/QuadraticFundingVotingStrategyImplementation.md, packages/contracts/test/_votingStrategy/QuadraticFundingVotingStrategyImplementation.test.ts
Move condition check to interface as a modifier
Locally Tested
=> chore: move condition check to interface modifier

packages/contracts/contracts/payoutStrategy/IPayoutStrategy.sol, packages/contracts/contracts/payoutStrategy/MerklePayoutStrategy.sol, packages/contracts/docs/CHAINS.md, packages/contracts/docs/DEPLOY_STEPS.md, packages/contracts/docs/contracts/payoutStrategy/IPayoutStrategy.md, packages/contracts/docs/contracts/payoutStrategy/MerklePayoutStrategy.md, packages/contracts/package.json, packages/contracts/scripts/config/payoutStrategy.config.ts, packages/contracts/scripts/payoutStrategy/deployMerklePayoutStrategy.ts, packages/contracts/scripts/utils.ts, packages/contracts/test/_votingStrategy/QuadraticFundingVotingStrategyImplementation.test.ts, packages/contracts/test/payoutStrategy/MerklePayoutStrategy.test.ts
- create IPayoutStrategy abstract contract
- implement MerklePayoutStrategy which extends IPayoutStrategy
- add script to deploy MerklePayoutStrategy
- update documentation + tests
- fixes https://github.com/gitcoinco/grants-round/issues/404
- fixes https://github.com/gitcoinco/grants-round/issues/406
https://goerli.etherscan.io/address/0x62b3CE47829777db4ec4dd3d9FF268168C562547#code
=> feat: add PayoutStrategy contract

CONTRIBUTING.md, README.md, packages/round-manager/docs/DEV.md
also fix typos and style in other md docs
Fixes #518 
not applicable
=> chore(docs): add CONTRIBUTING.md

.github/workflows/grant-explorer.yml, .github/workflows/round-manager.yml
enable yarn caching for round-manager and grant-explorer
fixes #525 
tested locally using [act](https://github.com/nektos/act)
=> chore: use caching and frozen-lockfile in CI

packages/grant-explorer/src/context/BallotContext.tsx, packages/grant-explorer/src/context/__tests__/BallotContext.test.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
Implement remove project from ballot
closes #355
=> feat(ge): implement remove project from ballot

packages/grant-explorer/src/features/common/AccessDenied.tsx, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/NotFoundPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
fixes #521
**Testing**
(fleek preview link)/#/round/5/0xe005f9bfabb61c2f04a08bf023044f9e1ed7dedd
=> feat(ge): align margins on grant explorer

packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/common/AccessDenied.tsx, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/NotFoundPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx, packages/grant-explorer/src/index.tsx
feat: view selected projects on ballot
- add roundid and chainid to ballot url
fixes #356
=> feat: view selected projects on ballot #356

packages/contracts/contracts/round/RoundImplementation.sol, packages/contracts/docs/contracts/round/RoundImplementation.md, packages/contracts/scripts/round/createRound.ts, packages/contracts/scripts/utils.ts, packages/contracts/test/payoutStrategy/MerklePayoutStrategy.test.ts, packages/contracts/test/round/RoundFactory.test.ts, packages/contracts/test/round/RoundImplementation.test.ts
- update RoundImplementation to invoke init on PayoutStrategy
- add function updateDistribution to invoke updateDistribution on PayoutStrategy
fixes https://github.com/gitcoinco/grants-round/issues/405
fixes https://github.com/gitcoinco/grants-round/issues/407
=> feat: update RoundImplementation to link to PayoutStrategy

packages/round-manager/src/features/program/ListProgramPage.tsx, packages/round-manager/src/features/program/__tests__/ListProgramPage.test.tsx
fixes #539
Infinite loading spinner, updated tests to support new fetchProgramsStatus enum.
=> fix: infinite loading spinner with new users

packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx
- update default application questions
- update form data schema to support dynamic customizable questions
- update application schema generator to match new form data schema
fixes #451
example application metadata: https://gitcoin.mypinata.cloud/ipfs/bafkreibrymxlkozgroes22eavhqhygkns6rh7frgsdueff2q6vqkuq5idm
=> feat(rm): revise default application configuration page

packages/round-manager/src/features/common/styles.ts, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
- prevent users from picking past dates
- add validation error if application start date is in the past
fixes #450
=> feat: cleaner date picker UX

packages/round-manager/.gitignore, packages/round-manager/package.json, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx, packages/round-manager/yarn.lock
- add encrypted toggle to editable questions
- add required toggle to editable questions
- set payout wallet address in disable state
- add empty cross icon which does nothing
- update .gitignore to exclude .vscode
closes https://github.com/gitcoinco/grants-round/issues/501
closes https://github.com/gitcoinco/grants-round/issues/534
=> feat: (rm)  toggle application question

packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx
- implement remove application question
- implement add application question
fixes https://github.com/gitcoinco/grants-round/issues/503
fixes https://github.com/gitcoinco/grants-round/issues/502
=> feat (rm) : add / remove question

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> feat: add application open dates to button

packages/round-manager/src/features/api/contracts.ts
bug fix: revert project registry contract addresses to correct values
=> bugfix prod deploy oct 28

packages/grant-explorer/.env.sample, packages/grant-explorer/package.json, packages/grant-explorer/src/app/wagmi.ts, packages/grant-explorer/yarn.lock, packages/round-manager/.env.sample, packages/round-manager/package.json, packages/round-manager/src/app/wagmi.ts, packages/round-manager/yarn.lock
- bump rainbow package
- add REACT_APP_ENV env and default to development
- ensure test and mainnet chains show on dev env
- ensure mainnet chains show up on production env
fixes #579
=> feat: add fantom chain to rm + ge

packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/test-utils.tsx, packages/round-manager/.run/All Tests.run.xml, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx, packages/round-manager/src/test-utils.tsx
As a round operator
I want to configure the quadratic funding settings for my round
So that the mechanism fits my needs
fixes #513, fixes #570
=> feat: add matching fund fields

packages/contracts/docs/CHAINS.md, packages/contracts/docs/DEPLOY_STEPS.md, packages/contracts/hardhat.config.ts, packages/contracts/scripts/config/payoutStrategy.config.ts, packages/contracts/scripts/config/program.config.ts, packages/contracts/scripts/config/round.config.ts, packages/contracts/scripts/config/votingStrategy.config.ts, packages/grant-explorer/.env.sample, packages/grant-explorer/src/features/api/utils.ts, packages/graph/README.md, packages/graph/config/fantom-testnet.json, packages/graph/package.json, packages/round-manager/.env.sample, packages/round-manager/src/features/api/contracts.ts, packages/round-manager/src/features/api/utils.ts
-  Envs have been updated with `REACT_APP_SUBGRAPH_FANTOM_TESTNET_API `
fixes #500
=> feat: add support for fantom testnet

packages/contracts/.gitignore, packages/contracts/docs/DEV.md, packages/contracts/package.json, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
This pr dynamically renders the custom questions in the application detail page
closes #535
=> feat: dynamically render application custom questions

packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/program/__tests__/CreateProgramPage.test.tsx
Add Chain Info on program creation
fixes #558
=> feat: add Program Chain field

packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
=> feat: added support contact dropdown type

packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
Add error modal in application review flow
https://github.com/gitcoinco/grants-round/issues/468
=> feat: wire in error modal on application review flow

packages/round-manager/src/features/common/ProgressModal.tsx, packages/round-manager/src/features/program/__tests__/CreateProgramPage.test.tsx, packages/round-manager/tailwind.config.js
=> feat: modal progress animation

packages/round-manager/src/features/round/RoundDetailForm.tsx
fixes resize issue on listbox
fixes #610
=> fix (rm) : dropdown resize fix

packages/grant-explorer/src/app/wagmi.ts, packages/round-manager/src/app/wagmi.ts
Optimism contracts + subgraph haven't been deployed.
Removing this fixes the UI error
fixes #617
=> chore: disable optimism network

.husky/pre-push, packages/round-manager/src/app/wagmi.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx, packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
GIVEN that I am on step one of Round Creation
WHEN I look at the page
THEN I see the empty state of the Contact Information field next to Support Input
GIVEN that I am on step one of Round Creation
WHEN I click on the Contact Information field
THEN I can enter text into the field
GIVEN that I have not entered an email or URL in the Contact Information field
WHEN I click next
THEN I see an error message that I must enter contact information
GIVEN that I have entered in a Support Input and Contact Information
WHEN I deploy the round
THEN the information is saved in my round metadata
closes #603
=> feat: support contact input field

packages/grant-explorer/src/context/BallotContext.tsx, packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx
Note: This should be merged after #627
- add Navbar
- refactory code to introduce finalBallot in context state
fixes https://github.com/gitcoinco/grants-round/issues/594
refs https://github.com/gitcoinco/grants-round/issues/484
http://localhost:3000/#/round/5/0xcef1772dd6764c95f14c26b25e8f012c072c5f77/ballot
=> feat: add navbar to ballot page 

packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx
- build the empty ballot empty state
- update tests
fixes #484
=> feat : ballot empty state

packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/round-manager/src/features/api/contracts.ts, packages/round-manager/src/features/common/Spinner.tsx, packages/round-manager/src/features/program/ListProgramPage.tsx, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/round/RoundDetailForm.tsx
- [chore: fix spinner position](https://github.com/gitcoinco/grants-round/commit/80ea7a7947e2befbbc20134dc94c9aa3627f8dde)
- [chore: wire in project registry fantom contract address](https://github.com/gitcoinco/grants-round/commit/b50a4da02495c8ffbccb1724b919997c6cb41ac6)
- [chore: update text on ballot builder](https://github.com/gitcoinco/grants-round/commit/3ec3fe6698f3fbd521e2e08b17a263d9bfe7e96d)
- [fix: broken matching funds ui](https://github.com/gitcoinco/grants-round/commit/18b42d33d478976c1b67fe13c644c4dadc2f1cd6)
closes #640 
closes #643 
closes #632
=> chore: ui fixes + improvement

packages/grant-explorer/src/context/BallotContext.tsx, packages/grant-explorer/src/context/__tests__/BallotContext.test.tsx, packages/grant-explorer/src/features/api/LocalStorage.ts, packages/grant-explorer/src/features/api/__tests__/localstorage.test.ts
- implement addToFinalBallot to remove from shortlist before adding to finalBallot
- implement removeFromFinalBallot to add to shortlist after removing from shortlist
- update localstorage to include loadFinalBallot and saveFinalBallot
refs #586
refs #488
=> feat: update BallotContext with finalBallot implementation

conventionalcommit.coauthors, packages/grant-explorer/src/context/BallotContext.tsx, packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx
Built on top of #639
closes #487
WHEN I click the Select button
THEN the Select button turns purple (aka the selecting state)
WHEN I click on a project in my shortlist
THEN the project changes to the selected state (i.e. highlighted in gray)
AND the text of the Select button changes to "Add Selected (N) to Final Donation" (where N is number of selected projects in shortlist)
WHEN I click on a selected project
THEN the project changes to the unselected state (i.e. back to white background)
AND the text of the Select button updates to the correct number of selected projects
WHEN I click on the selected project
THEN the project changes to the unselected state
AND the copy of the Select button changes back to "Select"
WHEN I click the "Select" button
THEN I return to the default state (and …
=> feat: implement select in shortlist

conventionalcommit.coauthors, packages/grant-explorer/src/context/BallotContext.tsx, packages/grant-explorer/src/context/__tests__/BallotContext.test.tsx, packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx
Built on top of #654 
- refactor in ViewBallotPage
- update handleAddToFinalDonation to accept multiple projects
- implements add to Final Donation ballot
closes #586
closes #660
=> feat: add to final donation

packages/grant-explorer/src/features/ViewBallotPage.tsx
This PR adds the functionality to remove project from shortlist
=> feat(ge): remove project from shortlist

packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
Matching Funds Available is not getting updated in Grants Explorer, round details page. The PR fixes it.
fixes #633
=> fix: matching funds issue

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> chore: fix footer on explorer main page

packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx
As a donor
I want to enter in specific donations to each project on my final ballot
So that I can help my preferred projects earn matching funds
closes https://github.com/gitcoinco/grants-round/issues/489
=> feat: get donation summary

packages/grant-explorer/package.json, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/common/ErrorModal.tsx, packages/grant-explorer/src/features/common/InfoModal.tsx, packages/grant-explorer/src/features/common/ProgressModal.tsx, packages/grant-explorer/src/features/common/__tests__/ErrorModal.test.tsx, packages/grant-explorer/src/features/common/__tests__/InfoModal.test.tsx, packages/grant-explorer/src/features/common/__tests__/ProgressModal.test.tsx, packages/grant-explorer/src/setupTests.ts, packages/grant-explorer/src/test-utils.tsx, packages/grant-explorer/yarn.lock
- wired in ProgressModal
- wired in ErrorModal
refs #516
=> chore: wire in ProgressModal + Error Modal + Info Modal

packages/grant-explorer/package.json, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx, packages/grant-explorer/yarn.lock
feat: added transition text and tests
fixes #667
=> feat: shortlist button update

packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/common/ConfirmationModal.tsx, packages/grant-explorer/src/features/common/__tests__/ConfirmationModal.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx, packages/round-manager/src/features/api/utils.ts
WHEN I click the "Submit Your Donation" button
THEN I see an error message below the button that says "You must enter donations for all final ballot projects"
WHEN I do not have enough funds in my wallet
THEN I see an error "You do not have enough funds for these donations"
WHEN I click the "Submit Your Donation" button
THEN I see the donation confirmation modal
WHEN I click "Cancel"
THEN the modal closes
AND I am kept on the Ballot Builder page
~GIVEN that I am looking at the donation confirmation modal
WHEN I click "Confirm"
THEN the modal closes~
^ Ignore this as this will be wired in the next story
closes #506
=> feat: initiate donation submission

packages/grant-explorer/src/context/BallotContext.tsx, packages/grant-explorer/src/context/__tests__/BallotContext.test.tsx, packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
fixes #679 
This updates the ballot context to not be so buggy. 
In addition it adds a state to the "Add/Remove ..." from shortlist button with a "Remove from final ballot" button when a shortlist item has been moved to the final ballot. 
Consequentially, it also removes the transition state of the button "Added to Shortlist" as this causes difficulty in state management.
=> fix: 679 buggy ballots

packages/grant-explorer/package.json, packages/grant-explorer/src/context/__tests__/RoundContext.test.tsx, packages/grant-explorer/src/features/api/__tests__/round.test.ts, packages/grant-explorer/src/features/api/round.ts, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/test-utils.tsx, packages/grant-explorer/yarn.lock, packages/round-manager/src/features/round/ViewApplicationPage.tsx
This PR adds verified/unverified badges to the grant explorer project details
closes #649
=> feat(ge): add verified checkmark to project details

packages/grant-explorer/src/index.tsx, packages/round-manager/src/index.tsx
=> chore: enable coolMode

packages/grant-explorer/src/features/ViewBallotPage.tsx
If you have added an amount to a project in the final donation, but move that project back to the shortlist then the amount still shows up in the summary.
fixes #696
=> fix: donation summary bug

packages/grant-explorer/src/features/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx
=> chore: open modal to connect button

.husky/pre-push, package.json, packages/round-manager/src/features/api/__tests__/program.test.ts, packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
=> feat: add typechecking to prepush hook

packages/grant-explorer/src/features/ViewBallotPage.tsx
This PR resolves the console error in grant-explorer yarn test
closes #703
=> fix: console error in grant-explorer yarn test

packages/grant-explorer/src/features/common/styles.ts
Fixes project card description overflow issue
fixes #711
=> fix: project card overflow issue

packages/grant-explorer/src/features/ViewBallotPage.tsx
As a user
I want to see a shorter description of a project
So that the UI of the Donation Builder doesn't look broken
fixes #690
=> fix: project description issue

packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
As a user
I want to be able to add a project I like to my shortlist
So that I don't have to navigate away from the landing page in order to do so
fixes #694
=> feat: add shortlist button in project cards

lerna.json, packages/api/README.md, packages/api/index.ts, packages/api/package-lock.json, packages/api/package.json, packages/api/src/__tests__/utils.test.ts, packages/api/src/index.ts, packages/api/src/utils.ts, packages/api/src/votingStrategies/linearQuadraticFunding.ts, packages/api/types.ts
=> chore: setup calculate method

packages/contracts/docs/CHAINS.md, packages/contracts/docs/DEPLOY_STEPS.md, packages/contracts/hardhat.config.ts, packages/contracts/scripts/config/payoutStrategy.config.ts, packages/contracts/scripts/config/program.config.ts, packages/contracts/scripts/config/round.config.ts, packages/contracts/scripts/config/votingStrategy.config.ts, packages/contracts/scripts/program/createProgram.ts, packages/contracts/scripts/round/createRound.ts, packages/grant-explorer/.env.sample, packages/grant-explorer/src/app/wagmi.ts, packages/grant-explorer/src/features/api/contracts.ts, packages/grant-explorer/src/features/api/utils.ts, packages/graph/README.md, packages/graph/config/mainnet.json, packages/graph/package.json, packages/round-manager/src/app/wagmi.ts, packages/round-manager/src/features/api/utils.ts
As a round operator
I want to have the protocol contracts available on Ethereum
So that I can run a round on that chain
Deploy contracts on Ethereum mainnet
fixes #723
=> feat: deploy contracts to ethereum mainnet

packages/contracts/contracts/votingStrategy/QuadraticFundingStrategy/QuadraticFundingVotingStrategyImplementation.sol, packages/contracts/docs/contracts/votingStrategy/QuadraticFundingStrategy/QuadraticFundingVotingStrategyImplementation.md, packages/contracts/test/_votingStrategy/QuadraticFundingVotingStrategyImplementation.test.ts, packages/contracts/test/round/RoundImplementation.test.ts, packages/graph/abis/QuadraticFundingVotingStrategyImplementation.json, packages/graph/schema.graphql, packages/graph/src/votingStrategy/quadraticFunding/implementation.ts, packages/graph/subgraph.template.yaml, packages/graph/tests/votingStrategy/quadraticFunding/implementation.test.ts
=> feat: add project id to contracts

packages/grant-explorer/src/assets/search-grey.svg, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/grant-explorer/src/index.tsx
As a donor
I want to search projects
So that I can easily find specific projects
fixes #492
=> feat: search projects

packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/grant-explorer/tailwind.config.js
- add pulse effect
- update headsup text
fixes #701
=> chore: add pulse effect + update headsup text

packages/grant-explorer/src/features/api/utils.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/common/Auth.tsx, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/index.tsx
=> fix ftm payout tokens

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
fixes footer issue.
Footer issue link: https://grant-explorer.gitcoin.co/#/round/1/0xdf75054cd67217aee44b4f9e4ebc651c00330938/0x0718e3d08633de4d7d2a6cf71e13f79507ba19f4389552fec4314e7ad5a13fc9-0xdf75054cd67217aee44b4f9e4ebc651c00330938
=> fix: footer issue in project page

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> main -> release

packages/api/src/__tests__/utils.test.ts
=> fix(api): fix fetch mocking in tests

packages/grant-explorer/src/features/round/ViewBallotPage.tsx
=> fix: updates the total donation to use better math

packages/graph/config/fantom-testnet.json, packages/graph/config/fantom.json
Add QFVotingStrategyFactoryAddress into the config file for fantom chains
=> chore: add missing config to fantom chain

packages/grant-explorer/src/context/QFDonationContext.tsx, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/common/AccessDenied.tsx, packages/grant-explorer/src/features/common/Auth.tsx, packages/grant-explorer/src/features/common/Footer.tsx, packages/grant-explorer/src/features/common/NotFoundPage.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ThankYou.test.tsx, packages/grant-explorer/src/index.tsx, packages/round-manager/src/features/common/AccessDenied.tsx
=> fix etherscan link on thank you page

packages/grant-explorer/src/features/common/Footer.tsx, packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Just did a quick overview of the round page https://grant-explorer.gitcoin.co/#/round/5/0x0739c6bb86297d847db22cc56388d3abfda551ff on mobile and threw in a few tweaks
=> fix: mobile view on round page

packages/grant-explorer/src/features/common/AccessDenied.tsx, packages/grant-explorer/src/features/common/NotFoundPage.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Mobile View Support on Ballot Page
fixes #800
fixes #804
=> fix: ui mobile support

packages/grant-explorer/src/features/round/ThankYou.tsx
Update share to twitter text
fixes #821
=> chore: update share to twitter link

packages/grant-explorer/src/features/round/ViewBallotPage.tsx
Ensure donation amount is defaulted to 0 when it is empty
fixes #820
=> fix: nan value on ballot

packages/grant-explorer/src/features/common/styles.ts
reduce card container width
fixes #818
=> fix: ensure 4 cards appear on grant explorer

packages/grant-explorer/src/features/round/ViewBallotPage.tsx
fixes spillover issue when description has long link which exceeds donation box width  
fixes #819
=> chore: fix spillover issue

packages/api/Dockerfile, packages/api/docker-compose.yml
This updates the docker file. 
It moves the api to yarn. 
Removes the health check.
=> fix: updated docker to work with yarn

packages/api/Dockerfile, packages/api/docker-compose.yml, packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Updates mostly small bugfixes.
=> 13 Dec 2022 Release

packages/grant-explorer/src/features/round/ThankYou.tsx
=> fix: scroll to top on thankyou load

packages/api/index.ts, packages/api/package.json, packages/api/src/handlers/calculateHandler.ts, packages/api/src/routes.ts, packages/api/tsconfig.json, packages/api/yarn.lock, packages/grant-explorer/.env.sample, packages/grant-explorer/craco.config.js, packages/grant-explorer/package.json, packages/grant-explorer/src/index.tsx, packages/grant-explorer/src/sentry.ts, packages/grant-explorer/yarn.lock, packages/round-manager/.env.sample, packages/round-manager/craco.config.js, packages/round-manager/package.json, packages/round-manager/src/index.tsx, packages/round-manager/src/sentry.ts, packages/round-manager/yarn.lock
round manager: https://sentry.io/organizations/gitcoin-protocol/projects/grants-round-rm/?project=4504326431834112
explorer: https://sentry.io/organizations/gitcoin-protocol/projects/grants-round-ge/?project=4504327111114752
api : https://sentry.io/organizations/gitcoin-protocol/projects/grants-round-api/?project=4504326423052288
fixes #844
=> feat: setup sentry on rm + ge

packages/api/src/cacheConfig.ts, packages/api/src/handlers/getProjectMatchDataHandler.ts, packages/api/src/handlers/getProjectSummaryDataHandler.ts, packages/api/src/handlers/getRoundMatchDataHandler.ts, packages/api/src/handlers/getRoundSummaryDataHandler.ts, packages/api/src/handlers/updateProjectSummaryHandler.ts, packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/handlers/updateRoundSummaryHandler.ts, packages/api/src/middleware/cacheMiddleware.ts, packages/api/src/utils.ts
this improves caching across the api. 
it also implements error handling, with cache availability, and should work even when the database is down.
=> feat: added error handling + improved caching

packages/grant-explorer/.env.sample, packages/grant-explorer/craco.config.js, packages/round-manager/.env.sample, packages/round-manager/craco.config.js
=> chore: append REACT_APP prefix

packages/api/index.ts, packages/api/src/__tests__/utils.test.ts, packages/api/src/cacheConfig.ts, packages/api/src/controllers/v1/routes.ts, packages/api/src/database.ts, packages/api/src/handlers/getProjectMatchDataHandler.ts, packages/api/src/handlers/getProjectSummariesDataHandler.ts, packages/api/src/handlers/getProjectSummaryDataHandler.ts, packages/api/src/handlers/getRoundMatchDataHandler.ts, packages/api/src/handlers/getRoundSummaryDataHandler.ts, packages/api/src/handlers/updateProjectSummaryHandler.ts, packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/handlers/updateRoundSummaryHandler.ts, packages/api/src/hotfixes/index.ts, packages/api/src/hotfixes/unicefMissingContributions.ts, packages/api/src/middleware/cacheMiddleware.ts, packages/api/src/test-utils.ts, packages/api/src/types.ts, packages/api/src/utils.ts, packages/api/src/votingStrategies/linearQuadraticFunding.ts
just format the code in the api package and improve the error handling with a result type.
=> Error results n code format

packages/api/index.ts, packages/api/sentry.ts
Moving sentry to it's own config file
=> chore: move sentry to it's own file

packages/api/prisma/migrations/20221223162105_match_add_unique_contributors_count/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/database.ts, packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/types.ts
Refs https://github.com/gitcoinco/grants-round/issues/510
=> chore: add uniqueContributorCount to match response

packages/grant-explorer/src/features/common/Banner.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx
https://gitcoindao.pagerduty.com/incidents/Q2FW70CREN440Z
=> chore: disable contribute button on ended round

infra/staging/index.js, packages/api/Dockerfile, packages/api/index.ts, packages/api/prisma/migrations/20221223162105_match_add_unique_contributors_count/migration.sql, packages/api/prisma/schema.prisma, packages/api/sentry.ts, packages/api/src/__tests__/utils.test.ts, packages/api/src/cacheConfig.ts, packages/api/src/controllers/v1/routes.ts, packages/api/src/database.ts, packages/api/src/handlers/getProjectMatchDataHandler.ts, packages/api/src/handlers/getProjectSummariesDataHandler.ts, packages/api/src/handlers/getProjectSummaryDataHandler.ts, packages/api/src/handlers/getRoundMatchDataHandler.ts, packages/api/src/handlers/getRoundSummaryDataHandler.ts, packages/api/src/handlers/updateProjectSummaryHandler.ts, packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/handlers/updateRoundSummaryHandler.ts, packages/api/src/hotfixes/index.ts, packages/api/src/hotfixes/unicefMissingContributions.ts, packages/api/src/middleware/cacheMiddleware.ts, packages/api/src/test-utils.ts, packages/api/src/types.ts, packages/api/src/utils.ts, packages/api/src/votingStrategies/linearQuadraticFunding.ts, packages/grant-explorer/src/features/common/Banner.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx
=> deploy:  main -> release

packages/api/package.json, packages/api/src/controllers/v1/routes.ts, packages/grant-explorer/package.json, packages/grant-explorer/src/context/__tests__/BallotContext.test.tsx, packages/grant-explorer/src/context/__tests__/QFDonationContext.test.tsx, packages/grant-explorer/src/features/api/api.ts, packages/grant-explorer/src/features/common/__tests__/Navbar.test.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx, packages/grant-explorer/yarn.lock, packages/round-manager/.run/All Tests.run.xml
fixes #482 
added tests for the new component
=> feat(ge): project stats

packages/round-manager/src/features/round/RoundDetailForm.tsx
=> fix: utc timezoning

packages/grant-explorer/.env.sample, packages/grant-explorer/yarn.lock, packages/round-manager/.env.sample, packages/round-manager/package.json, packages/round-manager/src/context/application/BulkUpdateGrantApplicationContext.tsx, packages/round-manager/src/features/api/api.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/ViewFundingAdmin.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/sentry.ts, packages/round-manager/src/test-utils.tsx, packages/round-manager/yarn.lock
As a round operator
I want to finalize and store my fund distribution
So that my round results are public and verifiable
fixes #510
=> feat:  see matching stats on Funding Admin tab

packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/ViewFundingAdmin.tsx
As a round operator
I want to finalize and store my fund distribution
So that my round results are public and verifiable
fixes #866
=> feat: add download json button

packages/grant-explorer/package.json, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/round-manager/package.json, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx
- [chore: set UTC timing on program detail page](https://github.com/gitcoinco/grants-round/commit/ce763cfde82a1b9684b0774943960aa98104a17c)
- [chore: add UTC timing to round detail page](https://github.com/gitcoinco/grants-round/commit/601b0d1a97b117fb008eb7aed5e57afb1582a30d)
- [chore: add UTC timing to round landing page](https://github.com/gitcoinco/grants-round/commit/64d9e7355374eb4c1912b77b96ce80e7ea7b1575)
closes #894 
closes #896
closes #897
=> default time to UTC

packages/graph/schema.graphql, packages/graph/src/legacy/votingStrategy/quadraticFunding/implementationLegacyV1.ts, packages/graph/src/program/factory.ts, packages/graph/src/program/implementation.ts, packages/graph/src/round/factory.ts, packages/graph/src/round/implementation.ts, packages/graph/src/votingStrategy/quadraticFunding/implementation.ts
Added timestamp for graph entities 
```
{
programs {
createdAt
updatedAt
rounds {
createdAt
updatedAt
votingStrategy{
votes {
createdAt
version
}
}
}
}
}
```
fixes #862
=> feat: add timestamp to Round, Program, QFVote, RoundProject

packages/grant-explorer/src/features/api/api.ts
It looks like the endpoint are wired in wrong.
I'm not clear if all of them should be POST but sticking to the whatever is written and just updating the URL path for now
=> chore: summary endpoint fix

packages/api/index.ts
=> fix: allow all origins xD

packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx
Set 24 hour timestamp
closes #933
=> 933 utc cleanup

packages/grant-explorer/package.json, packages/grant-explorer/src/features/api/__tests__/passport.test.ts, packages/grant-explorer/src/features/api/passport.ts, packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx, packages/grant-explorer/src/features/round/__tests__/ThankYou.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewBallotPage.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/grant-explorer/src/index.tsx, packages/grant-explorer/src/test-utils.tsx, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/program/ViewProgramPage.tsx, packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx
- chore: add open passport buttons
- chore: add fetch score logic
- chore: increase test coverage
- removes undefined behavior in passport state
- chore: score to fixed 2 decimal
- chore: add recalculate score trigger
- add zero score check
closes https://github.com/gitcoinco/grants-round/issues/962
closes https://github.com/gitcoinco/grants-round/issues/958
closes https://github.com/gitcoinco/grants-round/issues/959
=> feat: add PassportConnect

packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/types.ts
=> fix: match results

packages/grant-explorer/src/features/api/passport.ts, packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx
This PR is being merged to passport-integration-branch
- update design of passport connect page
- update calculate button 
refs #977 
refs #974
=> chore: update PassportConnect

packages/grant-explorer/src/features/common/PassportBanner.tsx
fixes #983 
changes wording on invalid passport banner
=> feat: change invalid passport message

packages/api/src/handlers/updateRoundMatchHandler.ts
=> fix: testnet matches (api)

packages/grant-explorer/src/features/api/passport.ts, packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx
closes https://github.com/gitcoinco/grants-round/issues/977
closes https://github.com/gitcoinco/grants-round/issues/974
=> integration-branch: passport changes

packages/api/README.md, packages/api/docker-compose.yml, packages/api/docs/linearQF.md, packages/api/index.ts, packages/api/sentry.ts, packages/api/src/controllers/v1/routes.ts, packages/api/src/database.ts, packages/api/src/handlers/singleton.ts, packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/handlers/updateRoundSummaryHandler.ts, packages/api/src/test-utils.ts, packages/api/src/types.ts, packages/api/src/utils.ts, packages/api/src/votingStrategies/__tests__/linearQuadraticFunding.test.ts, packages/api/src/votingStrategies/linearQuadraticFunding.ts, packages/api/tsconfig.json
Code Reference: https://github.com/gitcoinco/web/blob/master/app/grants/clr.py#L441-L478
closes #978
=> chore: implement capping

packages/api/docs/linearQF.md, packages/api/src/votingStrategies/linearQuadraticFunding.ts
User Story:
Explore what is necessary to include matching cap to round calculation
fixes #988
=> feat: update linearQF doc with QF calculation & example

packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx
Fix passport eligibility issue.
fixes #999
=> fix: passport eligibility issue

packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx
Co-authored-by: Josef Vacek <vacekj@outlook.com>
=> fix: ddos fetch passport

packages/grant-explorer/src/features/common/PassportBanner.tsx
=> fixing some verbiage

packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx
fix unregistered passport address logging
ref: https://sentry.io/organizations/gitcoin-protocol/issues/3879484565/?project=4504327111114752&query=is%3Aunresolved&referrer=issue-stream
fixes #1002
=> fix: unregistered passport address logging

packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx
Handle scenario where passport returns 200 but status is ERROR
https://discord.com/channels/562828676480237578/1065551844333604914/1065601234549100654
closes #1022
=> chore: handle passport error scenario

packages/api/src/handlers/getProjectMatchDataHandler.ts, packages/api/src/handlers/getProjectSummariesDataHandler.ts, packages/api/src/handlers/getProjectSummaryDataHandler.ts, packages/api/src/handlers/getRoundMatchDataHandler.ts, packages/api/src/handlers/getRoundSummaryDataHandler.ts, packages/api/src/handlers/updateProjectSummaryHandler.ts, packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/handlers/updateRoundSummaryHandler.ts
Currently the api expects all lowercase for round Id and project ID in the request
We need to update the API package to ensure all parameters are made lowercase to ensure endpoint works when address is sent in right format
fixes #975
=> fix: ensure api endpoints are not case sensitive

packages/grant-explorer/.env.sample, packages/grant-explorer/src/features/round/ViewBallotPage.tsx, packages/round-manager/src/test-utils.tsx
=> Ge upd donation builder copy 1028

packages/api/src/handlers/updateProjectSummaryHandler.ts, packages/api/src/handlers/updateRoundMatchHandler.ts, packages/api/src/handlers/updateRoundSummaryHandler.ts, packages/api/src/utils.ts, packages/api/src/votingStrategies/linearQuadraticFunding.ts
this fixes an unlisted bug on the summary update handler. The issue was summary data was returning 0 on the USD, contributors, etc. 
It also has a quality-of-life refactor for the graph fetches.
=> fix: api summary bug 

packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
As a potential grantee
I want to see the updated pre-round view
So that I can see the pretty design
fixes #652
=> feat: update ge PreRoundPage design

packages/api/src/votingStrategies/linearQuadraticFunding.ts
Fix for bug where 1st contribution for every project is counted twice
cc @bhargavaparoksham
=> bug: ensure contribution is counted once

packages/project-registry/src/__tests__/components/grants/Details.test.tsx, packages/project-registry/src/__tests__/components/providers/Github.test.tsx, packages/project-registry/src/__tests__/components/providers/Twitter.test.tsx
=> fixed func mock

packages/api/src/database.ts
=> fix: resolve round summary upsert issue

packages/api/src/votingStrategies/linearQuadraticFunding.ts
feat: temporarily disable passport for matching calcs
fixes #1119
=> feat: temporarily disable passport for matching calcs

packages/api/.dockerignore, packages/api/Dockerfile, packages/api/docker-compose.yml
=> fix: docker build

packages/api/Dockerfile, packages/grant-explorer/src/index.tsx, packages/round-manager/src/index.tsx
actually polyfills process and buffer
fixes #1118
=> fix: walletconnect buffer error

pnpm-lock.yaml
=> fix: reverted pnpm lock yaml to ...6ff12a3ea

pnpm-lock.yaml
Reverts gitcoinco/grants-round#1140
=> Revert "friday release 💀 "

packages/contracts/contracts/payoutStrategy/IPayoutStrategy.sol, packages/contracts/contracts/payoutStrategy/MerklePayoutStrategy/MerklePayoutStrategyFactory.sol, packages/contracts/contracts/round/RoundImplementation.sol, packages/contracts/docs/contracts/payoutStrategy/IPayoutStrategy.md, packages/contracts/docs/contracts/payoutStrategy/MerklePayoutStrategy/MerklePayoutStrategyFactory.md, packages/contracts/docs/contracts/payoutStrategy/MerklePayoutStrategy/MerklePayoutStrategyImplementation.md, packages/contracts/test/payoutStrategy/IPayoutInterface.test.ts, packages/contracts/test/round/RoundFactory.test.ts, packages/contracts/test/round/RoundImplementation.test.ts
- Add tests for RoundImplementation
- Add tests for IPayoutInterface
fixes #1157 
fixes #1159
=> chore: add test for RoundImplementation + IPayoutInterface

packages/round-manager/src/context/round/CreateRoundContext.tsx, packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/RoundApplicationForm.tsx, packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx
refers to #1101 
Metadata example: https://gateway.ipfscdn.io/ipfs/bafkreifzwo2eo2cgimq6gela5jpvpq2iuv33olk4axp437sq5ocg4q5ime/
Deployed round with updated metadata for testing: https://grantshub.gitcoin.co/#/chains/5/rounds/0xdbb585f33bfd6f34cba7f0f62850fb07eeb3ead2
Deployed PR: [https://bafybeihgqbf47x5xz2sy4mxexlucjv5r3gv2pn57lbcc45lqodpomjsy3m.on.fleek.co](https://bafybeihgqbf47x5xz2sy4mxexlucjv5r3gv2pn57lbcc45lqodpomjsy3m.on.fleek.co)
=> feat: add ability to require socials and/or verified socials

packages/builder/src/__tests__/components/application/Form.test.tsx, packages/builder/src/__tests__/utils/RoundApplicationBuilder.test.ts, packages/builder/src/actions/rounds.ts, packages/builder/src/components/application/Form.tsx, packages/builder/src/components/base/formValidation.ts, packages/builder/src/components/grants/About.tsx, packages/builder/src/components/grants/ToggleDetails.tsx, packages/builder/src/components/providers/Github.tsx, packages/builder/src/components/providers/Twitter.tsx, packages/builder/src/hooks/useValidateCredential.tsx, packages/builder/src/routes.tsx, packages/builder/src/styles/index.css, packages/builder/src/types/index.ts, packages/builder/src/types/roundApplication.ts, packages/builder/src/utils/RoundApplicationBuilder.ts, packages/builder/src/utils/roundApplication.ts
=> Enforce socials when applying to a round

packages/grant-explorer/src/features/round/ViewBallotPage.tsx
note: we need to start thinking about proper error handling with application specific error codes and a new error class.
fixes #1069
=> fix: transaction cancelled error handling

packages/contracts/contracts/round/RoundImplementation.sol, packages/contracts/docs/contracts/round/RoundImplementation.md, packages/contracts/test/payoutStrategy/MerklePayoutStrategyImplementation.test.ts, packages/contracts/test/round/RoundImplementation.test.ts
This has 2 commits
- [chore: refactor updateStartAndEndTime](https://github.com/gitcoinco/grants-round/commit/632c4eb9ae7ea6cb40bafcd5024103d7816ee024) which cleans up the logic and ensure round times and application times can overlap 
- [chore: add fee on top of match amount](https://github.com/gitcoinco/grants-round/commit/a29dd6f674c8c40dfd6fe71a10ae57ee7ad26dd9) which adds the fee on top of the matchAmount. 
This commit is isolated for the sole reason for being able to rollback if the team decides we want to have the fee amount to be taken from the match Amount 
Both commits add additional tests to ensure functionality works as expected.
This is to be reviewed and only then merged
=> chore: refactor fee

packages/contracts/contracts/round/RoundFactory.sol, packages/contracts/contracts/round/RoundImplementation.sol, packages/contracts/docs/contracts/round/RoundFactory.md, packages/contracts/docs/contracts/round/RoundImplementation.md, packages/contracts/scripts/utils.ts, packages/contracts/test/payoutStrategy/IPayoutInterface.test.ts, packages/contracts/test/payoutStrategy/MerklePayoutStrategyImplementation.test.ts, packages/contracts/test/round/RoundFactory.test.ts, packages/contracts/test/round/RoundImplementation.test.ts
- Reduces the bytecode size of the RoundImplementation by grouping update RoundTime functions into 1
- Adds roundFee
fixes #1158
=> feat: add updateStartAndEndTimes & roundFee

packages/builder/src/components/base/ProjectForm.tsx
=> project form "validate" returns true/false to avoid reading from async state

packages/graph/round/schema.graphql, packages/graph/round/src/payoutStrategy/merkle/factory.ts, packages/graph/round/src/payoutStrategy/merkle/implementation.ts, packages/graph/round/src/round/factory.ts, packages/graph/round/subgraph.template.yaml
- Index round fee percentage, round fee  address, distribution metaPtr, isReadyForPayout 
- Add handlers for all events being fired in Round
```
{
rounds(where:{
version: "1.0.0"
}) {
id
roundFeeAddress
roundFeePercentage
payoutStrategy {
id
isReadyForPayout
distributionMetaPtr {
pointer
}
}
}
}
```
fixes #1222
=> feat: Update subgraph to include matchAmount & fee data

packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/AddQuestionModal.tsx, packages/round-manager/src/features/common/InputIcon.tsx
=>  chore: adding link question type

packages/round-manager/package.json, packages/round-manager/src/context/round/FinalizeRoundContext.tsx, packages/round-manager/src/context/round/__tests__/FinalizeRoundContext.test.tsx, packages/round-manager/src/features/api/payoutStrategy/merklePayoutStrategy.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/ViewRoundResults.tsx, packages/round-manager/src/test-utils.tsx, pnpm-lock.yaml
- Add util function to generate merkle tree
- Update data distribution to ensure merkle root is generated
- Add new parameters on the distribution
- index
- matchingAmountInToken
- projectPayoutAddress
fixes #1195
=> chore: add merkle tree util function

packages/builder/src/components/application/Form.tsx, packages/builder/src/components/base/FormValidationErrorList.tsx, packages/builder/src/components/base/ProjectForm.tsx, packages/builder/src/components/base/VerificationForm.tsx, packages/builder/src/components/base/__tests__/VerificationForm.test.tsx, packages/builder/src/components/base/formValidation.ts, packages/builder/src/components/grants/inputs.tsx, packages/builder/src/types/index.ts
fixes #1133 
Deployment URL: https://bafybeifygyz7xbp5a2j7bkh7dc2k2ezfrx34efkyelni4hacx46maj3sbe.on.fleek.co/
=> 1133 twitter GitHub input validation

package.json, packages/builder/src/components/base/formValidation.ts, packages/builder/src/types/roundApplication.ts
=> 1163 add validation

packages/common/src/index.ts, packages/round-manager/package.json, packages/round-manager/src/context/round/FinalizeRoundContext.tsx, packages/round-manager/src/features/api/__tests__/payoutStrategy/merklePayoutStrategy.test.ts, packages/round-manager/src/features/api/api.ts, packages/round-manager/src/features/api/payoutStrategy/merklePayoutStrategy.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/round/ViewFundGrantees.tsx, packages/round-manager/src/features/round/ViewRoundResults.tsx, packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx
fixes #1194
USE  http://localhost:3000/#/round/0x90f301826d464708c74b437f868e6c8a3c591e5f
=> feat: populate unpaid table

package.json, packages/common/package.json, packages/common/src/index.ts, packages/grant-explorer/package.json, packages/grant-explorer/src/sentry.ts, packages/grant-explorer/src/setupTests.ts, packages/round-manager/package.json, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/ViewRoundStats.tsx, packages/round-manager/src/sentry.ts, packages/round-manager/src/setupTests.ts, pnpm-lock.yaml
=> Populate stats page with real data

packages/builder/src/components/base/VerificationForm.tsx
Refactored the `validate` function in `VerificationForm` for readability.
N/A
Tested locally
=> feat: refactor validate function in VerificationForm

packages/round-manager/src/context/round/FinalizeRoundContext.tsx, packages/round-manager/src/features/api/api.ts, packages/round-manager/src/features/api/payoutStrategy/merklePayoutStrategy.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/ViewFundGrantees.tsx, packages/round-manager/src/features/round/ViewRoundResults.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx, packages/round-manager/src/test-utils.tsx
Adds Finalize Results button to call 
#1258 
https://share.vidyard.com/watch/fYfYym7ATMW95wX6MAgbt7?
=> wip: [1258] mark contract ready for payout

packages/round-manager/src/context/round/ReclaimFundsContext.tsx, packages/round-manager/src/context/round/__tests__/ReclaimFundsContext.test.tsx, packages/round-manager/src/features/api/payoutStrategy/merklePayoutStrategy.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/round/ReclaimFunds.tsx, packages/round-manager/src/features/round/__tests__/ReclaimFunds.test.tsx, packages/round-manager/src/index.tsx
Adds the actual functionality that allows a round manager to retrieve funds from a round.
Closes #1197 
Tests will be written as part of the PR
=> [1197] reclaim funds contract interaction

packages/round-manager/src/features/api/round.ts
=> chore: ensure we use parsedUnits

packages/common/src/index.ts, packages/round-manager/src/features/api/api.ts, packages/round-manager/src/features/api/payoutStrategy/merklePayoutStrategy.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/common/ConfirmationModal.tsx, packages/round-manager/src/features/common/InfoModal.tsx, packages/round-manager/src/features/round/FundContract.tsx, packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/ViewFundGrantees.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/ViewRoundResults.tsx, packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx, packages/round-manager/src/test-utils.tsx
This addresses #1193 and #1151
=> feat: 1193 adds fund grantees tab and contract interaction for payout(s)

packages/round-manager/src/features/api/payoutStrategy/merklePayoutStrategy.ts
fixes [1324](https://github.com/gitcoinco/grants-stack/issues/1324)
=> chore: filter by projectId

packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx, packages/grant-explorer/src/test-utils.tsx, packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx, pnpm-lock.yaml
=> feat: display createdAt in GE project details

packages/builder/src/components/grants/Landing.tsx, packages/builder/src/styles/index.css
=> fix: revert images branding 2

packages/builder/src/components/application/Form.tsx
=> feat: 1334 submission modal

packages/grant-explorer/src/features/common/NavbarCart.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx
Makes the cart preview more spacious
=> chore: cleanup cart preview

packages/builder/src/contracts/abis/RoundImplementation.json, packages/grant-explorer/src/features/api/contracts.ts, packages/round-manager/src/features/api/abi/payoutStrategy/merklePayoutStrategyImplementation.ts, packages/round-manager/src/features/api/contracts.ts
- update ABI
- update contract address across all dapps
=> chore: update abi + contract address for beta

packages/round-manager/src/features/round/RoundDetailForm.tsx
=> chore: add stricter check around round date

packages/builder/.jest/setEnvVars.js, packages/builder/jest.config.js, packages/builder/src/services/pinata.ts
For some reason our pinata credentials were hardcoded. This PR removes them again.
=> chore: Remove pinata credentials

packages/grant-explorer/src/features/api/round.ts, packages/grant-explorer/src/features/round/ViewCartPage.tsx
Explorer: add tooltip to explain "Apply to all" function 
fixes #1356
=> feat: add apply to all tooltip in ge

packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/test-utils.tsx
=> fix: explorer data retrieval and token req

packages/round-manager/src/context/application/BulkUpdateGrantApplicationContext.tsx
fixes the error when we toggle rejected project to approved project
=> fix: bulk application status update bug

packages/grant-explorer/src/context/QFDonationContext.tsx, packages/grant-explorer/src/features/api/application.ts, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/round/ViewCartPage.tsx
Updated the voting function to ensure it matches the new signature and passing the applicationIndex
https://goerli.etherscan.io/tx/0x7ca103d22756215b8b1634f44bfa4d5148ede327d8967dec15a69414a5ddbcf3
=> chore: fix vote

packages/builder/src/contracts/deployments.ts
This fixes the loading of the existing Fantom projects.
=> hotfix: update fantom project registry address

packages/builder/src/components/application/Form.tsx, packages/builder/src/components/base/ErrorModal.tsx
This will show a new error message when the `applicationEndTime` > current date in seconds, otherwise it will show the transaction error message.
=> 1410 update error message

packages/round-manager/src/features/round/QuadraticFundingForm.tsx
=> add: missing tooltip text in rm 

packages/builder/src/components/rounds/Show.tsx
=> add: eligibility requirements and description for builder show comp

packages/builder/src/components/rounds/Show.tsx
Adds additional check before apply button is enabled for application start date.
=> add check for app start date

packages/builder/src/components/grants/List.tsx
Hides the Apply alert if the application dates have not started or have ended.
=> 1430 update showing round alert based on app dates

packages/round-manager/src/features/round/QuadraticFundingForm.tsx
=> 1419 manager open passport docs link on a new tab

packages/round-manager/src/features/round/FundContract.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx
=> feat: get current chainId from wagmi

packages/builder/src/components/rounds/Show.tsx
=> fix: prevent main content div from expanding over footer and header

packages/builder/src/utils/graphql.ts
=> chore: update graph

packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/FundContract.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsReceived.test.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsRejected.test.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx, packages/round-manager/src/test-utils.tsx
=> chore: wire in fee from graph

packages/round-manager/src/features/round/FundContract.tsx
This prevents a user from depositing more funds then necessary into the contract for payouts in the UI only.
- Disables Button
- Disables Input
- Updates placeholder with message
=> 1320 prevent user from over funding contract

packages/round-manager/src/features/round/FundContract.tsx, packages/round-manager/src/features/round/ReclaimFunds.tsx
=> fix: remove usd if NaN or 0

packages/round-manager/package.json, packages/round-manager/src/features/common/Spinner.tsx, packages/round-manager/src/features/round/ApplicationsReceived.tsx, pnpm-lock.yaml
closes https://github.com/gitcoinco/grants-stack/issues/1484
https://www.loom.com/share/0ab72775c0814e9f87ffc6f5c191703f
=> Decrypt fields in the applications CSV export

packages/round-manager/src/features/api/application.ts
- Instead of downloading a CSV, parsing it and creating another, we now download the applications in JSON format and generate a CSV, it looks like we'll be downloading this file in the future so we might as well do it now
- Decrypt all answers
- Make decryption of each row sequential to avoid getting rate limited out by Lit
- Add payout and signature
=> Deploy Application CSV fixes

packages/grant-explorer/src/features/round/ViewCartPage.tsx
fixes https://github.com/gitcoinco/grants-stack/issues/1357
=> mobile fixes

packages/round-manager/src/features/api/round.ts
https://discord.com/channels/562828676480237578/1098031144412381304/1098031144412381304
=> chore: fix admin role

packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/__tests__/Navbar.test.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Hide cart functionality if round has ended
fixes #1425
=> chore: remove cart on ended round

packages/grant-explorer/src/features/api/round.ts, packages/grant-explorer/src/features/api/rounds.ts
=> chore: add subgraph query

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
fix passport banner not showing up on explorer
fixes #1533
=> fix: passport banner not showing up on explorer

packages/round-manager/src/features/common/Utils.ts, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/ViewRoundSettings.tsx
What it says on the tin
Closes #1497 
To be added with write logic
=> [1497] Add round settings tab content to round settings page

packages/grant-explorer/src/context/RoundContext.tsx
Fixes the same issue we had on the round manager
=> fix: check for token undefined as condition to refetch round

packages/common/src/index.ts, packages/round-manager/src/features/round/ViewRoundSettings.tsx
=> fix: create getUTCDate and import correctly

packages/round-manager/package.json, packages/round-manager/src/features/round/ViewRoundStats.tsx, pnpm-lock.yaml
wip branch for #1342 
depends on: https://github.com/gitcoinco/allo-indexer-client/pull/8 https://github.com/gitcoinco/allo-indexer/pull/31
=> Hook up round stats page to calculator

packages/round-manager/src/features/round/FundContract.tsx
After finalizing the round, the Fund contract tab shows Amount in contract: 0 and gives the impression that the contract still needs funding.
fixes #1319
=> feat: update fund contract ui once its ready for payout

packages/common/src/index.ts, packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/common/SearchInput.tsx, packages/grant-explorer/src/features/common/__tests__/Navbar.test.tsx, packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx, packages/grant-explorer/src/features/discovery/RoundCard.tsx, packages/grant-explorer/src/features/discovery/RoundCardStat.tsx, packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/test-utils.tsx
UI changes as per [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=784-18459&t=DJhIAzDftemL80JA-0)
Closes #1516 
Closes #1518 
N/A
=> [1516] Update Passport banner copy & CTA 

packages/grant-explorer/src/features/api/contracts.ts, packages/round-manager/src/features/api/contracts.ts
Updated from https://github.com/allo-protocol/contracts/blob/main/docs/CHAINS.md
=> chore: update factory address

packages/grant-explorer/src/features/api/__tests__/round.test.ts, packages/grant-explorer/src/features/api/round.ts
=> chore: fix subgraph votingStrategy issue

packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx
fix: setState inside a component render function in passport connect
=> fix: setState inside a component render function in passport connect

packages/grant-explorer/src/features/discovery/RoundCard.tsx
Fix a string comparison to be lowercase
Fixes #1590 
Tested locally
=> fix: token address comparison

packages/grant-explorer/src/features/discovery/RoundCard.tsx
=> fix: token address comparison (#1591)

packages/grant-explorer/src/features/discovery/LandingPage.tsx
What the title says
N/A
Tested locally
=> feat: redirect to grants.gitcoin.co if user hits the landing page

packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx, packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Donated amount is not displayed. This fixes it.
N/A
Tested locally
=> Hotfix: display donated amount

packages/grant-explorer/src/app/wagmi.ts
=> chore: enable only mainnet

packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/discovery/ActiveRoundSection.tsx, packages/grant-explorer/src/features/discovery/RoundCard.tsx
Filtering out test chains was not working properly.
Fixes #1586 
Fixes #1584 
Fixes #1585 
Tested locally - to be tested in staging before merging to prod
=> fix: filter test chains out in prod

packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/discovery/ActiveRoundSection.tsx, packages/grant-explorer/src/features/discovery/ApplyNowPage.tsx, packages/grant-explorer/src/features/discovery/ApplyNowSection.tsx, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/discovery/RoundCard.tsx, packages/grant-explorer/src/features/discovery/RoundCardStat.tsx, packages/grant-explorer/src/test-utils.tsx
=> explorer cleanup

packages/builder/src/actions/projects.ts
=> set average stat to 0 if contributions count is 0

packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx
Right now, projects stay in the cart even after donating. Projects should clear out of the cart after a donation is complete.
fixes #1544
=> fix: clear cart when donation is successful

packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/SearchInput.tsx, packages/grant-explorer/src/features/discovery/ApplyNowPage.tsx, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/discovery/RoundCard.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
=> [1597]: round search fixes

packages/grant-explorer/src/features/common/SearchInput.tsx, packages/grant-explorer/src/features/discovery/ActiveRoundSection.tsx, packages/grant-explorer/src/features/discovery/ApplyNowPage.tsx
fixes #1629 
https://www.loom.com/share/22620ed099574268bbccdaf03395c523
=> feat: sort rounds by date

packages/builder/src/actions/projects.ts, packages/builder/src/utils/graphql.ts
Better error handling for when subgraphs are not defined.
Also better error logging for fetching applications. You now get a lot more information:
=> Subgraph endpoint error handling

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> fixed spacing

packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> chore: wire min donation amount

packages/grant-explorer/src/features/api/application.ts
=> estimate gas price

packages/round-manager/package.json, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/features/round/ViewRoundStats.tsx, pnpm-lock.yaml
closes https://github.com/gitcoinco/allo-indexer/issues/40
=> Use round token for match amount

packages/round-manager/package.json, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/features/round/ViewRoundStats.tsx, pnpm-lock.yaml
Reverts gitcoinco/grants-stack#1654
=> Revert "Use round token for match amount"

packages/grant-explorer/src/features/common/ProjectBanner.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx
Implement resizing of images on round page and detail page using pinata parameters. Context here: https://discord.com/channels/562828676480237578/1100440289442807838/1100440293779701771
fixes #1581
=> feat: resize images using pinata

packages/grant-explorer/src/features/api/application.ts
=> fix wrong name

packages/grant-explorer/src/features/api/application.ts
Pushing a fix for the gas cost estimate
N/A
N/A
=> Hotfix for prod gas issues

packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> chore: fix card issue

packages/grant-explorer/src/context/CartContext.tsx, packages/grant-explorer/src/context/__tests__/CartContext.test.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
closes  https://github.com/gitcoinco/grants-stack/issues/1649
=> chore: fix cart across tabs

packages/grant-explorer/package.json, packages/grant-explorer/src/features/api/application.ts, pnpm-lock.yaml
Skips the approval step if not necessary.
Closes #871 
Tested locally donating to current production round
=> [871] Remember ERC20 approval

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
[Discord Thread](https://discord.com/channels/562828676480237578/1103794356319686716)
=> hotfix: fix for contributor stats

packages/common/package.json, packages/common/src/index.ts, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/FundContract.tsx, packages/round-manager/src/features/round/ReclaimFunds.tsx, packages/round-manager/src/features/round/ViewFundGrantees.tsx, packages/round-manager/src/features/round/__tests__/FundContract.test.tsx, packages/round-manager/src/features/round/__tests__/ReclaimFunds.test.tsx, pnpm-lock.yaml
As a donor
I want to know what the USD value of my contributions are
So that I know if they meet the minimum donation threshold for the round
fixes #1537
=> feat: add usd value of donation during checkout

packages/builder/src/components/base/PurpleNotificationBox.tsx, packages/builder/src/components/grants/Edit.tsx, packages/builder/src/components/rounds/Apply.tsx
=> added reapply alert

packages/grant-explorer/src/context/CartContext.tsx, packages/grant-explorer/src/context/QFDonationContext.tsx, packages/grant-explorer/src/context/__tests__/CartContext.test.tsx, packages/grant-explorer/src/context/__tests__/QFDonationContext.test.tsx, packages/grant-explorer/src/features/api/application.ts, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewCartPage.test.tsx
=> fix: use bignumbers in cart

packages/builder/src/actions/projects.ts, packages/builder/src/actions/roundApplication.ts, packages/builder/src/components/grants/Details.tsx, packages/builder/src/utils/graphql.ts
Builder: need to prevent project owners from reapplying
#1526
=> Prevent project owners from reapplying

packages/round-manager/src/context/application/__tests__/BulkUpdateGrantApplicationContext.test.tsx, packages/round-manager/src/setupTests.ts
=> [1566] fixed test cases

packages/common/src/styles.ts, packages/round-manager/package.json, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/hooks.ts, packages/round-manager/tailwind.config.js, pnpm-lock.yaml
closes https://github.com/gitcoinco/grants-stack/issues/1474
related eng-only PR: https://github.com/gitcoinco/allo-indexer-client/pull/17
I noticed if your screen is small it's difficult to get both the upload widget and the table at the same time, so when you click Upload & revise you will get scrolled up to the table so you can see it update.
**No file selected:**
Revise button is disabled
**File selected:**
Added a little filename indicator so users know they have a file selected, maybe it could be more prominent?
**File is invalid:**
The error copy could be improved here but this comes form the indexer, we can fix it over that repo.
=> Upload CSV overrides to revise results

packages/grant-explorer/src/features/round/ViewCartPage.tsx
=> chore: add text to cart

packages/round-manager/src/context/round/RoundContext.tsx, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/NotFoundPage.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/FundContract.test.tsx, packages/round-manager/src/features/round/__tests__/ReclaimFunds.test.tsx, packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx, packages/round-manager/src/test-utils.tsx
=> fix: ensure show 404 page if on wrong network

packages/round-manager/src/features/round/RoundDetailForm.tsx
=> chore: ensure appliation date can be selected in future

packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/hooks.ts
- Fix infinite lifecycle
- Simplify lifecycle
- Use match amounts instead of USD to calculate saturation
I didn't have time to fix the tests but i am sure they'r easy to fix, I would merge this PR and fix in the origin
=> Fix saturation

packages/round-manager/package.json, packages/round-manager/src/features/api/exports.ts, packages/round-manager/src/features/round/ApplicationsReceived.tsx, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, pnpm-lock.yaml
Closes: https://github.com/gitcoinco/grants-stack/issues/1456
This also includes this PR to fix stats and matches without overrides.
=> Round Raw Data Exports

packages/round-manager/package.json, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx, packages/round-manager/src/hooks.ts, packages/round-manager/src/test-utils.tsx, pnpm-lock.yaml
fixes #1458 
Saturation controls.
This depends on this allo indexer client commit / PR: https://github.com/gitcoinco/allo-indexer-client/pull/21
=> feat: saturation controls

packages/round-manager/src/features/round/FundContract.tsx
=> fix: fee display magnitude

packages/round-manager/package.json, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx, packages/round-manager/src/hooks.ts, packages/round-manager/src/test-utils.tsx, pnpm-lock.yaml
Reverts gitcoinco/grants-stack#1706
=> Revert "feat: saturation controls"

packages/grant-explorer/src/app/wagmi.ts
=> chore: enable optimism

packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/test-utils.tsx
closes https://github.com/gitcoinco/grants-stack/issues/1766
=> Finalize Round View

packages/grant-explorer/src/features/common/Breadcrumb.tsx, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewCartPage.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
also removes back buttons outside of design spec
=> feat: add bread crumbs :bread:

packages/round-manager/src/features/round/ApplicationEligibilityForm.tsx, packages/round-manager/src/features/round/__tests__/ApplicationEligibilityForm.test.tsx
=> [1744] add remove eligibility req button

packages/grant-explorer/src/features/common/NavbarCart.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/index.css
- ensure mobile cart works on mobile 
- ensure chain name shows on grant explorer
- update text on ERC20 approval
fixes #1688 
fixes #1609
fixes #1690
=> chore: improve to grant explorer

packages/builder/src/components/application/Form.tsx
=> Builder: UX updates on Application Preview page

packages/builder/src/__tests__/components/grants/Details.test.tsx, packages/builder/src/components/base/Preview.tsx, packages/builder/src/components/grants/Details.tsx, packages/builder/src/components/grants/Show.tsx
=> builder: don't show stats/rounds tabs in new/edit preview

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
fixes #1531 
round to check: /#/round/5/0x1161fae3274be56f6d9286cb363fc2b43d0f48cb
=> fix: apply button color

packages/builder/src/components/application/Form.tsx, packages/builder/src/components/grants/Edit.tsx, packages/builder/src/components/rounds/Apply.tsx
=> 1529 - add preview copy message

packages/round-manager/src/features/round/RoundDetailForm.tsx
=> chore: update text on round creation

packages/grant-explorer/src/features/api/LocalStorage.ts, packages/grant-explorer/src/features/common/Navbar.tsx
Automatically update cart across all tabs if a project is added/removed to cart]
fixes #1689
=> Explorer: automatically update cart across all tabs if a project is added/removed to cart

packages/round-manager/src/context/round/CreateRoundContext.tsx
=> chore: filter out empty requirements

packages/round-manager/src/features/round/RoundDetailForm.tsx, packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
=> feat: make url checking in manager allow urls without protocols

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
=> feat: make project details page more responsive

packages/builder/src/components/application/Form.tsx, packages/builder/src/components/rounds/Apply.tsx
=> fix: preview bar on builder

packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ViewRoundPage.test.tsx
fixes #1890
fixes error page popping up on navigation due to incorrect permissions check in ViewRoundPage.tsx
=> fix: error page fix

packages/round-manager/src/features/round/ViewRoundSettings.tsx
Fixes #1901 
See https://discord.com/channels/562828676480237578/1116248042790719528 for related discussion
=> fix: 1901 edit button disabled during round period after cancel click

packages/builder/src/actions/projects.ts, packages/builder/src/components/application/Form.tsx
Prevent projects from applying multiple times to the same round cross-chain.
Closes #1892 
Tested locally
=> [1892] fix: prevent multiple cross-chain application for same project

packages/round-manager/src/features/round/ViewRoundPage.tsx
Debug mode is not working in staging: https://rmgitcoin.on.fleek.co/#/round/0x12bb5bbbfe596dbc489d209299b8302c3300fa40?debug=true
Expressions are not grouped correctly.
=> fix: debug mode for view round

packages/builder/src/__tests__/components/rounds/Show.test.tsx, packages/builder/src/components/rounds/Show.tsx
=> (Builder) Update Application Landing page for when applications have not opened yet 

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
fixes https://github.com/gitcoinco/grants-stack/issues/1968
=> Fix: incorrect formatting of project pages on Explorer

KB.md
Creates a KB.md in the repo for storing common problems and solutions, and general permanent knowledge sharing space for the project
fixes #2008
=> docs: add knowledgebase

KB.md, README.md, packages/grant-explorer/README.md, packages/round-manager/docs/EncryptingPII.md
=> Fix: typos

packages/grant-explorer/src/features/round/ViewCartPage.tsx
fix unable to donate to a round due to inaccurate "not enough funds" error
fixes #2057
=> Explorer: unable to donate to a round due to inaccurate "not enough funds" error

packages/builder/src/actions/roundApplication.ts, packages/common/src/chains.ts, packages/grant-explorer/src/features/api/types.ts, packages/round-manager/src/features/api/exports.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/ViewApplicationPage.tsx
Add LIT protocol support for PGN
fixes #2072
=> Add LIT protocol support for PGN

packages/builder/src/utils/wagmi.ts, packages/grant-explorer/src/app/wagmi.ts, packages/round-manager/src/app/wagmi.ts
enables pgn mainnet in prod by moving the chain to production chains.
=> chore: enable pgn mainnet in prod

packages/grant-explorer/src/context/CartContext.tsx, packages/grant-explorer/src/context/__tests__/CartContext.test.tsx, packages/grant-explorer/src/features/api/LocalStorage.ts, packages/grant-explorer/src/features/api/__tests__/localstorage.test.ts, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/common/CartNotification.tsx, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/NavbarCart.tsx, packages/grant-explorer/src/features/common/__tests__/Navbar.test.tsx, packages/grant-explorer/src/features/common/__tests__/NavbarCart.test.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/test-utils.tsx
As a donor,
I want add/remove projects in different rounds to/from the same cart
so that I can checkout all of the projects I want to support at once
fixes #2011
=> [MRC] Explorer: add/remove projects from different rounds to the same cart

packages/grant-explorer/src/features/api/utils.ts
Add pgn in doantion history page
=> [Explorer] Add pgn in doantion history page

packages/grant-explorer/src/context/CartContext.tsx, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewCartPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewCartPage.test.tsx
As a donor,
I want to see the projects that I've added to my cart grouped by chain AND within a chain, separated by round
so that I can see an overview of all projects that I plan on supporting
fixes #2012
=> [MRC] Explorer: view the projects I have in my cart by round and chain on cart checkout page 

packages/grant-explorer/src/features/round/ViewCartPage/Summary.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx
=> Multi Round Checkout

packages/round-manager/src/features/api/round.ts
=> temporary fix to support old/new round subgraph query

packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx
=> Add MRC Chain Progress steps

packages/grant-explorer/src/checkoutStore.ts, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
;) https://www.youtube.com/watch?v=3WAOxKOmR90
thank you redirect working
=> fix: NICE.

packages/grant-explorer/src/checkoutStore.ts, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/discovery/ActiveRoundSection.tsx, packages/grant-explorer/src/features/discovery/ApplyNowPage.tsx, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx, packages/grant-explorer/src/store.ts
fixes #2182 #2175 
also fixes donation history link not working
=> fix: thank you page not redirecting when only one chain checked out

packages/grant-explorer/src/features/discovery/LandingPage.tsx
re-enable Explorer homepage redirect from https://github.com/gitcoinco/grants-stack/pull/1806/files
closes #2117
=> explorer homepage redirects to grants.gitcoin.co

packages/grant-explorer/src/features/common/AccessDenied.tsx, packages/grant-explorer/src/features/common/NotFoundPage.tsx, packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> use cartProject when it's not undefined

packages/common/src/components/RoundsSubNav.tsx, packages/grant-explorer/src/features/common/CartNotification.tsx, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/NavbarCart.tsx, packages/grant-explorer/src/features/common/PassportBanner.tsx, packages/grant-explorer/src/features/round/PassportConnect.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
1. New bottom nav bar is hiding the Passport banner in explorer
2. nav bar is overcrowding the thank you page in explorer
fixes #2191  #2196
=> [Bug] Explorer: new bottom nav bar is hiding the Passport banner

packages/grant-explorer/src/checkoutStore.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/api/voting.ts
fixes donating dai on optimism.
fixes #2199
=> fix: dai on optimism

packages/grant-explorer/src/checkoutStore.ts, packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx
Reverts gitcoinco/grants-stack#2214
=> Revert "fix: dai on optimism"

.cm/approve_js_formatting.cm, .cm/approve_js_log_changes.cm, .cm/approve_tests.cm, .cm/code_experts.cm, .cm/estimated_time_to_review.cm, .cm/gitstream.cm, .cm/label_without_tests.cm, .cm/percentage_new_code.cm, .cm/safe_changes.cm, .github/workflows/gitstream.yml
adding https://docs.gitstream.cm/
=> Add gitstream

CODEOWNERS
=> update codeowners with the new team names

packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/round/FundContract.tsx
=> find token by address and chainId

packages/common/src/components/RoundsSubNav.tsx
=> add arbitrum round link to gg18 subnav

packages/grant-explorer/src/assets/thank-you.svg, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ApplyTooltip.tsx, packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx, packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx
Mobile UI fixes on cart page
fixes #2174
=> MRC: Mobile UI fixes on cart page

packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/common/__tests__/CopyToClipboardButton.test.tsx
=> fix: eth -> ftm on explorer running round page

packages/builder/craco.config.js, packages/builder/tsconfig.json
=> fix connect wallet bug by enabling sourcemaps

packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx, packages/grant-explorer/src/features/discovery/RoundCard.tsx, packages/grant-explorer/src/features/discovery/__tests__/ApplyNowSection.test.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx, turbo.json
=> fix: pull token info from chain on explorer

.github/workflows/builder.yml
=> ignore, testing github actions

docs/TOKENS.md
=> chore: add usdc info on polygon pos

packages/builder/src/utils/wagmi.ts
=> check env var is "true"

packages/grant-explorer/src/cartStore.test.tsx, packages/grant-explorer/src/checkoutStore.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/store.ts, pnpm-lock.yaml
=> feat: make cart handle new chains gracefully

packages/common/src/index.ts, packages/round-manager/src/features/program/ViewProgramPage.tsx
fixes manager crash with direct grants rounds
=> hotfix: temporarily handle direct grant rounds

packages/round-manager/src/features/round/FundContract.tsx
I want to know that I can fund the contract directly with any wallet
So that I know that I am not constrained to funding the contract via the UI
fixes #2370
=> Update fund contract copy in rm

packages/round-manager/src/features/round/DGApplicationsToApproveReject.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/DGApplicationsToApproveReject.test.tsx
Fix applications CSV download btn is missing
fixes #2420
=> [Manager] Applications CSV download btn is missing

packages/round-manager/src/features/round/ApplicationsToApproveReject.tsx, packages/round-manager/src/features/round/ApplicationsToReview.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/__tests__/ApplicationsToApproveReject.test.tsx
Fix direct grants applications received bug
=> fix dg applications received bug

.github/PULL_REQUEST_TEMPLATE.md
@bard rewriting the statements in first person felt very weird, so I left them as-is
fixes #2430
=> chore: add PR checklist to pr template

packages/grant-explorer/src/features/contributors/DonationsTable.tsx, packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
Fix incorrect token name on Donation History page
fixes #2394
=> fix incorrect token name on Donation History page

packages/round-manager/src/features/round/RoundApplicationForm.tsx
As a Round Manager
I want to have more control over my application questions
So that I can customize my application questions to my direct grants round
fixes #2444
=> Make the Application Detail and Amount requested questions optional 

packages/grant-explorer/src/features/common/styles.ts
Project titles were not visible because they were white. closes https://github.com/gitcoinco/grants-stack/issues/2482
=> fix: make project titles visible

packages/round-manager/src/features/api/utils.ts
=> feat: add dai to pgn

packages/round-manager/src/features/round/ViewRoundSettings.tsx
=> feat(round-settings): fix visual bugs

packages/round-manager/package.json, packages/round-manager/src/context/round/UpdateRoundContext.tsx, pnpm-lock.yaml
=> feat(round-settings): fix round time editing bug

packages/grant-explorer/src/features/api/utils.ts, packages/round-manager/src/features/api/utils.ts
Add usdc as a payout token on polygon
fixes #2508 
fixes #2510
=> Add usdc as a payout token on polygon

packages/grant-explorer/src/features/api/utils.ts
Add dai as donation token to pgn on explorer
fixes #2472
=> Add dai as donation token to pgn on explorer

packages/grant-explorer/src/features/api/utils.ts
Update incorrect chainId for usdc on polgon mumbai testnet
=> update incorrect chainId for usdc on polgon mumbai testnet

packages/builder/src/utils/wagmi.ts, packages/common/src/chains.ts
=> use a custom rpc config for optimism and polygon to avoid errors from public RPC without api key

packages/builder/src/utils/wagmi.ts, packages/common/src/chains.ts
=> override default and public wagmi rpc url in builder

packages/common/src/config.ts, packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/test-utils.tsx
Update getConfig to fix failing tests in manager & explorer
fixes #2539
=> Update getConfig to fix failing tests

packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx, packages/grant-explorer/src/features/discovery/RoundCard.tsx, packages/grant-explorer/src/features/discovery/RoundCardStat.tsx, packages/grant-explorer/src/features/discovery/RoundDaysLeft.tsx, packages/grant-explorer/src/features/discovery/utils/__tests__/getRoundEndedText.test.tsx
- Fixes #2545 
Rounds ended filter:
https://explorer-staging-git-2545-round-ended-grants-stack.vercel.app/#/rounds?status=finished
=> Explorer: Round ended badge

packages/common/src/index.ts, packages/round-manager/src/features/round/ViewRoundSettings.tsx
Update ui on round edit flow in manager
fixes #2522
=> Update ui on round edit flow in manager

packages/grant-explorer/src/features/categories/CategoryCard.tsx, packages/grant-explorer/src/features/collections/CollectionCard.tsx, packages/grant-explorer/src/features/collections/CollectionsGrid.tsx, packages/grant-explorer/src/features/collections/hooks/useCollections.ts, packages/grant-explorer/src/features/common/styles.ts, packages/grant-explorer/src/features/discovery/CardBanner.tsx, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/discovery/RoundsGrid.tsx, packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
- Fixes #2492 
- Fixes #2493 
Todo:
=> Explorer: [2493] Add collections

packages/grant-explorer/src/features/api/round.ts
=> Explorer: [2556] Some application links not loading

packages/grant-explorer/src/cartStore.test.tsx, packages/grant-explorer/src/store.ts
Reverts gitcoinco/grants-stack#2594
=> Revert "Fix Duplicate Cart Items in Explorer"

packages/grant-explorer/src/cartStore.test.tsx, packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx, packages/grant-explorer/src/store.ts
Reverts gitcoinco/grants-stack#2599
=> Fix Duplicate Cart Items in Explorer

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
=> explorer: show spinner in application page while loading

packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/collections/hooks/useCollections.ts, packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
=> Explorer: Use toLowerCase for addresses - fixes tests

packages/grant-explorer/src/features/collections/hooks/useCollections.ts
tested in local, both collections are loading
tests passing
=> Use checksum addresses for application refs

packages/grant-explorer/src/features/discovery/hooks/useApplications.ts
=> Randomize collections & reduce amount of unnecessary requests

packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
As a donor
I want to know if the project I'm looking for is not there
So that I don't waste time looking for a non-existent project
fixes #2588
=> Add partial empty state for project search

packages/grant-explorer/src/features/api/rounds.ts
Hide additional test rounds on explorer
fixes #2589
=> Hide additional test rounds on explorer

lefthook.yml, package.json
- Cap turbo's concurrency at 50% of available CPUs.
- Fixes top-level `test` script which was calling itself recursively.
=> fix: avoid recursive pnpm test; don't let turbo take all cpus

packages/grant-explorer/src/features/collections/hooks/useCollections.ts
Check the explorer homepage for the collection titles
before:
after:
=> Fix Collection Title Casing

packages/grant-explorer/src/hooks/matchingEstimate.ts
the re-validation requests are unnecessarily loading the indexer
=> fix: do not revalidate matching estimates

packages/round-manager/src/context/round/UpdateRoundContext.tsx, packages/round-manager/src/features/round/ViewRoundSettings.tsx
fix unable to edit application end date bug
fixes #2602
=> fix unable to edit application end date bug

packages/grant-explorer/src/features/collections/CollectionsGrid.tsx, packages/grant-explorer/src/features/discovery/RoundsGrid.tsx
=> Explorer: [2634] Mobile UI issues collections

packages/grant-explorer/src/features/collections/CollectionDetails.tsx, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/discovery/LandingSection.tsx, packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
=> Explorer: [2624] Add Live GG19 stats button

packages/grant-explorer/src/features/api/rounds.ts
=> Explorer: [2596] Fix incorrect projects in explore rounds page

packages/grant-explorer/src/features/api/utils.ts
update polygonscan tx explorer link
fixes #2645
=> update polygonscan tx explorer link

packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
fix partial empty state msg issue on categories
fixes #2644
=> fix partial empty state msg issue on categories

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
closes #2615 
* truncate project summary in round page cards 
* show mouse pointer on cart icon
=> truncate project summary in round page cards

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Reverts gitcoinco/grants-stack#2659
=> Revert "truncate project summary in round page cards"

packages/grant-explorer/src/features/common/Navbar.tsx
=> update PGN Bridge link to point to docs

packages/grant-explorer/src/features/collections/CollectionDetails.tsx
close #2608 
Enable add all projects to cart button in collections
=> enable add all projects to cart button in collections

packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
=> temporarily disable matching estimate

packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
=> add disableEstimate var

packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/hooks/matchingEstimate.ts
=> disable all matching estimate

packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
Add copy to donation history page.
fixes #2636
=> Add copy to donation history page

packages/grant-explorer/src/features/collections/CollectionDetails.tsx, packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
=> Explorer: [2695] Add number of projects for add collection to cart

packages/grant-explorer/src/features/round/ThankYou.test.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx
closes #2704
updates the twitter share url based on their new docs: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
=> update twitter share url with the new path

.github/PULL_REQUEST_TEMPLATE.md
Not applicable.
Proposal for new PR template. Automatable items removed or summarized.
=> chore: try new PR template

packages/grant-explorer/src/features/api/utils.ts, packages/round-manager/src/features/api/payoutTokens.ts
Fixes: #issue
Remove usdc as payout & donation token on zksync
This PR:
=> Remove usdc as payout & donation token on zksync

packages/round-manager/src/features/api/payoutStrategy/payoutStrategy.ts, packages/round-manager/src/features/round/ViewFundGrantees.tsx, packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx
Fixes: #issue
payouts fail when paying any projects after paying one because the merkle root is different
This PR:
=> Fix payouts for individual projects

packages/builder/package.json, packages/round-manager/package.json, pnpm-lock.yaml
Fixes: #2757 
fix lit decryption issue in manager on zksync.
This PR:
=> fix lit decryption issue in manager on zksync.

packages/common/src/allo/backends/allo-v1.ts
Fixes: #2834 
updated registry address of the transaction to the actual registry address
This PR:
=> fixing registry address

packages/common/src/allo/backends/allo-v1.ts, packages/common/src/allo/transaction-sender.ts
=> fix send transaction type safety

packages/data-layer/src/backends/legacy.ts, packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/discovery/hooks/__tests__/useFilterRounds.test.tsx
=> temporary fix: active rounds sorting

packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/index.css
closes #2855
closes #2860 
Fixes: #issue
This PR:
=> explorer: enable markdown for any type of answer in round applications

packages/data-layer/src/data-layer.test.ts, packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts, packages/round-manager/src/features/api/__tests__/program.test.ts, packages/round-manager/src/features/api/program.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/test-utils.tsx
Fixes: #2920 
Filter out duplicate bot rounds
This PR:
=> filter out duplicate bot rounds

packages/data-layer/src/data-layer.ts
closes https://github.com/gitcoinco/grants-stack/issues/3031
=> temporary fix to filter out programs not owned by the current user

packages/builder/src/__tests__/components/application/Form.test.tsx, packages/builder/src/__tests__/reducers/projects.test.ts, packages/builder/src/actions/projects.ts, packages/builder/src/actions/roundApplication.ts, packages/builder/src/actions/rounds.ts, packages/builder/src/components/application/Form.tsx, packages/builder/src/components/grants/ApplicationCard.tsx, packages/builder/src/components/grants/rounds/RoundListItem.tsx, packages/builder/src/components/grants/stats/Stats.tsx, packages/builder/src/components/rounds/Apply.tsx, packages/builder/src/components/rounds/Show.tsx, packages/builder/src/components/rounds/ViewApplication.tsx, packages/builder/src/types/index.ts, packages/builder/src/utils/test_utils.tsx, packages/builder/src/utils/utils.ts, packages/common/src/allo/backends/allo-v2.test.ts, packages/data-layer/src/data.types.ts
=> reuse type

packages/common/package.json, packages/common/src/allo/backends/allo-v2.ts, packages/round-manager/src/features/round/RoundApplicationForm.tsx, pnpm-lock.yaml
Fixes #3046 
The recently updated Direct Grants strategy supports now timestamps. This PR updates the common package and the round manager to reflect these changes
=> round manager: update direct grants

packages/builder/src/__tests__/components/application/Form.test.tsx, packages/builder/src/__tests__/reducers/projects.test.ts, packages/builder/src/actions/projects.ts, packages/builder/src/actions/roundApplication.ts, packages/builder/src/actions/rounds.ts, packages/builder/src/components/application/Form.tsx, packages/builder/src/components/grants/ApplicationCard.tsx, packages/builder/src/components/grants/rounds/RoundListItem.tsx, packages/builder/src/components/grants/stats/Stats.tsx, packages/builder/src/components/rounds/Apply.tsx, packages/builder/src/components/rounds/Show.tsx, packages/builder/src/components/rounds/ViewApplication.tsx, packages/builder/src/types/index.ts, packages/builder/src/utils/test_utils.tsx, packages/builder/src/utils/utils.ts, packages/common/src/allo/allo.ts, packages/common/src/allo/backends/allo-v2.test.ts, packages/common/src/allo/backends/allo-v2.ts, packages/data-layer/src/data-layer.test.ts, packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts, pnpm-lock.yaml
This PR adds the feature to be able to apply to direct grants round created on V2.
- Create a Direct Grants round on V2 on manager.
- Use your allo v2 project to apply to it (create one if you don't have one).
- Also try using a project from another chain, this will create a profile on current chain and link your canonical project.
- The application should appear on `Applications` section.
- After clicking on the `view application` button you should see a preview of your application.
NOTE: USE ONLY MUMBAI TO TEST 
Fixes: #2943 
**Round to apply:** https://builder-staging-git-2943-apply-to-direct-round-grants-stack.vercel.app/#/chains/80001/rounds/17
**Manager Link:** need
=> Apply to Direct Round ON MUMBAI

.github/workflows/common.yml, .github/workflows/data-layer.yml, package.json, packages/common/.eslintrc.js, packages/common/package.json, packages/common/src/allo/backends/allo-v1.test.ts, packages/common/src/allo/backends/allo-v1.ts, packages/common/src/allo/backends/allo-v2.ts, packages/common/src/graphql_fetch.ts, packages/common/src/icons/Dropdown.tsx, packages/common/src/index.ts, packages/common/src/transactions.ts, pnpm-lock.yaml
adds checks for common and data layer
fixed some linter issues but some of the bigger ones i just added a eslint ignore comment
=> ifx lint and typecheck for common and datalayer

packages/common/src/payoutTokens.ts, packages/round-manager/src/features/api/payoutTokens.ts
=> add GTC as payout token for arbitrum

packages/round-manager/src/features/round/RoundDetailForm.tsx
Update html elements to avoid having invalid html errors with `p` tags inside are `p` tags
=> fix(Manager): remove invalid html errors in manager

.github/PULL_REQUEST_TEMPLATE.md
Update PR template to add a question about payout/donation tokens
=> Update PR checklist with donation/payout tokens check

packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/useApplicationsByRoundId.tsx
=> set projectId when using GrantApplication for direct payout

packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
another PR to convert p tags to div to avoid invalid html errors
=> fix(Manager): convert p to div to avoid invalid html

packages/round-manager/src/features/round/ViewRoundSettings.tsx
avoid react  errors adding key to elements inside loops
=> fix(Manager): RoundType key in map

docs/DEV.md, packages/builder/.env.example, packages/grant-explorer/.env.example, packages/grant-explorer/src/features/api/utils.ts, packages/round-manager/.env.example
Improve docs and `.env` vars to run Builder in local discussed in #2957
=> improve docs and default .env vars to run builder in local

packages/common/src/allo/backends/allo-v2.ts, packages/common/src/index.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/round/ViewRoundPage.tsx
- Create DG round on allo-v2
Fixes: #3041
=> chore: update for direct v2 create

packages/common/src/allo/backends/allo-v2.ts, packages/common/src/index.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/round/ViewRoundPage.tsx
Reverts gitcoinco/grants-stack#3101
=> Revert "chore: update for direct v2 create"

packages/round-manager/src/features/round/ViewApplicationPage.tsx
=> fix(manager): compare verifiable credential's id and round owners with lowercase strings

packages/common/src/allo/backends/allo-v2.ts, packages/round-manager/src/features/api/round.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/round/FundContract.tsx, packages/round-manager/src/features/round/ViewRoundSettings.tsx, packages/round-manager/src/features/round/ViewRoundStats.tsx, packages/round-manager/src/hooks.ts
Fixes: #3041
NOTE: #3090 should be merged first or we can change the base of this to `edit` branch.
cc: @thelostone-mc @0xKurt
=> support round edit for DG v2

packages/common/src/payoutTokens.ts, packages/round-manager/src/features/api/payoutTokens.ts
fixes https://github.com/gitcoinco/grants-stack/issues/3074
=> chore: add usd glo

packages/round-manager/src/context/round/UpdateRoundContext.tsx, packages/round-manager/src/features/round/ViewRoundSettings.tsx
Fixes: #3100 
In v2 the contract was build in a way, that the timestamps can be updated at any time and also point into the future.
This change reflects these changes on the round manager frontend.
❗️Please merge [3090](https://github.com/gitcoinco/grants-stack/pull/3090) and [3103](https://github.com/gitcoinco/grants-stack/pull/3103) first
This PR:
=> Update timestamp check

packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts, packages/round-manager/src/features/api/round.ts
=> fix: ready for payout

packages/round-manager/src/features/round/CreateRoundPage.tsx
=> fix missing space

packages/common/src/allo/allo.ts, packages/common/src/allo/backends/allo-v1.ts, packages/common/src/allo/backends/allo-v2.ts, packages/round-manager/src/context/round/ReclaimFundsContext.tsx, packages/round-manager/src/context/round/__tests__/ReclaimFundsContext.test.tsx, packages/round-manager/src/features/api/__tests__/utils.test.ts, packages/round-manager/src/features/api/payoutStrategy/payoutStrategy.ts, packages/round-manager/src/features/round/FundContract.tsx, packages/round-manager/src/features/round/ReclaimFunds.tsx, packages/round-manager/src/features/round/__tests__/ReclaimFunds.test.tsx
Fixes: #3139 
Since we don't have old v2 rounds to test, we are postponing QA to the next weeks
=> implement reclaim funds for Allo V2

packages/data-layer/src/queries.ts
Fixes: #3174 
Change `project` to `canonicalProject` in `queries.ts`
This PR:
=> 3174/update project to canonicalProject

packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> fix round strategy label

packages/common/src/allo/backends/allo-v2.ts, packages/data-layer/src/data-layer.ts, packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts, packages/grant-explorer/src/checkoutStore.ts, packages/grant-explorer/src/context/RoundContext.tsx, packages/grant-explorer/src/context/__tests__/RoundContext.test.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx, packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
Fixes: #issue
depends on this one: https://github.com/gitcoinco/grants-stack-indexer/pull/510
This PR:
=> Fix allo v2 voting incorrect anchor address

packages/common/src/allo/backends/allo-v2.ts, packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/features/common/useApplicationsByRoundId.tsx, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ApplicationsRejected.tsx, packages/round-manager/src/features/round/ApplicationsToApproveReject.tsx, packages/round-manager/src/features/round/ApplicationsToReview.tsx, packages/round-manager/src/features/round/ViewFundGrantees.tsx, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/test-utils.tsx
=> fix finalization on allo v2

packages/builder/src/__tests__/components/base/StatusModal.test.tsx, packages/builder/src/actions/roundApplication.ts, packages/builder/src/reducers/roundApplication.ts, packages/builder/src/utils/steps.ts, packages/common/src/allo/allo.ts, packages/common/src/allo/backends/allo-v1.ts, packages/common/src/allo/backends/allo-v2.ts
Fixes: #3143 
- When applying to a round it should show the indexing step in the modal.
- Once the applying to round transaction is successful it should wait for the indexing to complete.
=> wait for indexer when applying to a round on v1

packages/data-layer/src/data-layer.ts, packages/grant-explorer/src/features/projects/hooks/useApplication.ts, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
fixes routes with the format:
https://explorer.gitcoin.co/#/round/424/0x98720dd1925d34a2453ebc1f91c9d48e7e89ec29/0x98720dd1925d34a2453ebc1f91c9d48e7e89ec29-153
https://explorer.gitcoin.co/#/round/424/0xb6e066444fafe576f82b751dd63408f15ea7b5e8/0xb6e066444fafe576f82b751dd63408f15ea7b5e8-0
https://explorer.gitcoin.co/#/round/424/0x98720dd1925d34a2453ebc1f91c9d48e7e89ec29/0x98720dd1925d34a2453ebc1f91c9d48e7e89ec29-6
https://explorer.gitcoin.co/#/round/10/0x1a5a0b247dc3230079ebb4c7c6f258ef3067d010/0x1a5a0b247dc3230079ebb4c7c6f258ef3067d010-0
https://explorer.gitcoin.co/#/round/137/0xbdccbba5c4c5dad41ce020ed725a483e1a43cf0e/0xbdccbba5c4c5dad41ce020ed725a483e1a43cf0e-0
notice the application ID is actually the round id and the application ID
closes …
=> fix explorer applciation routes

packages/builder/src/services/lit.ts, packages/common/src/allo/backends/allo-v2.ts, packages/common/src/components/AlloVersionSwitcher.tsx, packages/round-manager/package.json, packages/round-manager/src/features/api/exports.ts, packages/round-manager/src/features/api/lit.ts, packages/round-manager/src/features/round/ApplicationsToApproveReject.tsx, packages/round-manager/src/features/round/ApplicationsToReview.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, pnpm-lock.yaml
Fixes: #issue
how to test:
- create a round on v2 with and encrypted field (do not use sepolia)
- apply from builder
- go back to manager and check that the field is decrypted when viewing the application
This PR:
=> implement lit encryption and decryption for allo v2

packages/common/src/allo/transaction-sender.ts
=> fix transaction awaiter for non existent error

packages/common/src/chain-ids.ts, packages/round-manager/src/features/api/payoutTokens.ts
=> Add OP token for matching

packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts, packages/grant-explorer/src/store.ts
Fixes: #3227 
- To test: Open the grant explorer page and "Featured Rounds" should be at the top.
This PR:
=> Adds featured rounds

packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts, packages/grant-explorer/src/store.ts
Reverts gitcoinco/grants-stack#3249
=> Revert "Adds featured rounds"

.github/ISSUE_TEMPLATE/bug_report.yml
=> remove bug assignees

packages/common/src/index.ts, packages/data-layer/src/data.types.ts, packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx
Fixes: #3231 
fix: filtering bug in explorer
This PR:
=> Fix filtering bug in explorer

packages/builder/src/components/application/Form.tsx
=> 3182 done button

packages/grant-explorer/src/features/discovery/LandingHero.tsx
fixes https://github.com/gitcoinco/grants-stack/issues/3109
Fixes: #issue
This PR:
=> chore: update text

packages/grant-explorer/src/features/common/Navbar.tsx
Updates Allo version banner copy with dates
=> update allo version banner copy

packages/common/src/index.ts, packages/common/src/styles.ts, packages/grant-explorer/src/features/api/__tests__/passport.test.tsx, packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/common/CopyToClipboardButton.tsx, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/common/StatCard.tsx, packages/grant-explorer/src/features/contributors/DonationsTable.tsx, packages/grant-explorer/src/features/contributors/TransactionButton.tsx, packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx, packages/grant-explorer/src/features/contributors/__tests__/ViewContributionHistory.test.tsx, packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/store.ts, packages/grant-explorer/tailwind.config.js
Fixes: #3280 
Fixes: #3272 
This PR:
=> 2380/ Donations page overhaul

packages/data-layer/src/data-layer.ts, packages/data-layer/src/queries.ts
=> add a limit to all graphql queries

packages/grant-explorer/src/features/discovery/LandingTabs.tsx, packages/grant-explorer/src/index.tsx
=> add back proj tab

packages/grant-explorer/src/features/discovery/LandingTabs.tsx, packages/grant-explorer/src/index.tsx
Reverts gitcoinco/grants-stack#3321
=> Revert "add back proj tab"

packages/common/src/allo/backends/allo-v2.ts
https://discord.com/channels/562828676480237578/1231878578426347520/1231938455848620053
fixes https://github.com/gitcoinco/grants-stack/issues/3340
=> fix: ensure we get total Applications from contract

packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Fixes: #3346 
fix passport ui issue in gg20 rounds
This PR:
=> fix passport ui issue in gg20 rounds

packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
Fixes: #issue
Adds "* Please note that your recent transactions may take a short while to reflect in your donation history, as processing times may vary." to the contribution history page.
This PR:
=> add copy to contribution history page

packages/data-layer/src/data-layer.ts, packages/data-layer/src/queries.ts, packages/grant-explorer/src/features/projects/hooks/useRoundApplications.ts, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
=> fix loading app request for explorer

packages/grant-explorer/src/features/round/CollectionShareDialog.tsx
=> fix collection share loop

packages/builder/src/components/grants/stats/Stats.tsx, packages/builder/src/styles/index.css, packages/builder/tailwind.config.js
link to https://gitcoindonordata.xyz/ for more project stats
this is under the project detail => stats
=> add project stats dashboard to builder

packages/data-layer/src/data-layer.ts, packages/data-layer/src/openapi-search-client/apis/DefaultApi.ts, packages/data-layer/src/openapi-search-client/models/ApplicationSummary.ts, packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
=> [wip] add anchor to collections

packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx, packages/grant-explorer/src/features/discovery/LandingTabs.tsx
=> disable project explore tab

packages/common/src/index.ts, packages/grant-explorer/src/features/collections/CollectionCard.tsx, packages/grant-explorer/src/features/collections/hooks/useCollections.ts, packages/grant-explorer/src/features/common/Navbar.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Fixes: #3402 
Fixes typo in Navbar.tsx (explorer) dropdown and removes some unused imports.
This PR:
=> Navbar typo fix and linting

packages/grant-explorer/src/features/collections/community/index.ts
what the title says
(just a config change)
=> adds more collections as they roll in from the community

packages/grant-explorer/.env.example, packages/grant-explorer/package.json, packages/grant-explorer/src/features/common/ProjectCard.tsx, packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx, packages/grant-explorer/src/features/discovery/PaginatedProjectsList.tsx, packages/grant-explorer/src/index.tsx, packages/grant-explorer/src/posthog.ts, pnpm-lock.yaml
Fixes: #3405 
Adds PostHog with new account. All Grants Labs team members have been invited to the new account.
This PR:
=> update posthog with new account

packages/data-layer/src/data-layer.ts
=> increase collection size to 300

packages/data-layer/src/data-layer.test.ts
=> update indexer to production URL for tests

packages/common/src/index.ts, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
Fixes: #issue
Map gg20 rounds as passport-mbds rounds
This PR:
=> map gg20 rounds as passport-mbds rounds

packages/common/src/chains.ts
Fixes: #issue
SEI explorer link https://seistrace.com/ -> https://seitrace.com/
Fixes SEI explorer link from unrelated Nigerian oil and gas company site to actual explorer.
This PR:
=> fix SEI explorer link

packages/common/src/allo/backends/allo-v2.ts
=> update direct grants deployments

packages/common/src/chains.ts, packages/common/src/icons/lukso-logo.svg, packages/grant-explorer/public/logos/lukso-logo.svg, packages/round-manager/public/logos/lukso-logo.svg
Fixes: LUKSO logo and all-caps styling.
LUKSO provided feedback that they preferred an alternate logoset, and all-caps styling.
This PR:
=> update lukso's logo + styling

packages/round-manager/src/features/round/ViewFundGrantees.tsx, packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx
Reverts gitcoinco/grants-stack#3441
=> Revert "disabled payout"

packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
=> remove grantscan

packages/common/src/allo/allo.ts, packages/common/src/allo/backends/allo-v1.ts, packages/common/src/allo/backends/allo-v2.ts, packages/round-manager/src/context/round/FundContractContext.tsx, packages/round-manager/src/features/round/FundContract.tsx
Fixes: #issue
fix erc20 fund contract safe approval bug
This PR:
=> fix erc20 fund contract safe approval bug

packages/common/src/allo/allo.ts, packages/common/src/allo/backends/allo-v1.ts, packages/common/src/allo/backends/allo-v2.ts, packages/round-manager/src/context/round/UpdateRolesContext.tsx, packages/round-manager/src/features/round/ViewManageTeam.tsx, packages/round-manager/src/features/round/ViewRoundPage.tsx, packages/round-manager/src/index.tsx
Add Ability to Add / Remove members
=> Add Manage Team feature

packages/round-manager/src/features/api/__tests__/program.test.ts, packages/round-manager/src/features/api/program.ts, packages/round-manager/src/features/api/types.ts, packages/round-manager/src/test-utils.tsx
Remove program filter
see https://discord.com/channels/562828676480237578/1234146304108531852
=> Remove program filter

docs/DEV.md
Fixes: #issue
update docs after merging https://github.com/gitcoinco/grants-stack/pull/3467
also remove subgraph references.
This PR:
=> update docs to match unified env

packages/round-manager/src/features/round/ViewRoundSettings.tsx
=> fix: edit match amount post round end

packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/program/CreateProgramPage.tsx, packages/round-manager/src/features/round/ViewRoundSettings.tsx
=> fix SEI Mainnet name

packages/grant-explorer/src/features/round/ViewRoundPage.tsx
context: https://discord.com/channels/562828676480237578/1011735006764351609/1247918012007190569
=> fix token symbol

packages/data-layer/src/data-layer.ts, packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts, packages/grant-explorer/src/features/projects/ViewProject.tsx, packages/grant-explorer/src/features/projects/hooks/useProject.ts
Fixes: #issue
Test project link: https://explorer-git-explorer-project-page-2-grants-stack.vercel.app/#/projects/0x7c2db89015825d83f56cd55aff50b2ac0a8b50338d88c2988323ce6fa7739d1a
Add stats sidebar & past rounds tab
This PR:
=> Add stats sidebar & past rounds tab

packages/common/package.json, pnpm-lock.yaml
=> remove op usdc / update chain data package

packages/grant-explorer/src/features/projects/ViewProject.tsx
Fixes: #issue
Add active rounds in sidetab 
This PR:
=> Add active rounds in sidetab

packages/grant-explorer/src/features/round/KarmaGrant/MilestoneUpdate.tsx
Fixes: Render milestone updates text as markdown
Small changes on the [Karma-GAP](https://gap.karmahq.xyz/) grant integration
- Render milestone updates description as markdown
This PR:
=> [KARMA-GAP] Render milestone updates as markdown

packages/grant-explorer/src/features/api/utils.ts
Fixes: #issue https://github.com/gitcoinco/grants-stack/issues/3536
Our data layer is not checking if round dates are null when fetched from the indexer:
getRoundForExplorer() -> packages/data-layer/src/data-layer.ts
Converting null to Date becomes -> `1970-01-01T00:00:00.000Z` (timestamp 0 / Computer Dinosaur Age)
That's the main issue, depending on the timezone, it can be greater or lower than that.
One solution would be to convert all dates to UTC and make calculations from there.
Another solution would be that the data-layer leave null dates as null or undefined instead of converting it.
We currently have this function to address this issue:
```
export const isInfiniteDate = (roundTime: Date) => {
return (
roundTime.toString() === "Invalid Date" || roundTime.getFullYear() === 1970
); …
```
=> fix: isInfiniteDate should check if year is lower or equal to 1970

packages/grant-explorer/src/features/round/ViewCartPage/Header.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx
=> add share button

packages/grant-explorer/src/features/api/utils.ts, packages/grant-explorer/src/features/round/ApplicationsCountdownBanner.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Fixes: https://github.com/gitcoinco/grants-stack/issues/3535
- (explorer) src/features/api/utils.ts
- included `allov2.DirectGrantsSimpleStrategy` in isDirectRound() check function
- (explorer) src/features/round/ApplicationsCountdownBanner.tsx
- ApplicationsCountdownBanner now handles direct rounds without application period end date, displaying the message `Applications are open`
- (explorer) src/features/round/ViewRoundPage.tsx
- Donation time period now is not rendered in direct rounds
This PR:
=> fix(explorer): direct rounds not displayed correctly

.github/workflows/builder.yml, .github/workflows/common.yml, .github/workflows/data-layer.yml, .github/workflows/grant-explorer.yml, .github/workflows/round-manager.yml, .github/workflows/verify-env.yml, packages/round-manager/src/features/api/utils.ts, packages/round-manager/src/features/common/styles.ts, packages/round-manager/src/features/common/useApplicationsByRoundId.tsx, packages/round-manager/src/features/round/ApplicationsApproved.tsx, packages/round-manager/src/features/round/ViewApplicationPage.tsx
=> fix project loading bug

packages/round-manager/src/features/round/ViewApplicationPage.tsx
fixes #3555
Fixes: #issue
This PR:
=> fix: chainId is NaN

packages/common/src/allo/backends/allo-v2.ts
=> add poolId and strategy for direct allocation

packages/common/package.json, pnpm-lock.yaml
Fixes: BLU-138
Update gitcoin chain data package to add glo support to gs on celo
This PR:
=> feat: update gitcoin chain data package to add glo support to gs on celo

packages/data-layer/src/queries.ts, packages/grant-explorer/src/features/common/ProjectCard.tsx
=> ignore project and round with no metadata

packages/common/src/index.ts, packages/data-layer/src/data-layer.ts, packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts, packages/grant-explorer/src/features/common/BaseModal.tsx, packages/grant-explorer/src/features/common/Button.tsx, packages/grant-explorer/src/features/common/SwitchNetworkModal.tsx, packages/grant-explorer/src/features/contributors/DirectDonationTable.tsx, packages/grant-explorer/src/features/contributors/DirectDonationsTable.tsx, packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx, packages/grant-explorer/src/features/contributors/__tests__/ViewContributionHistory.test.tsx, packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx, packages/grant-explorer/src/features/projects/ViewProject.tsx, packages/grant-explorer/src/features/projects/__tests__/ViewProject.test.tsx
Fixes: BLU-79
Fixes: BLU-149
You can see direct donations here: https://explorer-git-direct-donation-history-grants-stack.vercel.app/#/contributors/0xc24e3C2e72f960fa1d54170Fa03492DDa4cE8256
=> feat: show direct donations on donation history page

packages/data-layer/src/queries.ts
=> Fix direct allocation query

packages/common/package.json, pnpm-lock.yaml
Fixes: BLU-143
Update gitcoin chain data package to fix scroll usdc issue
This PR:
=> feat: update gitcoin chain data package

packages/builder/src/components/base/images/ImageCrop.tsx, packages/builder/src/utils/datadog.tsx, packages/grant-explorer/src/datadog.tsx, packages/round-manager/src/datadog.tsx
=> chore: fix some comments

packages/grant-explorer/src/features/projects/ViewProject.tsx
Fixes: BLU-158
Fix ui alignment in donation component
This PR:
=> fix: ui alignment in donation component

packages/common/package.json, pnpm-lock.yaml
=> update chaindata version

packages/common/package.json, pnpm-lock.yaml
=> chain data version bump

packages/common/package.json, pnpm-lock.yaml
Fixes: #issue
Update chain data version to fix arb donation issue
This PR:
=> feat: update chain data version

packages/common/package.json, pnpm-lock.yaml
=> Remove TEC (bump chain data version)

packages/grant-explorer/src/features/collections/community/index.ts, packages/grant-explorer/src/features/contributors/DirectDonationsTable.tsx, packages/grant-explorer/src/features/discovery/LandingPage.tsx
=> enable collections

packages/builder/src/components/rounds/Show.tsx, packages/builder/src/utils/components.ts
Fixes: PAR-321
Update utc to local time in builder
This PR:
=> feat: update utc to local time in builder

packages/grant-explorer/src/features/api/rounds.ts, packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
=> requiring round metadata and roundtype to filter

packages/common/package.json, pnpm-lock.yaml
=> Bumping chain data

packages/common/package.json, pnpm-lock.yaml
=> Update MATIC to POL

packages/common/package.json, packages/common/src/chains.ts, pnpm-lock.yaml
=> Add Gnosis Chain

packages/common/package.json, pnpm-lock.yaml
=> bump sdk version

packages/builder/src/components/grants/stats/StatCard.tsx, packages/builder/src/components/grants/stats/Stats.tsx, packages/data-layer/src/data-layer.ts, packages/data-layer/src/data.types.ts, packages/data-layer/src/queries.ts
- Fix the graphql query 
- Compute stats on the front end
https://builder-git-par-388-grants-stack.vercel.app/#/chains/137/registry/0x/projects/0x78881afb3fd01b3bf074adfb6756742818da0b9efc2840ee0dc0fc9bf4ea8a2e
https://builder-git-par-388-grants-stack.vercel.app/#/chains/1088/registry/0x/projects/0xec2609dcea60222524e96e8cf9baf444dcbacde7475ee83cb5c8b74635496d47
closes PAR-388
=> fix:  direct allocation stats

packages/grant-explorer/package.json, packages/grant-explorer/src/features/api/types.ts, packages/grant-explorer/src/features/common/GenericModal.tsx, packages/grant-explorer/src/features/discovery/RoundMatchAmountBadge.tsx, packages/grant-explorer/src/features/projects/ViewProject.tsx, packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx, packages/grant-explorer/src/features/round/ViewCartPage/EmptyCart.tsx, packages/grant-explorer/src/features/round/ViewCartPage/PayoutTokenButton.tsx, packages/grant-explorer/src/features/round/ViewCartPage/PayoutTokenDropdown.tsx, packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SquidWidget.tsx, packages/grant-explorer/src/features/round/ViewCartPage/Summary.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx, pnpm-lock.yaml
=> feat: add bridging widget to checkout

packages/grant-explorer/src/features/api/oso.ts, packages/grant-explorer/src/features/common/GenericModal.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SquidWidget.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/features/round/ViewCartPage/ViewCartPage.tsx
=> bump : squid widget

packages/builder/src/components/grants/stats/Stats.tsx
due to issues with squarespace we temorarily lost access to gitcoindonordata.xyz so we've purchased a new domain and set up the deployment to serve traffic from the new domain instead
Fixes: #issue
This PR:
=> Update Stats.tsx to point towards new gitcoindonordata domain

packages/grant-explorer/src/features/attestations/MintYourImpactComponents.tsx, packages/grant-explorer/src/features/attestations/utils/constants.ts, packages/grant-explorer/src/features/contributors/components/Buttons/MintDonationImpactAction.tsx, packages/grant-explorer/src/features/contributors/hooks/useMintingAttestations.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/hooks/attestations/config.ts, packages/grant-explorer/src/hooks/attestations/useAttestMutation.ts, packages/grant-explorer/src/hooks/attestations/useEASAttestation.ts, packages/grant-explorer/src/hooks/attestations/useEASConfig.ts, packages/grant-explorer/src/hooks/attestations/useGetAttestationData.ts, packages/grant-explorer/src/hooks/attestations/utils/createContractCallArgs.ts
**Improves**
- Attestations fee handling 
- No funds error handling
- Distinguishes proxy delegation requests with delegation requests
=> dynamic handling of fees and proxy attestations implementation

packages/grant-explorer/src/features/common/ShareButtons.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Fixes: #issue
This PR updates the farcaster share URLs to properly support embedded links and mentions per the [warpcast docs](https://docs.farcaster.xyz/reference/warpcast/cast-composer-intents).
This PR:
=> fix farcaster links

packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
=> show squid widget always

packages/grant-explorer/src/features/common/ShareButtons.tsx, packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Fixes: #issue
Quick fix to use map instead of forEach and encode text
This PR:
=> fix: map embed urls and encode text

packages/grant-explorer/src/features/attestations/MintYourImpactComponents.tsx, packages/grant-explorer/src/features/common/ShareButtons.tsx, packages/grant-explorer/src/features/common/components/ImageWithLoading.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx, packages/grant-explorer/src/index.css
- Attestation UI improvements
fixes PAR-557
=> Mint attestations UI improvements

packages/grant-explorer/src/features/contributors/components/RoundDonations/TransactionHeader.tsx, packages/grant-explorer/src/features/round/ThankYou.tsx
Reverts gitcoinco/grants-stack#3690
=> release attestations

packages/common/package.json, packages/common/src/chains.ts, pnpm-lock.yaml
=> updated chain data version and rainbow config

packages/grant-explorer/src/features/api/gap.ts, packages/grant-explorer/src/features/round/KarmaGrant/GrantList.tsx, packages/grant-explorer/src/features/round/KarmaGrant/ImpactItem.tsx, packages/grant-explorer/src/features/round/KarmaGrant/ImpactList.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Feature: Display project impacts from [GAP](https://gap.karmahq.xyz/)
Changes on the [Karma-GAP](https://gap.karmahq.xyz/) integration
- Add a section to display project impacts from GAP
This PR:
=> [KARMA-GAP] Add project impacts section

packages/grant-explorer/src/features/collections/CollectionCard.tsx, packages/grant-explorer/src/features/collections/community/index.ts, packages/grant-explorer/src/features/collections/hooks/useCollections.ts, packages/grant-explorer/src/features/discovery/CardBanner.tsx, packages/grant-explorer/src/features/discovery/LandingPage.tsx, packages/grant-explorer/src/features/round/KarmaGrant/ImpactItem.tsx, packages/grant-explorer/src/features/round/ViewCartPage/Summary.tsx, packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx, packages/grant-explorer/src/hooks/attestations/useAttestMutation.ts, pnpm-lock.yaml
change data source for community collections
=> Whitelist collection

package.json, packages/grant-explorer/src/features/round/CopyToClipboard.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Fixes: Allows for the user to copy the project owner's address to their clipboard.
This PR:
=> added copy functionality to project owner address on ViewProjectDetails page.

packages/common/package.json
=> chore: apply fix version dependency allo sdk

funding.json
=> adds filecoin drips account safe address

packages/builder/src/utils/roundApplication.ts
=> handle no question scenario

packages/data-layer/src/queries.ts
Fixes: #3760 
chain IDs were missing from queries that made projects on those chains unsearchable. added several missing chains.
This PR:
=> added chains to query

packages/builder/src/components/base/InputLabel.tsx, packages/builder/src/components/providers/Github.tsx, packages/builder/src/components/providers/Twitter.tsx, packages/builder/src/components/providers/identity/credentials.ts
=> Fix twitter verification

packages/builder/src/actions/rounds.ts
=> fix: retrofunding application dates on builder

packages/builder/src/components/providers/identity/credentials.ts
=> fix github verification

packages/builder/src/components/grants/ApplicationCard.tsx
=> tweak builder checker wording

.env.example, packages/grant-explorer/public/index.html, packages/grant-explorer/src/datadog.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/ViewProjectDetails.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/ApplicationFormAnswers.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/CalendarIcon.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/CartButtonToggle.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/Detail.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/ProjectDetailsTab.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/ProjectLink.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/ProjectLinks.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/ProjectLogo.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/ProjectStats.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/Sidebar.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/StakingBannerAndModal/StakingBanner.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/StakingBannerAndModal/StakingBannerAndModal.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/StakingBannerAndModal/StakingModal.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/StakingBannerAndModal/hooks/useIsDonationPeriod.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/StakingBannerAndModal/hooks/useIsStakable.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/StakingBannerAndModal/index.ts, packages/grant-explorer/src/features/round/ViewProjectDetails/components/Stat.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/VerifiedBadge.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/components/index.ts, packages/grant-explorer/src/features/round/ViewProjectDetails/hooks/useProjectDetailsParams.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/index.ts
=> feat: implement staking flow

packages/data-layer/src/data.types.ts, packages/round-manager/src/features/api/payoutStrategy/payoutStrategy.ts, packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx, packages/round-manager/src/test-utils.tsx
=> fix matching distribution

.github/ISSUE_TEMPLATE/dataRequest.md
Corrected "indictor" to "indicator"
=> Typo in the dataRequest.md

packages/grant-explorer/src/features/common/DefaultLayout.tsx
=> chore:small ui fix

packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
=> fix bug cart

packages/data-layer/src/data-layer.ts, packages/round-manager/src/features/round/usePayouts.tsx
=> fix direct grants payout table

packages/builder/src/components/providers/identity/credentials.ts
=> added gh verification error message

packages/grant-explorer/src/features/round/ViewRoundPage/ProjectCard.tsx
=> Fix decimals staked

.env.example, packages/grant-explorer/src/features/round/DonateToGitcoinContext.tsx, packages/grant-explorer/src/features/round/ViewRoundPage/RoundPage.tsx
=> chore: set donation default to true

packages/grant-explorer/src/features/round/DonateToGitcoinContext.tsx
show only donate to gitcoin for supported chains
=> donate to gitcoin fix

packages/common/src/allo/backends/allo-v2.ts, packages/data-layer/src/data-layer.ts
=> fix donate to gitcoin

packages/grant-explorer/src/features/round/ViewProjectDetails/components/Detail.tsx
=> fix: Detail component prose-pre style to fix width

.env.example, packages/grant-explorer/src/features/api/gap.ts, packages/grant-explorer/src/features/round/KarmaGrant/ActivityItem.tsx, packages/grant-explorer/src/features/round/KarmaGrant/ActivityList.tsx, packages/grant-explorer/src/features/round/ViewProjectDetails/ViewProjectDetails.tsx
Added new section to Impact Measurement tab on project page of explorer. 
It have brings the updates/activities along with deliverables block and indicators/metrics with datapoints.
As some projects doesn't have it, there is a few projects that contains project activities.
`<localUrl>/#/round/42161/29/87`
`<localUrl>/#/round/42161/29/2`
This PR:
=> feat: project activities
